# -*- coding: utf-8 -*-
"""City x service pages, part A: Sarasota, Siesta Key, Longboat Key, Palmer Ranch, Gulf Gate, Fruitville & Bee Ridge.
Every page is written for that locality and that service; the shared helper only assembles the frame."""
from _data import CITIES, SERVICES, cs_route
from _h import cap, sec, p, ul, table, note, cta, reviewed, svc_link, city_link, link, facts, cards
from templates import lead_form

SRC = "Planning band from the September 10, 2026 cost tables; not a quote."


def page(city, service, title, meta, h1, lede, capsule_q, capsule_a, diff_html, rules_html, example_html, local_q, local_a, resources):
    c, s = CITIES[city], SERVICES[service]
    pillar = ("Concrete", "/concrete/") if s["pillar"] == "concrete" else ("Pavers", "/pavers/")
    body = facts([("Jurisdiction", c["jurisdiction"]), ("Permit page", link(c["permit_route"], "rules and office")), ("Drive from Sarasota", c["drive"]), ("Service", svc_link(service))])
    body += cap(capsule_q, capsule_a, '<p class="src-note">' + SRC + '</p>')
    body += sec(f"What's different about {s['nav'].lower()} in {c['name']}", diff_html)
    body += sec("Rules that apply here", rules_html)
    body += sec("A worked example", example_html)
    body += cap(local_q, local_a)
    body += sec("Where to go next", cards([(s["route"], s["name"], "Full spec and FAQ."), (f"/areas/{city}/", c["name"], "Rules, ground, housing.")] + resources))
    body += sec(f"Request an estimate in {c['name']}", lead_form(city=c["name"], service=s["name"]))
    body += reviewed("September 10, 2026")
    return {"route": cs_route(city, service), "title": title, "meta_description": meta, "h1": h1, "kicker": f"{pillar[0]} · {c['name']}", "lede": lede,
            "breadcrumbs": [("Home", "/"), pillar, (s["name"], s["route"]), (c["name"], None)], "body_html": body, "faq": [(local_q, local_a)]}


def get_pages():
    P = []
    # ---------------------------------------------------------------- SARASOTA (city)
    P.append(page("sarasota", "concrete-pool-decks", "Concrete Pool Decks in Sarasota, FL – City Permits & Cost", "Concrete pool decks inside the City of Sarasota: $9 to $14 per sq ft planning band, the city's FTG permit review, AE zones on Bird Key and Lido, the west-of-Trail slab problem and a worked example.",
        "Concrete pool decks in the City of Sarasota", "New and replacement decks for west-of-Trail ranches, Arlington Park block homes and the bayfront keys, permitted by the city.",
        "What does a concrete pool deck cost inside Sarasota city limits?", "About $9 to $14 per square foot for a new textured 4-inch deck on compacted base, so a 600-square-foot deck behind a Southside Village ranch runs roughly $5,500 to $8,500 before demolition of the old slab ($2 to $4 per square foot) and deck drains. Bird Key and Lido Key add 5 to 10 percent for bridge timing and salt-resistant mix.",
        p("City lots west of the Trail and in Arlington Park were built in the 1950s and 60s with pool decks that came later and thinner; many are 3-inch slabs on sand with cool-deck overlays from the 1990s. The bayfront keys (Bird Key, Lido, St. Armands) are on fill over shell in AE zones with VE on Lido's Gulf face, so decks there are pitched to drains that reach the bay side of the lot and poured with a low water-cement mix for spray.") + p("The city's tree rules shape deck extensions: a live oak within the deck footprint means a floating slab section or a smaller deck, because root pruning on a trunk over 4 inches needs a permit."),
        p(f'The City of Sarasota reviews a deck replacement through its FTG portal ({link("/permits/city-of-sarasota/", "city permit page")}); Lido Key falls under turtle lighting from May 1 to October 31; Bird Key and Lido are AE and VE, where a deck is a site improvement outside the 50 percent calculation but documented. Historic districts (Indian Beach, Sapphire Shores, Laurel Park) review visible changes.'),
        p("A 1961 ranch in Arlington Park with a 580-square-foot deck, 3 inches thick, cool-deck overlay from 1996 delaminating in sheets. Sounding found the slab hollow at the coping and under the cage line. Scope: demolition, 4 inches of compacted base, a new 4-inch 4,000 PSI fiber deck with #3 bar at the cage line, two deck drains to a dry well, knockdown texture in a light sand tone, cage re-anchored. City permit through FTG. Planning band: $6,500 to $9,500."),
        "Does a pool deck on Bird Key need anything a deck in Arlington Park doesn't?", "Two things: a low water-cement mix and a penetrating sealer for the bay spray, and drains that carry water to the seawall side rather than to the street, because the lots are flat fill at a few feet of elevation. The permit office is the same city portal; the flood zone (AE) is noted on the scope.",
        [("/pricing/pool-decks/", "Pool deck cost guide", "Every material for 400 to 1,000 square feet."), ("/compare/resurface-vs-replace-pool-deck/", "Resurface or replace", "Six tests before an overlay.")]))
    P.append(page("sarasota", "pavers-pool-decks", "Paver Pool Decks in Sarasota, FL – Travertine, Pavers, Permits", "Paver pool decks inside the City of Sarasota: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft planning bands, city permit review, Lido and Bird Key salt and lighting rules, and a worked example.",
        "Paver pool decks in the City of Sarasota", "Travertine, marble and concrete pavers around pools from Harbor Acres to Lido Key, on a base that drains to the bay side.",
        "What does a paver pool deck cost inside the City of Sarasota?", "Concrete pavers run about $13 to $16 per square foot installed and travertine $20 to $26, so a 700-square-foot deck lands near $9,000 to $11,000 in pavers or $14,000 to $18,000 in stone, plus demolition, coping ($25 to $60 per linear foot) and a deck drain. On Lido and Bird Key add 5 to 10 percent for logistics.",
        p("The city's paver deck market is the bayfront and west of the Trail: Harbor Acres, Bird Key, Lido Shores and St. Armands renovations that continue a marble or porcelain interior floor onto the lanai, and Southside Village and Cherokee Park homes replacing a 1980s deck with travertine. Salt reaches every bayfront deck, so coping on a salt pool is sealed annually and the field is rinsed; on Lido's Gulf side the edge restraint is a concrete curb and the lighting is amber.") + p("Downtown and Rosemary District townhomes have small courtyard pools where large-format porcelain on a mortar bed over the existing slab keeps the floor height under the sliders."),
        p(f'City permit review through FTG for a deck replacement ({link("/permits/city-of-sarasota/", "city rules")}); {link("/permits/sea-turtle-lighting/", "turtle lighting")} on Lido Key; AE and VE on the keys; historic review in designated districts; condo boards on Lido and St. Armands for common decks.'),
        p("A 1972 canal home on Bird Key with a 760-square-foot concrete deck spalled at the coping from a salt pool. Scope: demolition, a 4-inch compacted limerock base over geotextile, linear deck drain at the cage low side, travertine bullnose coping mortar-set on the beam, tumbled ivory travertine field in a French pattern, concrete curb at the seawall side and the cage line, polymeric sand on a dry day, sealing at 30 days with annual coping sealing on the care sheet. City permit. Planning range: $17,000 to $22,000."),
        "Is travertine a mistake on a Bird Key salt pool?", "Not if the owner commits to sealing the coping every year and rinsing the field; if not, dense concrete pavers or porcelain are the right call. The estimate says which the owner chose and writes the sealing date on the care sheet.",
        [("/pavers/travertine-shellstone/", "Travertine and shellstone", "Finishes and the salt rule."), ("/compare/travertine-vs-concrete-pavers/", "Travertine vs concrete pavers", "Cost, heat, salt, repair.")]))
    P.append(page("sarasota", "concrete-driveways", "Concrete Driveways in Sarasota, FL – Apron Permit & Cost", "Concrete driveway replacement inside the City of Sarasota: $7 to $12 per sq ft planning band, the city-owned apron rule, oak protection, 1950s slabs west of the Trail and a worked example.",
        "Concrete driveways in the City of Sarasota", "Replacing 1950s and 60s slabs west of the Trail and in Arlington Park, with the apron poured to the city's detail under its own permit.",
        "What does a concrete driveway cost inside Sarasota city limits?", "About $7 to $12 per square foot installed, so a 480-square-foot single-car-plus driveway typical of a west-of-Trail lot runs roughly $3,500 to $5,800, plus $1,000 to $1,900 for demolition and $500 to $2,500 for the apron in the city right-of-way, which needs its own city permit and detail.",
        p("City driveways are old and narrow: 1950s ribbon drives and 9-foot single-car slabs in Southside Village, Cherokee Park and Indian Beach, poured at 3 to 3.5 inches on sand with no joints. Replacement widens them where the lot allows, keeps the live oaks (the city protects trunks over 4 inches and root pruning needs a permit), and pours the apron between the sidewalk and the curb to the city's detail because that strip is city property.") + p("Bird Key and Lido driveways are short and flat on fill; the issue there is salt on the surface and the ARC in Bird Key's association."),
        p(f'The apron is city right-of-way and needs a permit; the private portion is reviewed through the FTG portal ({link("/permits/city-of-sarasota/", "City of Sarasota permits")}); trees with trunks 4 inches and up need a permit to prune roots; historic districts review visible changes.'),
        p("A 1956 home in Cherokee Park with a 9-by-45-foot ribbon driveway broken into a dozen pieces and a live oak whose roots had lifted the apron. Scope: demolition, root zone bridged with a thickened slab section over compacted stone (no cutting), driveway widened to 12 feet on four compacted inches of crushed base, 4-inch 4,000 PSI fiber concrete with #3 bar, joints at 8 feet, apron poured to the city detail under the apron permit. Budget band: $6,000 to $8,500."),
        "Can the driveway be widened on a 50-foot city lot?", "Usually to 12 feet on one side without crossing a setback, and the apron can't exceed the width the city's detail allows for the curb cut. The site plan shows both; the city reviews the apron.",
        [("/compare/concrete-vs-pavers-driveway/", "Concrete vs pavers", "Twenty-year cost."), ("/concrete/sidewalks-walkways/", "Walks", "The entry walk that usually goes with it.")]))
    P.append(page("sarasota", "pavers-driveways", "Paver Driveways in Sarasota, FL – City Apron Rules & Cost", "Paver driveways inside the City of Sarasota: $14 to $22 per sq ft planning band, the apron in the city right-of-way, clay brick in the historic neighborhoods, Bird Key and Lido logistics, and a worked example.",
        "Paver driveways in the City of Sarasota", "Concrete and clay pavers for west-of-Trail and bayfront homes, with the apron handled under the city's right-of-way rules.",
        "What does a paver driveway cost inside the City of Sarasota?", "About $14 to $22 per square foot installed, so a 500-square-foot driveway on a west-of-Trail lot runs roughly $7,000 to $11,000, plus $1,000 to $2,000 for demolition and the apron, which the city reviews separately and may require in concrete to its detail. Bird Key and Lido add 5 to 10 percent.",
        p("Clay brick pavers in running bond suit the 1920s to 1950s neighborhoods (Indian Beach, Sapphire Shores, Laurel Park) and pass historic review more easily than modern blends; concrete pavers in herringbone suit the mid-century ranches and the bayfront rebuilds. Lots are small, so the driveway is often 10 to 12 feet wide and 40 to 50 feet long, and the border does most of the design work.") + p("Bayfront lots on Bird Key and Lido carry salt; sealer runs 18 to 24 months and the edge at the street is a concrete curb."),
        p(f'Apron: city right-of-way, city permit, city detail (concrete, or pavers where the city allows); private portion through FTG ({link("/permits/city-of-sarasota/", "rules")}); tree permits over 4 inches; Bird Key Improvement Association reviews driveway changes.'),
        p("A 1948 Sapphire Shores bungalow with a 10-by-42-foot cracked ribbon driveway. Scope: demolition, 6 inches of compacted base in lifts, clay brick pavers in running bond with a sailor-course border, concrete curb at the sidewalk, apron poured in concrete to the city detail under the apron permit, irrigation sleeved. Historic review for the visible change took three weeks. Cost band: $8,000 to $10,500."),
        "Does the city allow pavers all the way to the curb?", "Where the city's detail allows a paver apron, yes, under the right-of-way permit; where it doesn't, the apron is concrete to the detail and the pavers start at the sidewalk. The permit review answers it for your street.",
        [("/pavers/walkways-steps/", "Paver walkways", "The entry walk to match."), ("/pavers/sealing/", "Sealing", "The bayfront cycle.")]))
    P.append(page("sarasota", "concrete-repair", "Concrete Repair in Sarasota, FL – Cracks, Lifting, Spalling", "Concrete repair inside the City of Sarasota: crack sealing, polyurethane lifting and spall patching with planning bands, why 1950s slabs west of the Trail fail, bayfront spalling and a worked example.",
        "Concrete repair in the City of Sarasota", "Settled walks, cracked driveways and spalled bayfront decks diagnosed with a level, a hammer and a hose.",
        "What does concrete repair cost in the City of Sarasota?", "Crack routing and sealing about $8 to $20 per linear foot, polyurethane slab lifting $500 to $2,500 per settled area, spall patching $10 to $18 per square foot, panel replacement $400 to $900 per panel. On a 1950s 3-inch slab the honest answer is often replacement, and the estimate says so.",
        p("City repair calls split by neighborhood: settled entry walks and driveway panels on the 1950s slabs west of the Trail, where the base was never compacted; spalling on bayfront pool decks and seawall-side slabs on Bird Key and Lido, where salt reaches the surface; and trip hazards on private walks under live oaks, where the root can't be cut without a permit.") + p("Lifting works on the sand under the ranches when the water source is fixed first; on a slab that's 3 inches thick and cracked in a dozen pieces, lifting buys a year."),
        p(f'Repairs that don\'t change the footprint are generally below the city\'s permit thresholds; public sidewalks are city right-of-way (report, don\'t repair); tree roots on trunks over 4 inches need a permit to prune ({link("/permits/city-of-sarasota/", "city rules")}).'),
        p("A 1963 Southside Village home with a front walk lifted 1.25 inches by an oak root and a garage-apron panel dropped half an inch. Scope: walk panel replaced with a bridge section over the root on compacted stone (no root cut), apron panel lifted with polyurethane foam after a leaking irrigation line under it was repaired, joints sealed. Half a day plus a small pour. Planning band: $1,400 to $2,200."),
        "Can a spalled seawall-side slab on Bird Key be patched?", "If it rings solid and the steel isn't rusting, a polymer-modified patch and a penetrating sealer hold; if rust is bleeding through, the chloride has reached the bar and the slab is replaced with a low water-cement mix and 2 inches of cover.",
        [("/coastal/salt-and-concrete/", "Salt and concrete", "Why bayfront slabs spall."), ("/concrete/resurfacing/", "Resurfacing", "When a deck gets a new surface instead.")]))
    P.append(page("sarasota", "pavers-sealing", "Paver Sealing in Sarasota, FL – Bayfront Cycle & Cost", "Paver cleaning, re-sanding and sealing inside the City of Sarasota: $1 to $3 per sq ft planning band, the 18-to-24-month cycle on Bird Key, Lido and the bayfront, inland 2 to 3 years, and a worked example.",
        "Paver sealing and cleaning in the City of Sarasota", "Bayfront decks on an 18-month cycle, west-of-Trail driveways on three years, and no wet-look sealer near a pool.",
        "What does paver sealing cost in the City of Sarasota?", "Cleaning alone about $0.40 to $0.60 per square foot; cleaning, polymeric re-sanding and sealing together $1 to $3 per square foot with a $150 to $250 minimum, so a 600-square-foot Bird Key deck runs roughly $600 to $1,800 for the full service and needs it every 18 to 24 months; a Cherokee Park driveway every 2 to 3 years.",
        p("Distance from the bay sets the cycle: Bird Key, Lido, St. Armands, Harbor Acres and the Bayou Oaks waterfront are within half a mile of salt water and get spray on every windy day; Arlington Park, Alta Vista and the Trail corridor are inland. Travertine coping on the bayfront's salt pools is sealed annually. Downtown courtyard pavers under oaks fight mildew more than salt and get a soft-brush clean, not a turbo nozzle.") + p("The city's older paver driveways in clay brick are sealed with a penetrating product only; film sealers change their color."),
        p(f'No permit for cleaning and sealing; condo boards on Lido and St. Armands schedule common-area sealing in summer; turtle lighting isn\'t affected by sealing but the May inspection is the time to check fixtures ({link("/coastal/maintenance-calendar/", "calendar")}).'),
        p("A 1985 Harbor Acres home with 1,100 square feet of concrete-paver driveway and pool deck, last sealed in 2022 with a wet-look product that had blushed white on the shaded side. Scope: strip the failed film, clean at controlled pressure, re-sand to full depth, activate on a dry day, seal with a breathable penetrating product two weeks later, and put October 2027 on the care sheet. Planning range: $2,200 to $3,600 including the strip."),
        "Why does the bayfront deck need sealing more often than the driveway?", "Spray. Salt on the surface and UV break a sealer down faster within half a mile of the water; the driveway at the street side of the same lot can be a year behind the deck. Two dates on one care sheet is normal on the keys.",
        [("/compare/sealer-types-coastal/", "Sealer types", "Why film blushes."), ("/guides/efflorescence/", "Efflorescence", "The other white haze.")]))

    # ---------------------------------------------------------------- SIESTA KEY
    P.append(page("siesta-key", "pavers-pool-decks", "Paver Pool Decks on Siesta Key, FL – Flood Zone & Cost", "Paver pool decks on Siesta Key: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft plus 5 to 15 percent island logistics, AE and VE zones, county permits, turtle lighting, post-2024 base rules and a worked example.",
        "Paver pool decks on Siesta Key", "Travertine, shellstone, porcelain and concrete pavers on a base built to be flushed and reset after the next surge.",
        "What does a paver pool deck cost on Siesta Key?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, plus 5 to 15 percent for island logistics (bridge timing, staging on small lots, concrete curbs at exposed edges), so a 700-square-foot deck lands near $10,000 to $12,500 in pavers or $15,000 to $20,500 in stone before demolition, coping and drains.",
        p("Every Siesta deck is in AE or VE, most within a few hundred yards of salt water, and most stood in surge in 2024. The base is built for that: geotextile, 4 inches compacted in lifts, a concrete curb on every edge the water can reach, and a field that can be lifted, flushed and reset. Salt pools are common; travertine coping is sealed annually or the owner picks porcelain or dense pavers. Lighting is amber and shielded from the first fixture.") + p("Canal streets (Sabal Drive, Palm Island, Bayou Louise) get bay water at the seawall; the Gulf side (Beach Road, Midnight Pass north) gets spray and the setback line."),
        p(f'Sarasota County permits ({link("/permits/sarasota-county/", "rules")}); the deck is a site improvement outside the NFIP 50 percent count but documented ({link("/permits/flood-zones-50-percent-rule/", "flood page")}); Gulf-front decks seaward of the Gulf Beach Setback Line need a variance; {link("/permits/sea-turtle-lighting/", "turtle lighting")} May 1 to October 31; condo boards for common decks.'),
        p("A 1978 canal home off Midnight Pass Road with a 680-square-foot concrete deck that cracked and dropped at the seawall side after the October 2024 surge undermined it. Scope: demolition, base rebuilt in lifts over geotextile with the void at the seawall filled and compacted, linear drain, shellstone bullnose coping, shellstone field, concrete curb at the seawall and cage line, amber recessed lights, polymeric sand on a dry day, sealing at 30 days with annual coping sealing. County permit; deck invoiced as site work. Budget band: $17,500 to $23,000."),
        "Should a Siesta Key deck be pavers or concrete after 2024?", "Pavers on a rebuildable base, in nearly every case. A poured deck that sat in surge with voids under it is replaced; a paver field is lifted, the base fixed and the same pavers reset. That's the difference between a claim and a weekend.",
        [("/coastal/post-storm-restoration/", "Post-storm restoration", "The sequence after surge."), ("/hoa/barrier-island-condos/", "Condo decks", "Board, reserves, phasing.")]))
    P.append(page("siesta-key", "concrete-pool-decks", "Concrete Pool Decks on Siesta Key, FL – When Concrete Still Fits", "Concrete pool decks and resurfacing on Siesta Key: $9 to $14 per sq ft plus island logistics, when a poured deck makes sense in AE and VE zones, county permits, salt mix rules and a worked example.",
        "Concrete pool decks on Siesta Key", "Poured decks where an engineer specifies them, resurfaced decks where the slab survived, and pavers where the water comes up.",
        "What does a concrete pool deck cost on Siesta Key?", "About $9 to $14 per square foot for a new textured deck plus 5 to 15 percent for island logistics, so a 600-square-foot deck runs roughly $5,700 to $9,700 before demolition and drains; a basic overlay on a slab that passed the six tests is $4 to $8 per square foot. On the island the question before price is whether concrete is the right deck at all.",
        p("Concrete pool decks on Siesta Key make sense in three cases: an engineered slab under an elevated home in a VE zone, where the engineer designs it; a lanai on the interior of the island in AE where the slab drains and the owner wants a single surface; and a sound existing deck that passed sounding after 2024 and gets a light overlay. Where surge reaches, pavers win. Every pour here uses a low water-cement mix, 2 inches of cover over steel, a 7-day cure and a penetrating sealer.") + p("Old cool-deck overlays from the 1990s are at end of life across the island; most fail sounding after two surges."),
        p(f'County permit ({link("/permits/sarasota-county/", "rules")}); deck is site work outside the 50 percent count; VE-zone slabs under elevated homes are engineered; setback variance for Gulf-front decks seaward of the line; {link("/permits/sea-turtle-lighting/", "turtle lighting")}.'),
        p("A 2019 elevated home on the interior of the key with an engineered 4-inch slab under the house and a 400-square-foot lanai deck that ponded against the cage. Scope: the slab stayed (engineer's design, sound), a linear drain was cut in at the cage low side, the deck was ground, bond-coated and given a light knockdown overlay with a matte grit sealer, cage anchors reset. County reviewed it as flatwork. Cost band: $3,200 to $5,000."),
        "Can a Siesta Key deck that stood in surge be resurfaced?", "Only after sounding shows no voids and a level shows it didn't drop; then a fresh-water rinse, a dry month, and an overlay. If it sounds hollow anywhere, the base under it moved and the overlay would follow.",
        [("/compare/resurface-vs-replace-pool-deck/", "Resurface or replace", "Six tests."), ("/permits/flood-zones-50-percent-rule/", "Flood zones", "AE, VE and the setback line.")]))
    P.append(page("siesta-key", "pavers-sealing", "Paver Sealing on Siesta Key, FL – 18-Month Cycle & Salt", "Paver cleaning, re-sanding and sealing on Siesta Key: $1 to $3 per sq ft, an 18-month cycle on the Gulf side, annual travertine coping sealing on salt pools, salt flush after surge, and a worked example.",
        "Paver sealing and cleaning on Siesta Key", "Eighteen months on the Gulf side, two years on the canals, every year on a salt pool's coping, and a fresh-water flush after any storm.",
        "What does paver sealing cost on Siesta Key and how often?", "About $1 to $3 per square foot for cleaning, polymeric re-sanding and sealing with a $150 to $250 minimum, every 18 to 24 months island-wide and closer to 18 on the Gulf-front rows; travertine or shellstone coping on a salt pool annually. A 700-square-foot deck runs roughly $700 to $2,100 per cycle.",
        p("Nothing on the key is more than a few hundred yards from salt water, so the sealer lives a short life: spray on the Gulf side, bay water on the canals, salt pools in between, and UV on all of it. Penetrating sealers only; film sealers blush white over bases that never fully dry here. After a surge the sequence is flush, dry, re-sand, then seal, and the sealing waits weeks. Siesta condos schedule common-deck sealing for June to September when the buildings are quiet.") + p("Coquina and shell in the older decks cleans with a soft brush and a neutral product; a turbo nozzle erodes it."),
        p(f'No permit; condo boards for common areas; the May inspection for turtle fixtures and edge restraint goes on the same visit ({link("/coastal/maintenance-calendar/", "calendar")}).'),
        p("A 1980s Gulf-front condo with a 2,400-square-foot travertine common deck, salt pool, last sealed before Helene. Scope: fresh-water flush of the field and base six weeks after Milton, dry month, joints cleaned and re-sanded, coping cleaned with a neutral product, penetrating sealer on the field and coping, board file updated with a May 2028 date for the field and an annual date for the coping. Planning band: $4,000 to $6,500."),
        "Why not seal right after the storm cleanup?", "Because the base holds salt water for weeks and a sealer applied over it traps moisture and blushes. Flush, wait for a dry stretch, then seal. Skipping the wait is how condo decks end up stripped and resealed twice.",
        [("/coastal/post-storm-restoration/", "Post-storm restoration", "Flush before seal."), ("/compare/sealer-types-coastal/", "Sealer types", "Penetrating vs film.")]))
    P.append(page("siesta-key", "pavers-repair-storm-restoration", "Paver Repair & Storm Restoration on Siesta Key, FL", "Paver repair and post-surge restoration on Siesta Key: $8 to $15 per sq ft affected area, the 2024 lessons, base flush and rebuild, concrete curbs at seawalls, insurer documentation and a worked example.",
        "Paver repair and storm restoration on Siesta Key", "Lifting, flushing and resetting fields that Helene and Milton moved, on bases rebuilt to be moved again.",
        "What does it cost to reset surge-shifted pavers on Siesta Key?", "About $8 to $15 per square foot of the affected area plus base material, less per foot for larger areas, so a 300-square-foot seawall-side section runs roughly $2,400 to $4,500 plus a concrete curb at $12 to $20 per linear foot. Full-deck restoration after a surge is scoped after a void survey.",
        p("The 2024 pattern on Siesta Key: edge restraint lifted along seawalls and the Gulf side, joint sand gone, bases salted and undermined at the water edge, pavers scattered but intact. The repair is the base: lift the field where it's low, sound and rebuild the voids in lifts, flush with fresh water, set a concrete curb where the plastic restraint was, reset the original pavers to the survey line, polymeric sand on a dry day, seal weeks later. Photographs first, for the insurer and the Town or county file.") + p("Non-storm calls are sinking around pool equipment where a condensate line saturated the base, and ant-tunneled joints on unsealed decks."),
        p(f'Resets that don\'t change the footprint are generally not permitted work; the county tracks storm repairs against the substantial-damage file even though site work is excluded ({link("/permits/flood-zones-50-percent-rule/", "flood page")}); document before touching anything ({link("/guides/hurricane-insurance-documentation/", "insurance guide")}).'),
        p("A 1969 canal home on Sabal Drive whose 900-square-foot paver deck floated its spiked restraint at the seawall in the Milton surge and settled 2 inches across a 200-square-foot section. After the insurer's photos and three weeks of drying: 260 square feet lifted, two voids at the seawall dug out and rebuilt in three lifts, base flushed, concrete curb poured along 38 feet of seawall edge, pavers rinsed and reset, polymeric sand on a two-day dry forecast, sealing scheduled for six weeks out. Planning range: $4,200 to $6,800."),
        "Do the pavers themselves need replacing after salt water?", "No. Concrete and stone pavers aren't harmed by immersion; they're rinsed and reused. What's replaced is the joint sand, the plastic edge restraint (with concrete) and any base that washed out.",
        [("/coastal/storm-season-playbook/", "Storm playbook", "Before June 1."), ("/coastal/post-storm-restoration/", "Post-storm sequence", "Document, drain, diagnose, rebuild.")]))

    # ---------------------------------------------------------------- LONGBOAT KEY
    P.append(page("longboat-key", "pavers-pool-decks", "Paver Pool Decks on Longboat Key, FL – Town Permits & Salt", "Paver pool decks on Longboat Key: pavers $13 to $16, travertine $20 to $26, marble and porcelain higher, plus island logistics; Town permits, substantial-improvement file, Ordinance 2021-01 lighting, the 6.68-foot surge and a worked example.",
        "Paver pool decks on Longboat Key", "Travertine, marble and porcelain decks for Bay Isles, Country Club Shores and the Gulf-front estates, permitted by the Town and built to be flushed.",
        "What does a marble or porcelain paver pool deck cost on Longboat Key?", "Honed marble about $24 to $34 per square foot and 2 cm porcelain $22 to $32, travertine $20 to $26 and concrete pavers $13 to $16, plus 5 to 15 percent for island logistics, so a 900-square-foot estate deck lands near $23,000 to $35,000 in marble or $12,500 to $16,500 in concrete pavers not counting demolition, coping or drains.",
        p("Longboat decks are large, high-end and exposed: Bay Isles and the Longboat Key Club want marble or porcelain floors that continue the interior, Country Club Shores and Sleepy Lagoon canal homes want travertine that survives the seawall, Gulf of Mexico Drive condos want phased common decks. All of it stood in salt water in September and October 2024. The base is built for the next time: geotextile, lifts, concrete curbs, a field that resets. Porcelain in a mortar bed over an engineered slab is the answer under elevated rebuilds.") + p("Every fixture is amber and fully shielded from the first sketch; Code Enforcement surveys from the beach."),
        p(f'Town of Longboat Key permit for both county halves, Planning & Zoning review of at-grade decks, substantial-improvement check on the file ({link("/permits/longboat-key/", "Town rules")}); {link("/permits/sea-turtle-lighting/", "Ordinance 2021-01 lighting")}; Bay Isles, Club and condo review first.'),
        p("A 1998 Bay Isles home with a 1,050-square-foot travertine deck that stood in 2 feet of surge, with the seawall-side base washed out and the coping loose. Scope: field lifted and stacked, base rebuilt in lifts and flushed, new travertine bullnose coping mortar-set, porcelain field in a large format on a re-screeded bed (the owner switched from travertine to skip annual sealing on the salt pool), concrete curb at the seawall and cage, amber wall-cap lights, polymeric sand on a dry day. Town permit; site work documented. Budget band: $27,000 to $36,000."),
        "Does the Town count the deck toward the 50 percent rule?", "The deck is a site improvement, outside the building's substantial-improvement calculation under FEMA's guidance, but the Town documents it in the file for any property under review. Keep the deck on its own invoice and say so on the application.",
        [("/pavers/marble-porcelain/", "Marble and porcelain", "Base tolerance and salt immunity."), ("/areas/longboat-key/", "Longboat Key", "Town rules and surge history.")]))
    P.append(page("longboat-key", "pavers-driveways", "Paver Driveways on Longboat Key, FL – Salt, Surge & Town Review", "Paver driveways on Longboat Key: $14 to $22 per sq ft plus island logistics, Town Planning & Zoning review of at-grade driveways, concrete curbs for surge, 18-month sealing and a worked example.",
        "Paver driveways on Longboat Key", "Sealed paver driveways for Bay Isles, Country Club Shores and Gulf of Mexico Drive, built with concrete curbs and a short sealing cycle.",
        "What does a paver driveway cost on Longboat Key?", "About $14 to $22 per square foot plus 5 to 15 percent for island logistics, so a 700-square-foot estate driveway runs roughly $10,800 to $17,700 before demolition and the concrete curb at the street. Sealing every 18 to 24 months is a line on the care sheet, not an option.",
        p("Driveways on the key are wide, short and exposed: circular drives and motor courts in Bay Isles and the Club, straight drives on the canal streets, all within a few hundred feet of the Gulf or the bay. Salt spray shortens sealer life to 18 to 24 months; surge lifts spiked restraint, so every edge is a concrete curb; the Town reviews the driveway as an at-grade exception. Herringbone vehicular pavers in light blends keep the surface cool for barefoot trips to the mailbox in August.") + p("Gulf of Mexico Drive access means staging on the lot, not the road, and delivery timing around the two bridges."),
        p(f'Town permit and Planning & Zoning review of at-grade driveways ({link("/permits/longboat-key/", "rules")}); community review in Bay Isles, the Club and Country Club Shores; substantial-improvement file; amber column lights if visible from the beach.'),
        p("A 1986 Country Club Shores canal home with a 620-square-foot concrete driveway cracked and heaved by the 2024 surge. Scope: demolition, 6 inches of compacted base in three lifts over geotextile, herringbone field in a light coral blend with a charcoal soldier course, poured curb where the field meets the street and along the side-yard edge the water reached, amber column lights on the entry pillars, polymeric sand, sealing at 30 days with April 2028 on the care sheet. Town permit; association approval. Cost band: $11,500 to $15,500."),
        "Why concrete curbs on a driveway that never floods from the street?", "Because on Longboat Key the water doesn't come from the street; it comes from the bay across the yard. A curb set on the base holds the field when the bedding sand is underwater; spiked restraint floats.",
        [("/pavers/sealing/longboat-key/", "Sealing on Longboat Key", "The cycle."), ("/coastal/post-storm-restoration/", "Post-storm restoration", "If it happens again.")]))
    P.append(page("longboat-key", "pavers-sealing", "Paver Sealing on Longboat Key, FL – Cycle & Salt Pools", "Paver cleaning, re-sanding and sealing on Longboat Key: $1 to $3 per sq ft, an 18-to-24-month island cycle, annual travertine coping sealing on salt pools, condo scheduling, salt flush after surge and a worked example.",
        "Paver sealing and cleaning on Longboat Key", "An 18-month cycle for fields, a 12-month cycle for limestone coping on salt pools, and summer scheduling for the condos.",
        "How often should Longboat Key pavers be sealed and what does it cost?", "Every 18 to 24 months for fields island-wide, annually for travertine or shellstone coping on salt-chlorinated pools, at about $1 to $3 per square foot for cleaning, re-sanding and sealing with a $150 to $250 minimum. A 900-square-foot deck runs roughly $900 to $2,700 per cycle; a 2,500-square-foot condo deck $2,500 to $7,500.",
        p("The whole key is within half a mile of salt water, and the Gulf-front rows get spray daily. Penetrating sealers only; film sealers blush over bases that stay damp. Condo associations along Gulf of Mexico Drive schedule sealing for June to September when occupancy is lowest and tie it to the May inspection of edges, drains and turtle fixtures. After the 2024 surge, every sealing job started with a fresh-water flush and a dry month.") + p("Marble on the estate lanais takes a penetrating sealer and a neutral cleaner; porcelain takes nothing."),
        p(f'No permit; condo and club scheduling; turtle-fixture check on the same visit ({link("/permits/sea-turtle-lighting/", "lighting rules")}); {link("/coastal/maintenance-calendar/", "maintenance calendar")}.'),
        p("A Gulf of Mexico Drive condominium with 3,200 square feet of travertine common deck around a salt pool, last sealed 2023, coping flaking at the waterline. Scope: neutral-pH clean with soft brushes, joints re-sanded, coping flakes removed and the worst 22 pieces replaced, penetrating sealer on field and coping, annual coping date and 2028 field date in the board's reserve file. Scheduled for July. Planning band: $5,500 to $9,000 including the coping pieces."),
        "Is annual coping sealing really necessary?", "On a salt pool with travertine or shellstone coping, yes; the alternative is flaking within two seasons and replacement within five. Porcelain or dense concrete coping ends the annual line.",
        [("/pavers/travertine-shellstone/", "Travertine and shellstone", "The chemistry."), ("/hoa/barrier-island-condos/", "Condo decks", "Reserves and phasing.")]))
    P.append(page("longboat-key", "pavers-repair-storm-restoration", "Paver Repair & Storm Restoration on Longboat Key, FL", "Paver repair and post-surge restoration on Longboat Key after the 6.68-foot Helene surge: $8 to $15 per sq ft affected area, base flush and rebuild, concrete curbs, Town file documentation and a worked example.",
        "Paver repair and storm restoration on Longboat Key", "Resetting fields the 2024 surge moved, on bases rebuilt for the next one, documented for the Town and the insurer.",
        "What does storm restoration of pavers cost on Longboat Key?", "About $8 to $15 per square foot of the affected area plus base material and concrete curbs at $12 to $20 per linear foot, so a 400-square-foot seawall-side section runs roughly $3,200 to $6,000 plus the curb. Whole-deck restoration is scoped after a void survey; the pavers are almost always reused.",
        p("Helene measured 6.68 feet on Longboat Key on September 26, 2024, and Milton followed on October 9. Fields along seawalls and the Gulf side lifted their restraint, bases salted and hollowed at the edges, joint sand vanished, and sand and debris buried drains. The restoration is the standard sequence: insurer photos, one to three weeks of drying, lift the low and heaved sections, dig out and rebuild voids in lifts, flush, concrete curb on every exposed edge, reset to the survey line, polymeric sand on a dry day, seal weeks later. The Town wants the site work documented in the file even though it doesn't count toward substantial damage.") + p("Non-storm repairs are canal-side settling where a seawall weep hole washed the base and ant-tunneled joints on unsealed driveways."),
        p(f'Town permit file for storm repairs on properties under substantial-damage review ({link("/permits/longboat-key/", "rules")}); resets without a footprint change are generally not permitted work; document first ({link("/guides/hurricane-insurance-documentation/", "insurance guide")}).'),
        p("A 1972 Sleepy Lagoon canal home whose 800-square-foot travertine deck dropped 3 inches along 40 feet of seawall after Helene and lost its restraint to Milton. After documentation and four weeks of drying: 320 square feet lifted, base voids rebuilt in lifts, fresh-water flush, concrete curb along the seawall and the side edge, travertine rinsed and reset with 18 new pieces, polymeric sand, coping resealed. Town file updated. Planning range: $5,500 to $8,500."),
        "How soon after a surge can the deck be reset?", "When the base has drained and can be compacted, usually one to three weeks, and after the insurer has photographs. Resetting on a saturated base means resetting again in the spring.",
        [("/coastal/post-storm-restoration/", "Post-storm sequence", "Document, drain, diagnose, rebuild."), ("/coastal/storm-season-playbook/", "Storm playbook", "Before June 1.")]))

    # ---------------------------------------------------------------- PALMER RANCH
    P.append(page("palmer-ranch", "concrete-driveways", "Concrete Driveways in Palmer Ranch, FL – ARC & Replacement", "Concrete driveway replacement in Palmer Ranch: $7 to $12 per sq ft planning band, 1990 to 2010 builder driveways at replacement age, sub-association and master ARC review, county right-of-way permit and a worked example.",
        "Concrete driveways in Palmer Ranch", "Replacing 1990s builder driveways on graded fill, with two levels of association review and a county permit for the apron.",
        "What does a concrete driveway cost in Palmer Ranch?", "About $7 to $12 per square foot installed, so a 640-square-foot two-car driveway typical of Turtle Rock or Deer Creek runs roughly $5,000 to $8,000 plus $1,300 to $2,600 for demolition and $300 to $800 for the apron under a county right-of-way use permit. Sub-association and master approvals add weeks, not dollars.",
        p("Palmer Ranch driveways were poured fast on graded fill between 1990 and 2010, most at 4 inches with little base and joints at 15 feet. They've settled at the garage, cracked across the long panels and stained orange where well-water sprinklers cross them. Replacement means compacting the backfill strip at the garage, 4 inches of base, a 4,000 PSI fiber slab with #3 bar, control joints every 8 feet, and sprinkler heads moved. Broom finish in the color the sub-association allows; most reject dark integral color on driveways.") + p("Prestancia and Stoneybrook lots on the lake edges are AE; the rest are X."),
        p(f'Sub-association ARC first, master association second ({link("/hoa/palmer-ranch/", "Palmer Ranch guide")}); Sarasota County right-of-way use permit for the apron and flatwork review ({link("/permits/sarasota-county/", "county rules")}); 50 percent impervious cap on the lot.'),
        p("A 1994 Deer Creek home with a 600-square-foot driveway settled an inch at the garage and cracked in three panels, rust-striped by the irrigation. Scope: demolition, backfill strip at the garage excavated and compacted, 4 inches of base, a 4-inch slab of fiber-reinforced 4,000 PSI concrete on #3 rebar dowelled to the new apron, joints sawn at 8 feet, heads relocated, penetrating sealer at 28 days. Sub-association approval two weeks, master three; county ROW permit. Budget band: $6,800 to $9,800."),
        "Can the driveway be widened for a third car in Palmer Ranch?", "Only where the sub-association's guideline allows it, usually not past the garage's side wall line, and only if the lot stays under the county's 50 percent impervious cap. The site plan in the ARC packet shows both.",
        [("/compare/concrete-vs-pavers-driveway/", "Concrete vs pavers", "The other Palmer Ranch answer."), ("/guides/well-water-rust-stains/", "Rust stains", "The irrigation problem.")]))
    P.append(page("palmer-ranch", "pavers-driveways", "Paver Driveways in Palmer Ranch, FL – ARC Colors & Cost", "Paver driveways in Palmer Ranch: $14 to $22 per sq ft planning band, approved color lists and borders, two-level ARC review, 6-inch base on graded fill, county apron permit and a worked example.",
        "Paver driveways in Palmer Ranch", "Herringbone driveways in the colors the sub-associations approve, on a base deeper than the builder ever put down.",
        "What does a paver driveway cost in Palmer Ranch?", "About $14 to $22 per square foot installed, so a 640-square-foot two-car driveway runs roughly $9,000 to $14,000 plus $1,300 to $2,600 for demolition of the builder slab and the apron under a county right-of-way permit. The color list and the border are the ARC conversation; the base is the contractor's.",
        p("Pavers are the most common Palmer Ranch driveway application because they read as the upgrade the community's newer villages (Esplanade, Sandhill Preserve, Isles of Sarasota) came with. Sub-associations keep approved blends; tan and gray fields with a charcoal or brown soldier course pass, dark fields and busy patterns don't. Under the pavers: a 6-inch base compacted in lifts on graded fill, herringbone field, a concrete edge at the street line, sprinkler heads moved off the surface.") + p("Palmer Ranch lots are on well water in many villages; a sealed field keeps the iron on the surface."),
        p(f'Sub-association ARC, then master ({link("/hoa/palmer-ranch/", "guide")}); county right-of-way use permit for the apron ({link("/permits/sarasota-county/", "rules")}); impervious cap unchanged by the material unless permeable pavers are used.'),
        p("A 1996 Turtle Rock home with a 640-square-foot builder driveway cracked at the garage. Scope: demolition, a 6-inch base placed in three lifts over geotextile and compacted, herringbone field in an approved tan blend with a charcoal soldier course, curb in concrete along the street edge, irrigation heads redirected, polymeric joint sand and a sealer 30 days later. Sub-association and master approvals four weeks; county ROW permit for the apron. Cost band: $10,000 to $14,000."),
        "Do both associations really have to approve a driveway color?", "In most Palmer Ranch villages, yes: the sub-association's committee reviews against its list and the master's form asks for that approval letter. Submit both at once with the same sample chip.",
        [("/pavers/sealing/", "Sealing", "The inland cycle."), ("/hoa/palmer-ranch/", "Palmer Ranch ARC guide", "The packet and the sequence.")]))
    P.append(page("palmer-ranch", "concrete-pool-decks", "Concrete Pool Decks in Palmer Ranch, FL – Replace the 1990s Deck", "Concrete pool decks in Palmer Ranch: $9 to $14 per sq ft new, $4 to $15 overlay, why 1990s cool-deck overlays are failing, county review, ARC review of color and a worked example.",
        "Concrete pool decks in Palmer Ranch", "Replacing or resurfacing the 1990s cool-deck decks under Palmer Ranch cages, with the six tests deciding which.",
        "What does a concrete pool deck cost in Palmer Ranch?", "About $9 to $14 per square foot for a new textured deck, so a 650-square-foot deck under a Stoneybrook or Prestancia cage runs roughly $6,000 to $9,000 not counting tear-out or drains; a basic overlay on a slab that passed sounding is $4 to $8 per square foot. Most 1990s cool-deck overlays here have reached the end of their 8-to-15-year life twice over.",
        p("Palmer Ranch pool decks were poured with the houses between 1990 and 2010 and finished with cool-deck overlays that are now chalking, cracking and lifting in sheets. The slabs underneath are often sound because the developer's fill compacts better than native sand, so resurfacing is a real option here more often than on the keys: sound it, check the slope, and overlay in a light knockdown with a matte grit sealer. Where the slab dropped toward the house or ponds under the cage, it comes out and a new deck goes in with drains.") + p("Sub-associations review the color; a light sand tone passes everywhere."),
        p(f'Sarasota County reviews replacement as flatwork; overlays on the same footprint usually fall below thresholds ({link("/permits/sarasota-county/", "rules")}); sub-association ARC for material and color ({link("/hoa/palmer-ranch/", "guide")}).'),
        p("A 1999 Stoneybrook home with a 700-square-foot deck whose 2008 cool-deck overlay was peeling. Sounding: solid; slope: to the drain; threshold: fine. Scope: strip the old overlay, repair two hairline cracks, bond coat, light knockdown overlay, matte sealer with grit, cage anchors checked. Two dry days between coats. No county permit needed; sub-association approved the color in one meeting. Planning band: $4,500 to $6,500."),
        "Why do Palmer Ranch decks pass the overlay tests more often than island decks?", "Better ground and no surge. Graded fill compacted during development holds a slab flat for decades; a barrier-island base that stood in surge doesn't. The tests are the same; the answers differ.",
        [("/compare/resurface-vs-replace-pool-deck/", "Resurface or replace", "The six tests."), ("/concrete/resurfacing/", "Resurfacing", "Finishes and process.")]))
    P.append(page("palmer-ranch", "pavers-pool-decks", "Paver Pool Decks in Palmer Ranch, FL – Travertine Under the Cage", "Paver pool decks in Palmer Ranch: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, overlays on sound builder slabs, deck drains under cages, ARC color review and a worked example.",
        "Paver pool decks in Palmer Ranch", "Travertine and light pavers over sound builder slabs or on new bases, under cages that trap water unless a drain is cut in.",
        "What does a paver pool deck cost in Palmer Ranch?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 650-square-foot deck runs roughly $8,500 to $10,500 in pavers or $13,000 to $17,000 in stone before demolition, coping and a drain. An overlay on a sound builder slab sits at the low end because there's no excavation.",
        p("The typical Palmer Ranch request is travertine over the 1990s deck the house came with: the slab passes sounding, the pavers go on a thin sand bed or thin-set with a perimeter curb, and the finished floor stays under the slider threshold. Where the deck ponds under the cage, a linear drain is cut in first. Chlorine pools dominate here, so travertine's annual salt-coping rule rarely applies; sealing runs 2 to 3 years inland. Sub-associations review the material and color; travertine and light blends pass.") + p("Cage anchors go into a new concrete curb along the cage line, never into paver joints."),
        p(f'County flatwork review for a new deck; overlays on the same footprint usually below thresholds ({link("/permits/sarasota-county/", "rules")}); sub-association ARC ({link("/hoa/palmer-ranch/", "guide")}).'),
        p("A 2001 Prestancia home with a 720-square-foot broom deck under a cage, sound but ponding at the far corner. Scope: linear drain cut into the low side and tied to the yard drain, travertine bullnose coping on the beam, tumbled travertine field sand-set over the slab with a perimeter curb, cage anchors reset into the curb, polymeric sand now and sealing after 30 days. Sub-association approval three weeks; no county permit for the overlay. Planning range: $15,000 to $19,500."),
        "Will travertine over the old deck raise the floor above the door?", "By about 2 inches (bedding plus stone); if the slab-to-threshold gap is under 3 inches, the answer is thin-set porcelain or a tear-out. The estimate measures it before anything is ordered.",
        [("/pavers/patios-lanais/", "Paver patios and lanais", "The five overlay tests."), ("/pavers/travertine-shellstone/", "Travertine", "Finishes.")]))

    # ---------------------------------------------------------------- GULF GATE
    P.append(page("gulf-gate", "concrete-driveways", "Concrete Driveways in Gulf Gate, FL – Replacing 1960s Slabs", "Concrete driveway replacement in Gulf Gate Estates: $7 to $12 per sq ft planning band, why 3.5-inch 1960s slabs on sand are failing, county right-of-way permit, no master HOA, and a worked example.",
        "Concrete driveways in Gulf Gate", "Sixty-year-old slabs on uncompacted sand, replaced on a real base with the county's apron permit and nobody's ARC.",
        "What does a concrete driveway cost in Gulf Gate?", "About $7 to $12 per square foot installed, so a 440-square-foot single-car-plus driveway typical of the 1960s lots runs roughly $3,300 to $5,300 plus $900 to $1,800 for demolition and $300 to $800 for the apron under a county right-of-way use permit. No association fee, no color list, no packet.",
        p("Gulf Gate's driveways are the original 1962 to 1972 pours: 3 to 3.5 inches on raw Myakka sand, no joints, no base, cracked into pieces and dropped at the garage where the backfill was never compacted. Overlays some owners added in the 1990s are delaminating. The replacement is the same everywhere in the neighborhood: demolition, compact the garage strip, 4 to 6 inches of base where the water table sits high (the blocks toward Phillippi Creek), a 4-inch fiber 4,000 PSI slab on #3 rebar, an 8-foot joint spacing, apron to the county detail.") + p("Lots are 80 by 110; widening to 16 feet for two cars is usually possible inside the setback."),
        p(f'Sarasota County right-of-way use permit for the apron and flatwork review for the slab ({link("/permits/sarasota-county/", "county rules")}); a strip along US-41 and Gulf Gate Drive is city, not county; no master association in Gulf Gate Estates.'),
        p("A 1966 home on a Gulf Gate Estates cul-de-sac with a 12-by-38-foot driveway in seven pieces and a 3/4-inch drop at the garage. Scope: demolition, garage backfill strip excavated 18 inches and compacted, 4 inches of base, 4,000 PSI fiber-reinforced concrete at 4 inches with #3 rebar on chairs, widened to 16 feet, joints cut on an 8-foot grid, apron under the county ROW permit. Four working days plus cure. Budget band: $5,500 to $7,800."),
        "Is it worth widening a Gulf Gate driveway while replacing it?", "Almost always; the mobilization is paid for and the extra 4 feet adds a few hundred dollars. Check the setback on the survey and the county's apron width for the curb cut.",
        [("/concrete/repair/gulf-gate/", "Repair in Gulf Gate", "When a panel, not the driveway, is the problem."), ("/guides/why-concrete-cracks-sarasota/", "Why concrete cracks here", "The 1960s slab explained.")]))
    P.append(page("gulf-gate", "concrete-repair", "Concrete Repair in Gulf Gate, FL – Lifting, Cracks, Trip Hazards", "Concrete repair in Gulf Gate Estates: crack sealing, polyurethane lifting, trip-hazard grinding and panel replacement with planning bands, and the honest line where a 1960s slab is past repairing.",
        "Concrete repair in Gulf Gate", "Lifting, sealing and replacing panels on 1960s slabs, and saying plainly when the slab is done.",
        "What does concrete repair cost in Gulf Gate?", "Crack sealing about $8 to $20 per linear foot, polyurethane lifting $500 to $2,500 per settled area, trip-hazard grinding $150 to $400 per joint, panel replacement $400 to $900 per panel. On a 3.5-inch 1960s driveway broken into many pieces, the repair estimate says replacement, because lifting a slab that has no base is a one-season fix.",
        p("Gulf Gate repair calls are the same three things: a front walk panel heaved by a 1960s oak root, a driveway panel dropped at the garage, and a lanai slab that settled toward the sliders. Lifting works where the slab is intact and the water that moved the sand has been stopped (a downspout, a leaking sprinkler line, a pool overflow); grinding handles trip hazards under half an inch; panels get replaced with dowels. Slabs cracked in many pieces are replaced, and the estimate says so instead of selling a patch.") + p("Interior blocks are dry; the Phillippi Creek and Little Sarasota Bay edges have a high water table that makes settlement common."),
        p(f'Repairs without a footprint change are generally below county permit thresholds ({link("/permits/sarasota-county/", "rules")}); public sidewalks in the county right-of-way are the county\'s to repair; oak roots on protected trees need a permit to cut.'),
        p("A 1969 home near Gulf Gate Drive with a lanai slab dropped 3/4 of an inch toward the house after a pool autofill line leaked under it. Scope: line repaired, slab lifted with polyurethane foam through six holes to restore the slope away from the sliders, holes patched, isolation joint at the house resealed. Same-day use. Cost band: $1,200 to $2,000."),
        "Can a 1960s Gulf Gate driveway be lifted instead of replaced?", "If it's in one or two pieces and the drop is the only problem, yes. If it's in seven pieces with no base, lifting is money spent twice; replacement on a compacted base is the repair.",
        [("/concrete/driveways/gulf-gate/", "Driveways in Gulf Gate", "The replacement."), ("/concrete/resurfacing/", "Resurfacing", "Pool decks with sound slabs.")]))
    P.append(page("gulf-gate", "concrete-pool-decks", "Concrete Pool Decks in Gulf Gate, FL – 1970s Decks, Sounded First", "Concrete pool decks in Gulf Gate Estates: $9 to $14 per sq ft new, $4 to $15 overlay, why 1970s decks with 1990s cool-deck fail sounding at the coping, county review and the 780-square-foot worked example.",
        "Concrete pool decks in Gulf Gate", "Original 1970s decks with 1990s overlays, sounded at the coping before anyone quotes another overlay.",
        "What does a concrete pool deck cost in Gulf Gate?", "About $9 to $14 per square foot for a new textured deck, so a 700-square-foot deck runs roughly $6,300 to $9,800 with demolition and drains extra; an overlay on a slab that passed sounding is $4 to $8 per square foot. Most Gulf Gate decks fail the sounding at the coping, where the original slab was poured tight to the shell with no isolation joint.",
        p("Gulf Gate pools were dug in the 1970s with decks poured tight to the shell and finished with cool-deck overlays in the 1990s. Two things fail: the deck cracks along the coping because there's no isolation joint, and the overlay delaminates over the hollows. The hammer decides. Decks that ring solid get a new overlay in a light knockdown; decks that don't come out and get 4 inches of base, a proper isolation joint, drains, and a textured 4,000 PSI slab. Blocks near Little Sarasota Bay get the low water-cement mix for the bay's spray.") + p("Cages here are original aluminum; anchors are reset into new concrete at the cage line."),
        p(f'County flatwork review for replacement; overlays on the footprint usually below thresholds ({link("/permits/sarasota-county/", "rules")}); AE on the bay and creek edges, X inland; no master association.'),
        p("A 1972 home two blocks from Little Sarasota Bay with a 780-square-foot deck on Myakka fine sand, spalled at the coping and hollow across a third of the field. Scope: demolition, 4 inches of crushed base compacted in two lifts, isolation joint at the shell with a flexible sealant, two deck drains, a 4-inch fiber-reinforced 4,000 PSI deck with #3 rebar along the cage, knockdown texture in a light sand tone, cage re-anchored. Eight working days. Planning band: $7,500 to $11,000."),
        "Why does the deck crack right along the pool?", "Because it was poured tight to the shell in 1972 with no isolation joint; the pool and the deck move differently and the deck loses. The new deck gets a compressible joint and a flexible sealant at the coping.",
        [("/compare/resurface-vs-replace-pool-deck/", "Resurface or replace", "Six tests."), ("/pavers/pool-decks/", "Paver pool decks", "The other Gulf Gate answer.")]))
    P.append(page("gulf-gate", "pavers-driveways", "Paver Driveways in Gulf Gate, FL – No HOA, County Apron Permit", "Paver driveways in Gulf Gate Estates: $14 to $22 per sq ft planning band, herringbone on a 6-inch base over Myakka sand, county right-of-way permit for the apron, no association review, and a worked example.",
        "Paver driveways in Gulf Gate", "Herringbone driveways on a real base, in any color you like, because Gulf Gate has no master association.",
        "What does a paver driveway cost in Gulf Gate?", "About $14 to $22 per square foot installed, so a 480-square-foot driveway runs roughly $6,700 to $10,500 plus $1,000 to $1,900 for demolition of the 1960s slab and the apron under a county right-of-way use permit. No ARC, so the color and border are yours.",
        p("Gulf Gate is one of the few neighborhoods in the county where a paver driveway is a design decision rather than a committee one. The ground still rules: Myakka fine sand with a shallow water table toward the creek and the bay, so 6 inches of base in three lifts over geotextile, herringbone for the tires, a concrete curb at the street where delivery trucks turn, and sprinkler heads moved off the field. Clay brick suits the mid-century ranches; light concrete blends stay cooler for a barefoot walk to the car.") + p("Widening to 16 feet is common on the 80-foot lots."),
        p(f'County right-of-way use permit for the apron ({link("/permits/sarasota-county/", "rules")}); city strip along US-41 and Gulf Gate Drive permits through the City of Sarasota; no association review.'),
        p("A 1968 Gulf Gate Estates home with a 10-by-40-foot slab in pieces. Scope: demolition, widened to 16 feet, six inches of crushed base placed and compacted in lifts over geotextile, 45-degree herringbone in a light gray blend with a charcoal border, poured curb where the field meets the street, apron in pavers under the county ROW permit, irrigation sleeved, joints filled with polymeric sand, sealer applied at day 30. Planning range: $9,500 to $13,000."),
        "Does the county allow a paver apron in Gulf Gate?", "Yes, under the right-of-way use permit, to the road; the county's review sets the crossing detail. The city strip along the Trail follows the city's apron rule instead.",
        [("/concrete/driveways/gulf-gate/", "Concrete driveways in Gulf Gate", "The poured alternative."), ("/compare/concrete-vs-pavers-driveway/", "Concrete vs pavers", "Twenty-year cost.")]))

    # ---------------------------------------------------------------- FRUITVILLE & BEE RIDGE
    P.append(page("fruitville-bee-ridge", "concrete-driveways", "Concrete Driveways in Fruitville & Bee Ridge, FL – County Rules", "Concrete driveway replacement in Fruitville, Bee Ridge, The Meadows and Kensington Park: $7 to $12 per sq ft, flatwoods sands with a shallow water table, county right-of-way permit, well-water rust and a worked example.",
        "Concrete driveways in Fruitville and Bee Ridge", "Replacing 1960s to 1990s driveways on flatwoods sand that holds water, with a county permit and, in The Meadows, two associations.",
        "What does a concrete driveway cost in Fruitville or Bee Ridge?", "About $7 to $12 per square foot installed, so a 560-square-foot two-car driveway runs roughly $4,000 to $6,700 plus $1,100 to $2,200 for demolition and $300 to $800 for the apron under a county right-of-way use permit. Lots with a swale at the road add a culvert line the county sizes.",
        p("East of the city the ground is Myakka, EauGallie and Immokalee sand over a hardpan, with a wet-season water table under 10 inches: driveways poured on it without a base settle and crack at the garage. Kensington Park and Sarasota Springs slabs are 1950s and 60s; The Meadows and Bee Ridge 1970s and 80s; the Fruitville corridor's newer subdivisions have builder slabs from the 2000s. All get 4 to 6 inches of compacted base, a 4,000 PSI fiber-reinforced slab with #3 steel, joints at 8 feet, and sprinkler heads moved because most of the area irrigates from wells.") + p("Larger Bee Ridge lots often add a boat or RV pad at 6 inches with the driveway."),
        p(f'Sarasota County right-of-way use permit for the apron or culvert, flatwork review for the slab ({link("/permits/sarasota-county/", "rules")}); The Meadows Community Association and its sub-associations review driveway changes; the Fruitville corridor subdivisions have ARCs.'),
        p("A 1984 Bee Ridge home on a half-acre lot with a 620-square-foot driveway cracked across three long panels and a swale crossing with a crushed culvert. Scope: demolition, new culvert to the county's size under the ROW permit, swale regraded, 6 inches of base (water table within a foot in August), four inches of 4,000 PSI concrete, fiber plus #3 rebar, control joints every 8 feet, a 12-by-30-foot boat pad at 6 inches with #4 bar beside it, heads moved. Budget band: $9,500 to $13,500 including the culvert and the pad."),
        "Why 6 inches of base here when 4 is standard?", "Because on the Bee Ridge and Fruitville flatwoods the water table sits within a foot of the surface for months; the extra base keeps the slab off saturated sand that pumps fines. Inland fill in Palmer Ranch doesn't need it; native flatwoods does.",
        [("/concrete/slabs/fruitville-bee-ridge/", "Slabs and pads here", "Boat, RV and shed pads."), ("/guides/well-water-rust-stains/", "Rust stains", "Well irrigation.")]))
    P.append(page("fruitville-bee-ridge", "concrete-slabs", "Concrete Slabs & Pads in Fruitville & Bee Ridge, FL", "Shed, boat, RV, generator and AC pads on the larger lots of Fruitville and Bee Ridge: thickness by load, 6-inch base on flatwoods sand, the 100-square-foot shed exemption, county review and a worked example.",
        "Concrete slabs and pads in Fruitville and Bee Ridge", "Boat, RV, shed and generator pads on half-acre lots where the water table decides the base.",
        "What does a pad cost in Fruitville or Bee Ridge?", "Small pads about $9 to $15 per square foot and larger slabs $8 to $12, so an AC pad runs $350 to $700, a 10-by-12 shed pad $1,200 to $2,000, a 12-by-30 boat pad at 6 inches with #4 bar $3,200 to $4,800, and a 14-by-45 RV pad $5,500 to $8,000. Pads sit 2 to 4 inches above grade so August rain doesn't stand against the equipment.",
        p("The half-acre and acre lots along Bee Ridge, Fruitville and Lorraine roads are where the county's boat trailers, RVs, workshops and generators live, and where the ground is worst for them: flatwoods sand with a shallow water table and a hardpan that keeps it wet. Every pad here gets a compacted subgrade, 6 inches of base for anything a vehicle sits on, a raised edge, and a slope to the swale. Generator pads are poured to the manufacturer's template; shed pads under 100 square feet follow the county's shed exemption.") + p("Zoning on the larger lots allows accessory structures the small lots don't; the county checks setbacks and the 50 percent impervious cap."),
        p(f'Detached sheds of 100 square feet or less generally exempt; larger pads and any structure on them reviewed through Accela; generator and AC pads usually ride with the equipment permit ({link("/permits/sarasota-county/", "county rules")}); ARC review in the newer Fruitville subdivisions.'),
        p("A 1991 home on an acre off Lorraine Road: a 14-by-40-foot RV pad, a 12-by-16 shed pad and a generator pad. Scope: subgrade proof-rolled (soft pocket found and dug out), 6 inches of base for the RV pad and 4 for the others, RV pad at 6 inches with #4 bar on 18-inch centers and a steel plate at the jack point, shed pad at 4 inches with a thickened edge, generator pad to the template with conduit sleeved, all raised 3 inches above grade and sloped to the swale. County permit for the shed (over 100 square feet) and the generator. Cost band: $9,000 to $13,000 for the three."),
        "Does a boat pad need a permit in unincorporated Sarasota County?", "As a slab with nothing on it, often not, though the county's zoning review checks setbacks and impervious cover; with a cover or a structure on it, yes. Ask Accela before pouring; the answer is free and the after-the-fact permit isn't.",
        [("/concrete/slabs/", "Slabs and pads", "Thickness by load."), ("/compare/4-inch-vs-6-inch/", "4 or 6 inches", "Why pads get 6.")]))
    P.append(page("fruitville-bee-ridge", "pavers-patios-lanais", "Paver Patios & Lanais in Fruitville, Bee Ridge & The Meadows, FL", "Paver patios and lanai floors in Fruitville, Bee Ridge and The Meadows: $13 to $26 per sq ft by material, overlays on 1970s and 80s lanai slabs, drains under cages, master and sub-association review and a worked example.",
        "Paver patios and lanais in Fruitville, Bee Ridge and The Meadows", "Travertine and paver lanai floors over 1970s slabs that pass the tests, and new patios on flatwoods sand that needs a base.",
        "What does a paver patio or lanai floor cost in The Meadows or Bee Ridge?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 350-square-foot lanai floor runs roughly $4,500 to $5,600 in pavers or $7,000 to $9,000 in stone; an overlay on a sound slab sits at the low end. New patios on the flatwoods add 4 inches of base and a drain to the swale.",
        p("The Meadows villas and homes from the 1970s and 80s have lanai slabs that mostly pass the five overlay tests: sound, no offset cracks, sloped away, room under the threshold, water leaving the cage. Travertine or a light paver over them, thin-set or sand-set with a perimeter curb, is the standard upgrade, with a a slot drain sawn into the deck where the cage traps water. New backyard patios on Bee Ridge and Fruitville lots go on a compacted 4-inch crushed-rock base over the wet-season sand, sloped to a swale or a dry well.") + p("The Meadows reviews the change at the sub-association and the master; the Fruitville corridor subdivisions at their ARC."),
        p(f'At-grade patios and overlays on the footprint usually below county thresholds; extensions that add impervious cover are checked against the 50 percent cap ({link("/permits/sarasota-county/", "rules")}); The Meadows Community Association plus sub-association review; Fruitville ARCs.'),
        p("A 1979 villa in The Meadows with a 14-by-24 lanai slab, sound, ponding 2 feet from the cage screen. Scope: linear deck drain installed along the low side and tied to the yard drain, a sand-set field of tumbled travertine over the slab, held by a perimeter curb, bullnose step at the slider, the cage re-anchored into the new curb, polymeric sand, sealing at 30 days. Sub-association and master approvals took a month; no county permit for the overlay. Planning band: $8,000 to $10,500."),
        "Does The Meadows allow travertine on a lanai?", "The material has been approved routinely, but each sub-association keeps its own guideline and the master reviews visible changes; a lanai floor inside a cage is usually the easiest approval in the community. Submit the sample and the drain detail.",
        [("/pavers/patios-lanais/", "Paver patios and lanais", "The five tests."), ("/areas/fruitville-bee-ridge/", "Fruitville and Bee Ridge", "Ground and rules.")]))
    P.append(page("fruitville-bee-ridge", "concrete-repair", "Concrete Repair in Fruitville & Bee Ridge, FL – Settlement & Rust", "Concrete repair in Fruitville, Bee Ridge, Kensington Park and Sarasota Springs: polyurethane lifting on flatwoods sand, crack sealing, panel replacement, well-water rust removal and a worked example.",
        "Concrete repair in Fruitville and Bee Ridge", "Settled driveways and lanais on sand that holds water, lifted after the water is fixed, and rust that comes from the well.",
        "What does concrete repair cost in Fruitville or Bee Ridge?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, panel replacement $400 to $900 per panel, rust removal and resealing $1 to $2 per square foot. On the flatwoods, the repair starts with finding the water that moved the sand.",
        p("East of the city the repair pattern is settlement: a driveway panel at the garage, a lanai corner, a walk beside a downspout, all on Myakka or EauGallie sand that lost fines to water. Lifting with polyurethane foam restores the grade in hours once the downspout, the leaking irrigation line or the blocked swale is fixed. Rust stains from well-water sprinklers are the other regular call; oxalic-acid cleaning on concrete, heads redirected, then a penetrating sealer. Kensington Park and Sarasota Springs slabs from the 1950s and 60s are thin and often past lifting; the estimate says so.") + p("Slabs under the older oaks in Sarasota Springs heave rather than settle; the root stays, the panel is bridged."),
        p(f'Repairs without a footprint change generally below county thresholds ({link("/permits/sarasota-county/", "rules")}); protected trees need a permit to root-prune; The Meadows reviews visible changes.'),
        p("A 1972 Kensington Park home with a two-car driveway settled 1.5 inches at the garage and orange from the well. Scope: gutter downspout that discharged onto the driveway edge redirected to a splash block 6 feet out, driveway lifted with polyurethane foam through eight holes, joints sealed, oxalic cleaning of the rust, heads redirected, penetrating sealer two weeks later. One day. Planning range: $1,900 to $3,000."),
        "Will the driveway settle again after lifting?", "Not if the water that moved the sand is stopped, which is the first item on the scope. Foam fills the void and supports the slab; it doesn't stop a downspout from digging a new one.",
        [("/guides/well-water-rust-stains/", "Rust stains", "Removal and prevention."), ("/guides/why-concrete-cracks-sarasota/", "Why concrete cracks", "Base movement.")]))
    return P
