# -*- coding: utf-8 -*-
from _h import cap, sec, p, ul, ol, table, note, faq_block, cta, reviewed, link, ext, facts, cards


def pg(route, title, meta, h1, kicker, lede, body, faq, crumb=None):
    return {"route": route, "title": title, "meta_description": meta, "h1": h1, "kicker": kicker, "lede": lede,
            "breadcrumbs": [("Home", "/"), ("HOA & ARC", "/hoa/"), (crumb, None)] if crumb else [("Home", "/"), ("HOA & ARC", None)],
            "body_html": body, "faq": faq, "article": True}


def hub():
    faq = [
        ("What goes in an ARC submittal packet for pavers?", "The association's application form signed by the owner; a survey or site plan with the hardscape drawn to scale and dimensions; the material, manufacturer, color name and a physical sample or photo; the pattern and border; the drainage direction with arrows; the contractor's name and insurance certificate; and the permit application or number if the jurisdiction requires one. Most committees meet once or twice a month, so missing one item costs a month."),
        ("Which comes first: HOA approval or the permit?", "HOA approval, in practice. The building department doesn't care about the association, but the association usually wants to see the permit number and almost always wants to approve before work starts. Submit both at once and let the permit clock run while the committee meets."),
        ("Do HOAs in the Venice area restrict paver colors and patterns?", "Most of the master-planned communities do: Wellen Park's villages, Venetian Golf & River Club, Boca Royale and the Palmer Ranch sub-associations keep approved color lists and reject dark or busy patterns on driveways more often than on rear patios."),
        ("Can an HOA stop a driveway widening the county would permit?", "Yes. Deed restrictions are private contracts; a county permit doesn't override them. Typical rules cap driveway width at the garage's side walls or at 24 feet."),
    ]
    body = cap("Which communities in the Sarasota area review driveway, patio and pool deck changes?",
               "Nearly every master-planned or gated community and most condominiums: Palmer Ranch and its sub-associations, Wellen Park and the West Villages (Islandwalk, Grand Palm, Gran Paradiso, Renaissance, Sarasota National), Venetian Golf & River Club, Boca Royale, Plantation, Heron Creek, Skye Ranch, Laurel Oak, The Meadows, Villagewalk, Bay Isles, Longboat Key Club, Country Club Shores, Rotonda West, and the condo boards on Siesta Key, Longboat Key and Venice Island.",
               p("Rules vary by document, not by county, so this site never states a community's rule from memory. The guides below explain the typical structure, what the packet needs, and how the sequence with the permit works; you bring the community's current guidelines and the estimate is written to them."))
    body += cards([("/hoa/palmer-ranch/", "Palmer Ranch", "Master plus sub-association review; what the packet needs; the driveway and pool deck replacement wave."),
                   ("/hoa/wellen-park/", "Wellen Park and the West Villages", "Driveway width and extension rules, paver color lists, pool deck and lanai review across the Venice and North Port sides."),
                   ("/hoa/barrier-island-condos/", "Barrier-island condominiums", "Board approval, reserves under Florida Statute 718, phasing so the pool stays open, and the substantial-improvement file.")])
    body += sec("What review usually covers", table(["Change", "Typically reviewed?", "What the committee looks at"], [["Driveway extension or widening", "Yes", "Width at the garage, setback from the lot line, material match"], ["Concrete to pavers", "Yes", "Color, pattern, border, edge at the sidewalk"], ["Driveway resurfacing or recoloring", "Often", "Color"], ["Pool deck replacement inside the cage", "Yes", "Material and color; sometimes not if it's invisible from the street"], ["Patio or lanai extension", "Yes", "Footprint, setbacks, drainage"], ["Walkway", "Usually", "Material"], ["Seat wall, fire pit, kitchen", "Yes", "Height, materials, gas"], ["Lighting", "Often", "Fixture style; turtle rules on the islands"], ["Artificial turf", "Yes", "Some communities prohibit it"]], "Typical ARC scope in Sarasota-area communities"))
    body += sec("The packet", ol(["Application form, signed by the owner (contractors usually can't submit).", "Survey or site plan with the work drawn to scale, dimensions and setbacks.", "Material: manufacturer, product, color name, sample or photo; pattern and border for pavers.", "Drainage arrows and a note on where runoff goes.", "Contractor name, certificate of insurance, and the permit number if issued.", "Photos of the existing condition.", "For pool decks: coping material and any lighting."]))
    body += sec("Timeline", p("Most committees meet monthly, some twice a month; a complete packet approved at the next meeting is typical, an incomplete one waits a cycle. Submit the permit application in parallel. In season, approvals plus permits plus scheduling mean six to ten weeks from decision to first day of work; plan a November finish from August."))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/hoa/", "HOA & ARC Approval for Driveways, Patios & Pool Decks", "How architectural review works for driveways, pavers, patios and pool decks in Sarasota-area communities: which communities review, what the packet needs, the sequence with the permit, and guides for Palmer Ranch, Wellen Park and island condos.",
              "HOA and ARC approval for hardscape in Sarasota-area communities", "HOA & ARC", "Most communities here review every exterior change. This is what they ask for, in what order, and how long it takes.", body, faq)


def palmer_ranch():
    faq = [
        ("Does Palmer Ranch require ARC approval for a paver driveway?", "Yes. The sub-association (Prestancia, Turtle Rock, Stoneybrook, Deer Creek, Huntington Pointe, Isles of Sarasota, Sandhill Preserve, Esplanade and others) reviews first, and the Palmer Ranch Master Property Owners Association reviews many changes on top. Each has its own form and guidelines; get both current documents before choosing a color."),
        ("What do the sub-associations usually restrict?", "Driveway width (often the garage's side walls), paver color from an approved list, border contrast, and anything visible from the street. Rear patios and pool decks inside the cage get lighter review."),
        ("How long does Palmer Ranch approval take?", "Three to six weeks for both levels with a complete packet; longer in season when committees are busiest."),
        ("Can I widen my driveway for a third car?", "Only if the sub-association's guideline allows it, usually to the garage wall line and not beyond, and the county's 50 percent impervious cap still applies to the lot."),
    ]
    body = facts([("Structure", "Master association (1986) plus dozens of sub-associations"), ("Review levels", "Sub-association, then master for many changes"), ("Jurisdiction", "Sarasota County (Accela)"), ("Housing", "1990 to 2010; driveway and pool deck replacement age")])
    body += cap("How does architectural review work in Palmer Ranch?",
                "Two levels. Your sub-association's architectural committee reviews first against its own guidelines, and the Palmer Ranch Master Property Owners Association, established in 1986 over the 10,000-acre community, reviews many changes on top. Both need a signed owner application, a site plan, the material and color, and drainage notes; both meet on their own schedule. Sarasota County issues the permit separately.",
                p("The site can't state any sub-association's rule from memory; guidelines are amended by boards. The sequence, the packet and the timing are the same across the community, and the estimate is written to the current documents you provide."))
    body += sec("Why the wave of applications", p("Palmer Ranch homes were built from 1990 to 2010 with builder-grade broom driveways and cool-deck pool decks that are now 15 to 35 years old. Settled driveways at the garage, spalling from well-water sprinklers and delaminating pool deck overlays are the standard findings, so committees see a steady flow of paver driveway and travertine deck applications and have settled expectations about colors and borders."))
    body += sec("Packet for a Palmer Ranch sub-association", ol(["Sub-association application, owner-signed.", "Survey with the driveway or deck drawn, dimensions, setbacks.", "Manufacturer, product and color name, plus a sample chip; border color.", "Pattern (herringbone for driveways).", "Drainage arrows; note if the driveway meets a swale.", "Contractor's certificate of insurance.", "County permit application or number for the apron (right-of-way use permit).", "Photos of the existing driveway or deck."]) + p("The master's form usually asks for the sub-association's approval letter attached."))
    body += sec("Typical timeline", table(["Step", "Time"], [["Sub-association committee", "2 to 4 weeks"], ["Master association", "1 to 3 weeks"], ["County permit (Accela) in parallel", "1 to 3 weeks"], ["Scheduling in season", "2 to 6 weeks"], ["Work", "3 to 7 working days"]], "Palmer Ranch driveway or deck replacement, planning timeline"))
    body += sec("Related", cards([("/areas/palmer-ranch/", "Palmer Ranch locality page", "Soil, flood zone, housing and a worked example."), ("/pavers/driveways/palmer-ranch/", "Paver driveways in Palmer Ranch", "Spec and price band."), ("/permits/sarasota-county/", "Sarasota County permits", "Right-of-way and flatwork rules.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/hoa/palmer-ranch/", "Palmer Ranch ARC Approval for Driveways & Pool Decks", "How Palmer Ranch's two-level architectural review works for paver driveways, concrete driveways and pool decks: sub-association then master, the packet, typical restrictions, timing, and the county permit that runs alongside.",
              "Palmer Ranch: two levels of review for every driveway and pool deck", "HOA & ARC · Palmer Ranch", "Sub-association first, master association second, county permit in parallel. What each wants and how long it takes.", body, faq, "Palmer Ranch")


def wellen_park():
    faq = [
        ("What do Wellen Park ARC guidelines say about driveway width and extensions?", "The site doesn't quote community rules from memory. Rules published by comparable Florida master associations and reported for Wellen Park villages cap driveway width at the garage's side walls or a fixed maximum such as 24 feet, require approval for any extension, resurfacing or material change, and keep an approved paver color list. Get the current guideline from your village's management before choosing."),
        ("Can I widen my driveway in Islandwalk or Grand Palm?", "Only within the village's width rule and with ARC approval; a golf-cart pad or a third-car strip is the common request and the common denial. The site plan needs to show the widening stays inside the garage wall line if that's the rule."),
        ("Which city permits Wellen Park?", "Both. The Venice side is permitted by the City of Venice; the North Port side (including Islandwalk and much of the West Villages) by the City of North Port. The master association reviews all of it."),
        ("Are pool deck changes reviewed?", "Yes, material and color, even inside a cage in most villages; travertine and light concrete pavers are routinely approved, dark colors less so."),
    ]
    body = facts([("Structure", "Master association plus village associations; West Villages Improvement District"), ("Jurisdictions", "City of Venice (west), City of North Port (east)"), ("Housing", "2018 and newer production homes"), ("Common request", "Paver driveway in place of builder concrete; lanai and pool deck upgrades")])
    body += cap("How does architectural review work in Wellen Park?",
                "Village association first, master association where required, and a city permit from Venice or North Port depending on which side of the line the home sits. Homes are 2018 and newer with builder-grade broom driveways and standard lanais, so the applications are paver driveways in approved colors, lanai extensions, pool decks and outdoor kitchens. Width rules, color lists and drainage notes are what committees check.",
                p("Guidelines differ by village (Islandwalk, Grand Palm, Gran Paradiso, Renaissance, Sarasota National, Wellen Park Golf & Country Club and others) and are amended; bring the current document and the estimate is written to it."))
    body += sec("Two cities, one community", table(["Side", "Permit office", "What that adds"], [["Venice", "City of Venice, eTRAKiT; Engineering for the right-of-way", "License agreement if pavers meet the street"], ["North Port", "City of North Port, Click2Gov; Right of Way Use Permit", "Swale and culvert rules on the crossing"]], "Wellen Park permitting by side") + p(f'Details on {link("/permits/venice/", "Venice permits")} and {link("/permits/north-port/", "North Port permits")}.'))
    body += sec("Packet for a village ARC", ol(["Village application, owner-signed.", "Builder site plan or survey with the change drawn.", "Manufacturer, product, color from the approved list, border, pattern.", "For extensions: dimensions showing the width rule is met.", "Drainage arrows; lanai extensions note the cage line.", "Contractor insurance and city permit number."]))
    body += sec("Golf carts", p(f'Wellen Park is golf-cart friendly on its paths; a cart pad or second driveway at the street is a village rule question first and a city right-of-way question second. The {link("/guides/golf-cart-paths/", "golf-cart path guide")} covers it.'))
    body += sec("Related", cards([("/areas/venice/", "Venice locality page", "Island, mainland and the Venice side of Wellen Park."), ("/areas/north-port/", "North Port locality page", "GDC lots and the North Port side."), ("/pavers/driveways/", "Paver driveways", "Spec and prices.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/hoa/wellen-park/", "Wellen Park ARC Approval: Driveways, Pavers & Pool Decks", "Architectural review in Wellen Park and the West Villages for paver driveways, extensions, lanais and pool decks: village then master, width and color rules to check, and which city (Venice or North Port) issues the permit.",
              "Wellen Park: village review, master review and two city permit offices", "HOA & ARC · Wellen Park", "New homes, builder driveways, strict color lists and a city line running through the community. What to submit and to whom.", body, faq, "Wellen Park")


def condos():
    faq = [
        ("How does a condo association approve a pool deck replacement on Siesta Key?", "The board approves it as a common-element project, usually funded from reserves; under Florida Statute 718.112(2)(f) associations maintain reserves for pavement resurfacing and any deferred-maintenance item over $10,000, and the reserve study sets when the deck is due. The board takes bids, votes, and the association pulls the county permit and files the work against its substantial-improvement record."),
        ("Can the pool stay open during the work?", "Usually, with phasing: half the deck is rebuilt while the other half stays open behind a temporary edge, then the phases swap. Boards schedule it for May through September when occupancy is lowest, and the contract states the phase dates."),
        ("Does the 50% rule apply to a condo pool deck?", "The deck is a site improvement outside the building's substantial-improvement calculation, but the association's permit file on Longboat Key or with the county documents it. Keep the deck contract separate from any building work."),
        ("What about turtle lighting on a condo deck?", "Any deck or cage light visible from the beach must be long-wavelength and shielded from May 1 to October 31; boards on Siesta Key and Longboat Key are surveyed by code enforcement from the beach at night."),
    ]
    body = facts([("Who decides", "The board, as a common-element project"), ("Funding", "Reserves under F.S. 718.112(2)(f); special assessment if short"), ("Season", "May to September, phased"), ("Rules", "County or Town permit; 50% file; turtle lighting; setback line")])
    body += cap("How does a condominium on Siesta Key or Longboat Key replace its pool deck?",
                "As a board-approved common-element project: the reserve study flags the deck (pavement resurfacing is a statutory reserve item over $10,000 under Florida Statute 718.112), the board takes comparable bids on a written scope, votes, funds it from reserves or a special assessment, and the association pulls the permit from Sarasota County or the Town of Longboat Key. The work is phased so the pool stays open and documented as a site improvement in the flood file.",
                p("What boards ask for, in order: a scope every bidder prices the same way, a phasing plan with dates, ADA-compliant access and slip resistance, a coping detail for the existing pool beam, a drainage plan for the cage, turtle-compliant lighting, and a warranty they can file."))
    body += sec("A comparable-bid scope for a condo deck", ol(["Square footage of the deck field, coping linear feet, number of cage anchors.", "Demolition and disposal.", "Base: 4 inches compacted in lifts, geotextile, pitched to drains.", "Drains: linear drain at the cage low side, tied to the property's stormwater.", "Material, manufacturer, color, pattern; coping material and profile.", "Edge: concrete curb at the cage line and any surge-exposed edge.", "Polymeric sand, sealing at 30 days.", "Lighting: FWC-certified fixtures if visible from the beach.", "Phasing: two halves, temporary edge, dates.", "Warranty terms, insurance, permit responsibility, legal name."]))
    body += sec("Reserves and timing", p(f'The reserve study\'s useful-life figure for pool decking (20 to 30 years) and the remaining-life estimate set the year; boards that let the component list go stale find the deck underfunded. Bids in the fall, board vote in the winter when owners are present, work in the summer when they aren\'t. The {link("/guides/condo-pool-deck-boards/", "guide for boards")} walks through a 12-month calendar.'))
    body += sec("Island rules that ride along", ul([f'{link("/permits/flood-zones-50-percent-rule/", "Flood zones and the 50% rule")}: deck excluded but documented.', f'{link("/permits/flood-zones-50-percent-rule/", "Gulf Beach Setback Line")}: Gulf-front decks seaward of the line need a variance.', f'{link("/permits/sea-turtle-lighting/", "Sea turtle lighting")}: amber, shielded, May 1 to October 31.', f'{link("/permits/longboat-key/", "Town of Longboat Key")} or {link("/permits/sarasota-county/", "Sarasota County")} permit, pulled by the association.']))
    body += sec("Related", cards([("/pavers/pool-decks/", "Paver pool decks", "Materials and spec."), ("/pricing/pool-decks/", "Pool deck cost guide", "Ranges for 400 to 1,000 square feet; multiply for common decks."), ("/areas/siesta-key/", "Siesta Key", "County rules, flood zones and surge history."), ("/areas/longboat-key/", "Longboat Key", "Town rules and surge history.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/hoa/barrier-island-condos/", "Condo Pool Deck Replacement on Siesta Key & Longboat Key", "How barrier-island condominium boards replace a pool deck: reserves under F.S. 718.112, a comparable-bid scope, phasing to keep the pool open, the county or Town permit, the flood file and turtle lighting.",
              "Condominium pool decks on the barrier islands: reserves, bids, phasing and the island rules", "HOA & ARC · condominiums", "A common-element project with a statute behind the reserves, a permit behind the deck, and a beach behind the lighting rule.", body, faq, "Barrier-island condos")


def get_pages():
    return [hub(), palmer_ranch(), wellen_park(), condos()]
