# -*- coding: utf-8 -*-
"""Permit hub and one page per jurisdiction, plus flood/50%/setback and sea turtle lighting."""
from _h import cap, sec, p, ul, ol, table, note, faq_block, cta, reviewed, link, ext, facts, cards

CHK = "Checked September 10, 2026. Fees and forms change by resolution; confirm with the office before you rely on them."


def pg(route, title, meta, h1, kicker, lede, body, faq=None, crumb="Permits"):
    return {"route": route, "title": title, "meta_description": meta, "h1": h1, "kicker": kicker, "lede": lede,
            "breadcrumbs": [("Home", "/"), ("Permits", "/permits/"), (crumb, None)] if route != "/permits/" else [("Home", "/"), ("Permits", None)],
            "body_html": body, "faq": faq or [], "article": True}


def hub():
    faq = [
        ("Who pulls the permit for hardscape: the homeowner or the contractor?", "The contractor, when it holds the county or city registration the office requires; the owner can pull it as an owner-builder for a home they occupy, with the disclosure the office makes them sign. A contractor who asks you to pull the permit for work it's doing is telling you it can't."),
        ("What happens if a previous owner replaced the pool deck without a permit?", "Nothing until someone looks: a sale, a refinance, an insurance claim or a code complaint. Then the office can require an after-the-fact permit, inspections of what can still be seen, and in the worst case removal. Search the address on the county's or city's permit portal before you buy or before you build on top of it."),
        ("What is the $7,500 residential exemption and does it cover flatwork?", "Under 2026 legislation (HB 803) Sarasota County lets an owner of a single-family home document that a job under $7,500 doesn't need a permit, by submitting a written request, the contract and proof of value (county Bulletin 2026-0002). Whether a specific driveway or slab qualifies is the county's call; the page for the county has the office."),
        ("Does replacing pavers with new pavers on the same footprint need a permit?", "In Charlotte County, yes, always. In unincorporated Sarasota County and the City of Sarasota, often not if the footprint, height and drainage don't change and the work stays off the right-of-way; on the barrier islands and in the Town of Longboat Key, expect review anyway. Ask the office and keep the answer in writing."),
    ]
    body = cap("Which office issues the permit for my address?",
               "It depends on whether the property is inside a city. The City of Sarasota, Venice, North Port and the Town of Longboat Key each run their own building department; everything else in Sarasota County, including Siesta Key, Casey Key, Osprey, Nokomis, South Venice and north Englewood, is the county's. South of the county line it's Charlotte County, which permits every slab and paver field.",
               p(f'Type the address into the {link("/tools/permit-flood-setback-finder/", "permit, flood-zone and setback finder")} and it names the office, the portal and the coastal rules that could apply. Or pick the office below.'))
    body += cards([("/permits/sarasota-county/", "Sarasota County", "Culvert and right-of-way use permits, Accela, the $7,500 exemption, owner-builder rules, the 50% impervious cap."),
                   ("/permits/city-of-sarasota/", "City of Sarasota", "FTG portal, the apron rule, tree permits, retaining walls over 3.5 feet."),
                   ("/permits/venice/", "City of Venice", "eTRAKiT, right-of-way license agreements for pavers, the island."),
                   ("/permits/north-port/", "City of North Port", "Right of Way Use Permit for culverts, driveways, sidewalks and slabs; swale restoration."),
                   ("/permits/longboat-key/", "Town of Longboat Key", "Island-wide permits, substantial-improvement review, Ordinance 2021-01 lighting."),
                   ("/permits/charlotte-county/", "Charlotte County", "All flatwork permitted, published fees, NOC over $5,000."),
                   ("/permits/flood-zones-50-percent-rule/", "Flood zones, the 50% rule and the setback line", "What AE and VE mean for hardscape, what the NFIP rule counts, and where a pool deck needs a variance."),
                   ("/permits/sea-turtle-lighting/", "Sea turtle lighting", "May 1 to October 31 on every barrier island: what bulbs, what fixtures, which ordinance.")])
    body += sec("The five questions every office asks", ol(["Is any part of the work in the public right-of-way (apron, sidewalk, swale, culvert)?", "Does the footprint, height or drainage change?", "Is the lot in a flood zone, and is the property under substantial-improvement review?", "Is the work seaward of the Gulf Beach Setback Line or inside a conservation district?", "Who is doing the work, and are they registered with this office?"]) + p("Answer those five and you know whether it's a permit, an exemption, or a variance."))
    body += sec("Sequence that avoids delays", ol(["Confirm the jurisdiction and flood zone (finder or Property Appraiser map).", "Get HOA or condo board approval in writing, because most associations want it before the permit and most offices don't care about the association.", "Submit the permit with a site plan or survey, the scope, and the contractor's registration.", "Record a Notice of Commencement where the office requires one (Charlotte County over $5,000; Sarasota County for work over $5,000 under Florida's construction lien law).", "Schedule inspections as the office lists them on the job card.", "Close the permit with the final inspection; keep the paperwork for the sale."]))
    body += faq_block(faq, "Permit questions that come up on every job")
    body += reviewed("September 10, 2026")
    return pg("/permits/", "Permits for Concrete & Pavers by Office in Sarasota", "Which office permits a driveway, slab, patio or pool deck for any address in Sarasota County or the Charlotte coast: six jurisdictions, the five questions each asks, flood and setback rules, turtle lighting.",
              "Permits for concrete, pavers and pool decks, one office at a time", "Permits", "Six jurisdictions, six sets of rules. This hub points you to the right one and explains the coastal rules that ride along with every island job.", body, faq)


def sarasota_county():
    faq = [
        ("Do I need a permit to replace my driveway in unincorporated Sarasota County?", "For the private portion, the county reviews driveway replacement as flatwork and small jobs may qualify for the documented $7,500 residential exemption; for any work in the county right-of-way (apron, swale, culvert) you need a culvert permit or a right-of-way use permit under Code Chapter 98 and Chapter 74. Ask the Building division which applies to your scope before demolition."),
        ("How long does a driveway or slab permit take?", "Simple flatwork permits through Accela are typically reviewed in one to two weeks when the application is complete; right-of-way permits go through the Transportation department's review and can take longer because the county surveys line and grade for culverts."),
        ("Can I do my own driveway as an owner-builder?", "Yes, under Code § 22-122(3), for a one- or two-family residence you own and occupy, after signing the county's owner-contractor disclosure in person. You supervise the work yourself; you can't hire an unlicensed person to act as the contractor."),
        ("How do I look up existing permits on my property?", "The county's permit search at building.scgov.net shows permits by address. Check it before buying a home with a new pool deck or driveway, and before building on top of one."),
    ]
    body = facts([("Office", "Building, 1001 Sarasota Center Blvd, Sarasota 34240; 4000 S. Tamiami Trail, Venice"), ("Portal", "Accela Citizen Access (building.scgov.net)"), ("Phone", "(941) 861-5000"), ("Covers", "Siesta Key, Casey Key, Osprey, Nokomis, Laurel, Gulf Gate, Palmer Ranch, Fruitville, Bee Ridge, South Venice, north Englewood")])
    body += cap("What does Sarasota County require for a driveway, slab, patio or pool deck?",
                "Three layers. Work in the county right-of-way needs a culvert permit or a right-of-way use permit issued by the County Engineer (Code Chapter 98 § 98-3 and Chapter 74). Work on the lot is reviewed as flatwork through Accela, with a documented exemption available for single-family jobs under $7,500 (Bulletin 2026-0002). And the contractor must hold a county Operating Certificate and Certificate of Competency for a regulated trade (Chapter 22 § 22-122), or a state license.",
                p(CHK))
    body += sec("Right-of-way work", p("Section 98-3 of the county code states that any work within county rights-of-way must be authorized by a permit from the County Engineer, that installation of a driveway culvert requires a culvert permit including county surveying of line and grade, and that all other work in the right-of-way is subject to a right-of-way use permit. Fees are set by resolution and were not published on a page this site could read; the Transportation department quotes them.") +
                p("In practice: replacing the apron of a driveway that meets a county road, changing the swale, or installing or replacing a culvert is right-of-way work. A driveway that ends at a private sidewalk on your own lot may not be."))
    body += sec("Flatwork on the lot", p("Pool decks, patios, slabs and the private portion of a driveway are building-permit matters reviewed through Accela. Uncovered at-grade slabs that don't change drainage or footprint are frequently below the county's thresholds, but the county, not this page, decides. The 2026 exemption for single-family work under $7,500 requires a written request, a copy of the contract and documentation of the value; keep the county's written answer with the house records."))
    body += sec("Zoning limits that affect hardscape", ul(["Impervious cover: 50 percent of the lot in RSF districts, and pool decks, concrete, asphalt and pavers count; grass, shell and pervious surfaces don't (Appendix A § 6.5). A driveway extension can push a small lot over.", "Trees: grand oaks and other protected trees under Chapter 54, Article XVIII; root pruning and removal need a permit.", "Coastal setback (Chapter 54, Article XXII) and marine turtle protection (Article XXIII) on the barrier islands; conservation districts on North Casey Key (Article XXVI) and Manasota Key (Article XXVII)."]))
    body += sec("Contractor registration", p("Chapter 22, Article V makes it unlawful to contract for regulated construction work without an active Sarasota County Operating Certificate and an applicable Certificate of Competency, in addition to any state license Florida requires. The General Contractors Licensing and Examining Board examines specialty contractors. Owner-builders are exempt for their own occupied home after signing the disclosure in person. Verify a contractor's status with the county before signing."))
    body += sec("Flood and coastal", p(f'Siesta Key, Casey Key, the bayfront and Manasota Key are AE and VE. The county applies the NFIP 50 percent rule to buildings, excludes site improvements, and administers the Gulf Beach Setback Line; pool decks seaward of the line need a coastal setback variance from the County Commission. Details on {link("/permits/flood-zones-50-percent-rule/", "flood zones and the 50% rule")}.'))
    body += sec("Official links", ul([ext("https://www.scgov.net/government/planning-and-development-services/building", "Sarasota County Building"), ext("https://building.scgov.net/", "Permit search and Accela portal"), ext("https://www.scgov.net/government/planning-and-development-services/online-permitting", "Online permitting"), ext("https://www.sarasotapropertyappraiser.gov/propertysearch", "Property Appraiser search (flood zone, jurisdiction)"), ext("http://sarasotacounty.elaws.us/code/coor_ch98_arti_sec98-3", "Code § 98-3, right-of-way permit fees"), ext("http://sarasotacounty.elaws.us/code/coor_ch22_artv_sec22-122", "Code § 22-122, contractor licensing"), ext("http://sarasotacounty.elaws.us/code/coor_apxa_art6_sec6.5", "Zoning App. A § 6.5, RSF impervious cover")]))
    body += note("The county's web pages block automated reading; the rules above come from the county code as published on eLaws, the Property Appraiser and published county bulletins. Confirm the current form and fee with the Building division.", "warn")
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/sarasota-county/", "Do You Need a Permit for a Driveway in Sarasota County?", "Sarasota County permits for driveways, slabs, patios and pool decks: culvert and right-of-way use permits, the Accela portal, the $7,500 exemption, owner-builder rules, contractor registration, the 50% impervious cap and coastal rules.",
              "Sarasota County permits for driveways, slabs, patios and pool decks", "Permits · Sarasota County", "Unincorporated county, from Siesta Key to South Venice: right-of-way permits at the road, flatwork review on the lot, and the zoning and coastal rules that come with them.", body, faq, "Sarasota County")


def city_of_sarasota():
    faq = [
        ("Who issues the permit for a driveway inside Sarasota city limits?", "The City of Sarasota's Development Services, through the FTG permit portal, for any address inside the city, including Lido Key, Bird Key, St. Armands, Indian Beach, Arlington Park and downtown. The county has no role inside the city."),
        ("Does replacing the apron between the sidewalk and the street need a City of Sarasota permit?", "Yes. That strip is city right-of-way; replacing it in concrete or pavers requires a city permit and the city's detail. Local landscape contractors report this consistently and the city's right-of-way use permit process covers it."),
        ("Does the city have the same $7,500 exemption as the county?", "The 2026 legislation applies statewide; the City of Sarasota implements it through its own written-request process. Ask Development Services for the form."),
        ("Do I need a permit for a retaining or seat wall?", "Over 3.5 feet, yes; under it, generally not as a structure, though drainage and setback rules still apply."),
    ]
    body = facts([("Office", "Development Services, City of Sarasota (1565 First Street, Sarasota 34236)"), ("Portal", "FTG permit portal (ftgportal.sarasotafl.gov)"), ("Covers", "Downtown, Rosemary District, Laurel Park, Indian Beach, Sapphire Shores, Arlington Park, Southside Village, Harbor Acres, Bird Key, Lido Key, St. Armands, city portions of Gulf Gate and Southgate"), ("Trees", "Permit for trunks 4 inches and up")])
    body += cap("What does the City of Sarasota require for hardscape?",
                "Inside the city limits the City of Sarasota, not the county, reviews flatwork through its FTG permit portal and Development Services office. The apron between the sidewalk and the street is city property and needs a permit to replace in concrete or pavers. Retaining walls over 3.5 feet need a permit, trees with trunks 4 inches and up need a permit to remove or root-prune, and Lido Key falls under turtle lighting rules.",
                p(CHK + " The city's own permit pages block automated reading; the statements here come from the city's portal structure, its published right-of-way use permit and local practitioners. Verify the exact permit category for a full driveway replacement with Development Services before demolition."))
    body += sec("Is my address in the city?", p(f'The city line is irregular: Gulf Gate Drive, parts of Southgate and the Trail corridor are split. The Property Appraiser\'s property search shows the taxing authority and jurisdiction for any parcel, and the {link("/tools/permit-flood-setback-finder/", "finder")} uses the same logic.'))
    body += sec("What usually applies", table(["Work", "City requirement", "Notes"], [["Driveway apron at the street", "Permit; city detail", "City right-of-way"], ["Private driveway, patio, pool deck", "Flatwork review via FTG; possible $7,500 documented exemption", "Confirm category"], ["Pavers in the right-of-way", "Right-of-way use permit", "Concrete or pavers per detail"], ["Retaining wall over 3.5 ft", "Permit", "Engineering may be required"], ["Tree removal or root pruning, trunk 4 in. and up", "Tree permit", "Applies to driveway and walk routing"], ["Lido Key beach-visible lighting", "Turtle-friendly fixtures, May 1 to Oct 31", "County Article XXIII applies via interlocal agreement; confirm"]], "City of Sarasota hardscape permitting summary"))
    body += sec("Historic and design review", p("Properties in the city's historic districts or individually designated (Indian Beach, Sapphire Shores, Laurel Park, Burns Court and others) may need Historic Preservation Board review for visible changes; entry walks and driveways in front yards can be visible changes."))
    body += sec("Official links", ul([ext("https://www.sarasotafl.gov/Department-Pages/Development-Services/Building-Permitting", "City of Sarasota Building & Permitting"), ext("https://ftgportal.sarasotafl.gov/Permits/Home.aspx?microapp=c", "FTG permit portal"), ext("https://www.sarasotapropertyappraiser.gov/propertysearch", "Property Appraiser (jurisdiction and flood zone)")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/city-of-sarasota/", "City of Sarasota Permits for Driveways, Aprons & Pool Decks", "Permits inside the City of Sarasota for driveways, aprons, patios and pool decks: the FTG portal, the city-owned apron rule, tree permits for trunks over 4 inches, wall height limits and Lido Key lighting.",
              "City of Sarasota permits for driveways, aprons, patios and pool decks", "Permits · City of Sarasota", "Inside the city line the city reviews the work, owns the apron at the street and protects every oak over 4 inches.", body, faq, "City of Sarasota")


def venice():
    faq = [
        ("What does the City of Venice require for pavers in the right-of-way?", "Approval by the city engineer, an approved right-of-way use authorization and a license agreement for any improvement in the right-of-way or a city easement that doesn't meet city standards, which is how pavers over the standard concrete apron are handled, plus construction to the city's detail (Code Chapter 62)."),
        ("What does a permit add to the cost and timeline of a driveway in Venice?", "Two to five weeks between the building permit through eTRAKiT and the engineering review of the apron, and the cost of the concrete apron to city detail (often 6 inches) or the license agreement for pavers. Budget the time before the season."),
        ("Does Venice Island have extra rules?", "Flood zones AE and VE, the historic district's design guidelines in the Nolen plan area, and turtle lighting on beach-visible properties."),
        ("Which portal does Venice use?", "eTRAKiT (trakit.venicegov.com) for building permits; Engineering handles right-of-way permits and license agreements."),
    ]
    body = facts([("Offices", "Building Department (permits) and Engineering (right-of-way), City of Venice"), ("Portal", "eTRAKiT (trakit.venicegov.com)"), ("Covers", "Venice Island, mainland city, Wellen Park villages inside the city line"), ("Right-of-way", "License agreement for non-standard improvements such as pavers")])
    body += cap("What does the City of Venice require for a driveway, apron or pool deck?",
                "Two departments. The Building Department permits flatwork on the lot through eTRAKiT. Engineering controls the right-of-way: any improvement in a city right-of-way or easement that doesn't meet city standards needs the city engineer's approval, a right-of-way use authorization and a license agreement, and pavers in the right-of-way must be built to the city's standards (Code Chapter 62). Aprons are commonly 6 inches of concrete to the city detail.",
                p(CHK + " The city's engineering page blocks automated reading; the summary comes from the Venice Code of Ordinances and the city's published permit structure."))
    body += sec("What usually applies", table(["Work", "Venice requirement"], [["Private driveway, patio, pool deck", "Building permit via eTRAKiT (confirm threshold for like-for-like replacement)"], ["Apron and any work at the street", "Engineering right-of-way review; concrete to city detail or license agreement for pavers"], ["Pavers over the standard apron", "License agreement recorded against the property"], ["Venice Island historic area", "Design review for visible changes"], ["Beach-visible lighting", "Red or amber LEDs in shielded, downward fixtures, May 1 to Oct 31"], ["Wellen Park (Venice side)", "City permit plus master association ARC approval"]], "City of Venice hardscape permitting summary"))
    body += sec("Official links", ul([ext("https://www.venicegov.com/government/engineering/permits-forms-and-applications", "Venice Engineering permits and forms"), ext("https://trakit.venicegov.com/etrakit/", "eTRAKiT permit portal"), ext("https://library.municode.com/fl/venice/codes/code_of_ordinances", "Venice Code of Ordinances (Chapter 62, streets and sidewalks)"), ext("https://www.venicegov.com/living/sea-turtle-lightning", "Venice sea turtle lighting")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/venice/", "City of Venice Permits: Driveways, Aprons, Pavers & Pool Decks", "City of Venice permits for driveways, aprons, pavers and pool decks: eTRAKiT building permits, Engineering's right-of-way review and license agreements for pavers, Venice Island rules and Wellen Park review.",
              "City of Venice permits for driveways, aprons, pavers and pool decks", "Permits · Venice", "Building permits through eTRAKiT, and an Engineering department that controls the right-of-way with license agreements when pavers meet the street.", body, faq, "Venice")


def north_port():
    faq = [
        ("Do I need a culvert permit for a driveway on a North Port GDC lot?", "Yes, when the driveway crosses the roadside swale, which most do. The city's Right of Way Use Permit application lists Culvert/Driveway/Sidewalk/Concrete Slab as work types; the city sizes the culvert, and Public Works inspects the swale restoration before final approval."),
        ("Does North Port require engineered drawings for a driveway?", "Construction documents that need sealing must be sealed by a Florida-licensed engineer or architect; a standard residential driveway and culvert usually follow the city's detail without a custom design. The Building Division confirms which applies."),
        ("What are the fees?", "The city publishes common permit costs by type on its Permit Fees page; the exact culvert and driveway fees weren't readable on the page this site could reach. Call (941) 429-7044 or check northportfl.gov before budgeting."),
        ("Which portal?", "Click2Gov (npor-egov.aspgov.com) for applications and status; forms on northportfl.gov under Building-Planning, Permitting."),
    ]
    body = facts([("Office", "Building Division, City of North Port (4970 City Hall Blvd)"), ("Phone / email", "(941) 429-7044 · bldginfo@cityofnorthport.com"), ("Portal", "Click2Gov"), ("Key permit", "Right of Way Use Permit: Culvert / Driveway / Sidewalk / Concrete Slab")])
    body += cap("What does North Port require for a driveway, culvert or slab?",
                "A Right of Way Use Permit whose application lists Culvert/Driveway/Sidewalk/Concrete Slab as work types, with the applicant responsible for repairing and restoring the roadway, right-of-way, swales and adjacent property before the Public Works Department gives final approval. Slabs, patios and pool decks on the lot are building permits through the Building Division and Click2Gov, with sealed drawings where the city's standard details don't cover the work.",
                p(CHK))
    body += sec("Why the swale matters in North Port", p("General Development Corporation platted tens of thousands of quarter-acre lots here from the 1950s to the 1980s and drained them with roadside swales, many of which were left shallow or pitched the wrong way. A driveway crossing is a drainage structure: the city sizes the culvert, the ends are set back from the frontage lines, and the swale on both sides is regraded so water keeps moving. That's why the permit includes a Public Works inspection and why a poured-flat crossing is the most common violation."))
    body += sec("What usually applies", table(["Work", "North Port requirement"], [["Driveway crossing the swale", "Right of Way Use Permit; culvert sized by the city; swale restoration inspected"], ["Driveway replacement not touching the swale", "Building permit (confirm threshold)"], ["Slab, patio, pool deck", "Building permit via Click2Gov; sealed drawings if required"], ["Sidewalk in the right-of-way", "Right of Way Use Permit"], ["Wellen Park (North Port side)", "City permit plus master association ARC approval"]], "North Port hardscape permitting summary"))
    body += sec("Official links", ul([ext("https://www.northportfl.gov/Building-Planning/Permitting", "North Port Permitting"), ext("https://www.northportfl.gov/Building-Planning/Permitting/Permit-Forms", "Permit forms"), ext("https://www.northportfl.gov/Building-Planning/Permitting/Permit-Fees", "Permit fees"), ext("https://npor-egov.aspgov.com/Click2GovBP/index.html", "Click2Gov portal")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/north-port/", "North Port Permits: Driveways, Culverts, Swales & Slabs", "City of North Port permits for driveways, culverts, sidewalks and slabs: the Right of Way Use Permit, swale restoration and Public Works inspection, sealed drawings, Click2Gov, and the GDC-lot drainage reality.",
              "North Port permits for driveways, culverts, sidewalks and slabs", "Permits · North Port", "On a GDC lot the driveway starts at the swale, and the city's Right of Way Use Permit is where the crossing gets sized and inspected.", body, faq, "North Port")


def longboat_key():
    faq = [
        ("Does the Town of Longboat Key require a permit for a paver driveway or pool deck?", "The Town's Planning & Zoning division reviews driveways, decks and patios directly at grade under its zoning criteria and approves them as exceptions, and every permit on a property subject to substantial-improvement or substantial-damage review goes through the Town. Treat any driveway or deck change as a Town permit until the Building Division tells you otherwise."),
        ("What is substantial damage on Longboat Key?", "Under the Town's flood code (Chapter 154), substantial damage is damage where the cost to restore the building to its pre-damage condition would equal or exceed 50 percent of its market value before the damage. A substantially improved or damaged building must be brought into compliance, including elevation to the Flood Protection Elevation."),
        ("Does a new pool deck count against that 50 percent?", "Site improvements outside the building generally don't, under FEMA's guidance, but the Town documents them in the file. The permit application shows the work as a site improvement so the reviewer can exclude it."),
        ("Which county's rules apply?", "The Town's. Longboat Key spans Sarasota and Manatee counties but has its own building, zoning, flood and turtle codes for the whole island."),
    ]
    body = facts([("Office", "Planning, Zoning & Building, Town Hall, 501 Bay Isles Rd, Longboat Key 34228"), ("Phone", "(941) 316-1999; Code Enforcement (941) 316-1966 ext. 2520"), ("Flood code", "Chapter 154; substantial improvement / damage review"), ("Turtle code", "Chapter 100, Ordinance 2021-01")])
    body += cap("What does the Town of Longboat Key require for driveways, decks and pool decks?",
                "A Town permit and Planning & Zoning review for at-grade driveways, decks and patios, which the code treats as exceptions to be approved under its zoning criteria, and a substantial-improvement or substantial-damage check on every permit for a property in that review. The island is AE and VE end to end, so the check applies almost everywhere. Lighting visible from the beach must meet Chapter 100 from May 1 to October 31.",
                p(CHK + " The Town's building FAQ pages moved during a website update and returned 404 when this site tried to read them; the summary comes from the Town's code (Chapters 154 and 158) and its turtle-lighting pages."))
    body += sec("What usually applies", table(["Work", "Town requirement"], [["Driveway, deck or patio at grade", "Planning & Zoning approval as an exception; building permit"], ["Pool deck replacement", "Permit; site improvement documented against the SI/SD file"], ["Any work after storm damage", "Permit; substantial-damage determination on the building"], ["Beach-visible lighting", "560 nm or longer bulbs, fully shielded downward fixtures, FWC-certified where possible"], ["Community review", "Bay Isles, Longboat Key Club, Country Club Shores and condominiums review first"]], "Town of Longboat Key hardscape permitting summary"))
    body += sec("Official links", ul([ext("https://www.longboatkey.org/202/Building-Division", "Building Division"), ext("https://www.longboatkey.org/214/Marine-Turtle-Protection", "Marine Turtle Protection"), ext("https://www.longboatkey.org/218/Turtle-friendly-Bulbs-Fixtures", "Turtle-friendly bulbs and fixtures"), ext("https://library.municode.com/fl/longboat_key/codes/code_of_ordinances", "Town Code of Ordinances (Chapters 100, 154, 158)")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/longboat-key/", "Longboat Key Permits: Driveways, Decks & the 50% Rule", "Town of Longboat Key permits for driveways, patios and pool decks: Planning & Zoning review of at-grade work, substantial-improvement and damage checks under Chapter 154, Ordinance 2021-01 lighting and the island-wide jurisdiction.",
              "Town of Longboat Key permits for driveways, decks and pool decks", "Permits · Longboat Key", "One town government for both county halves, a flood code that checks every permit, and a lighting ordinance with a wavelength in it.", body, faq, "Longboat Key")


def charlotte():
    faq = [
        ("Does Charlotte County require a permit for a concrete slab or for pavers?", "Yes. The county's residential slab page states that all concrete flatwork, structural or non-structural, including pavers, requires a permit and inspections. The residential driveway page adds that a driveway located only in the right-of-way is applied for as a ROW permit instead."),
        ("What is a Notice of Commencement and when does Charlotte County require one?", "A recorded notice under Florida's construction lien law that identifies the property, owner and contractor. Charlotte County requires a signed, recorded copy before scheduling the first inspection for any improvement with a direct contract price over $5,000."),
        ("What are the fees?", "Published on the county's pages: zoning review $22; slab review $22 non-structural or $90 structural; line and grade $310 at issuance (or right-of-way $90); building fee of 0.004 times ICC valuation when the valuation is $50,000 or more, plus a surcharge of 0.025 times the building fee. Payable by check to CCBCC or card."),
        ("Which licenses can pull a driveway or slab permit?", "Owner-builder, certified or registered Building, General or Residential contractors, and Local Concrete Masonry."),
    ]
    body = facts([("Office", "Community Development, 18500 Murdock Circle, Port Charlotte 33948"), ("Phone", "(941) 743-1200; Zoning (941) 743-1964"), ("Rule", "All flatwork, pavers included, requires a permit and inspections"), ("NOC", "Required over $5,000 before the first inspection")])
    body += cap("What does Charlotte County require for a driveway, slab or paver field?",
                "A permit and inspections for all residential concrete flatwork, structural or non-structural, pavers included, with an Application for Construction Permit, a legible scaled site plan showing easements and property lines, signed and sealed drawings where required, an Affidavit for Accessory Structures when the slab supports one, and a recorded Notice of Commencement over $5,000. Driveways only in the right-of-way are ROW permits.",
                p(CHK + " Charlotte County's pages were read in full on that date and are linked below."))
    body += sec("Fees on the county's pages", table(["Fee", "Amount", "When"], [["Zoning review", "$22", "At application"], ["Slab review, non-structural", "$22", "At application"], ["Slab review, structural", "$90", "At application"], ["Building fee", "0.004 × ICC valuation (if $50,000 or more)", "At application"], ["Surcharge", "0.025 × building fee", "At application"], ["Line and grade", "$310", "At issuance"], ["Right-of-way (instead of line and grade, when applicable)", "$90", "At issuance"]], "Charlotte County residential driveway and slab fees, as published September 10, 2026"))
    body += sec("Other requirements on the pages", ul(["Termite treatment for work performed one foot or less from an existing structure.", "An occupation-of-easement approval from Real Estate Services when flatwork or pavers cross an easement.", "Zoning contact for setbacks and coverage limits when the slab supports a shed or detached garage.", "Two original signed/sealed sets in person, one digitally signed set online."]))
    body += sec("Official links", ul([ext("https://www.charlottecountyfl.gov/departments/community-development/building-construction/permits/residential-permits/residential-driveway.stml", "Residential Driveway permit"), ext("https://www.charlottecountyfl.gov/departments/community-development/building-construction/permits/residential-permits/residential-slab.stml", "Residential Slab (flatwork) permit"), ext("https://www.charlottecountyfl.gov/departments/community-development/building-construction/permits/right-of-way-permit.stml", "Right-of-way permit requirements")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/charlotte-county/", "Charlotte County Permits: Slabs, Driveways & Pavers", "Charlotte County permits for driveways, slabs and pavers: all flatwork including pavers requires a permit and inspections, published fees ($22 zoning, $310 line and grade), Notice of Commencement over $5,000, easements and termite rules.",
              "Charlotte County permits for driveways, slabs and pavers", "Permits · Charlotte County", "Port Charlotte, Rotonda West, Placida and south Englewood: every slab and paver field is permitted, and the fees are published.", body, faq, "Charlotte County")


def flood():
    faq = [
        ("Does a new pool deck count toward the FEMA 50% rule on Siesta Key?", "Generally no. The NFIP's substantial-improvement calculation counts improvements to the building; FEMA's guidance and local FAQs exclude outside improvements such as landscaping, driveways, pools and seawalls. Sarasota County and the Town of Longboat Key make the determination case by case, so the permit application still identifies the deck as site work."),
        ("What is the difference between AE and VE flood zones for hardscape?", "AE is a Special Flood Hazard Area with a base flood elevation and no wave action; VE adds velocity wave action and the strictest rules, including limits on what can be built under an elevated home. In VE, decks and driveways are designed to break away or be sacrificial, pavers on a rebuildable base are favored, and nothing under the house may obstruct flow."),
        ("Can I build a pool deck seaward of the Gulf Beach Setback Line?", "Only with a coastal setback variance from the Sarasota County Board of County Commissioners after a public hearing, on a showing of unreasonable hardship. Pools, spas and pool decks are treated as structures under Chapter 54, Article XXII; recent variances have been granted for decks 60 to 70 feet seaward of the line on Siesta Key and Casey Key, and others have been denied."),
        ("Should I choose pavers or poured concrete in a VE zone?", "Pavers, in most cases. A surge that lifts a slab destroys it; a surge that shifts a paver field leaves reusable units on a base that can be rebuilt and flushed. The exception is an engineered slab under an elevated home, which is designed by the structural engineer."),
    ]
    body = facts([("50% rule", "NFIP; building improvements vs. market value; site work excluded"), ("Calculation (Sarasota)", "Tax-roll improvement value × 1.2, halved; or private appraisal"), ("Setback", "Gulf Beach Setback Line, Sarasota County Code Ch. 54 Art. XXII"), ("Zones", "AE on most of the islands; VE on the Gulf-facing rows")])
    body += cap("What does the FEMA 50 percent rule mean for a pool deck or driveway?",
                "The NFIP prohibits improving a building in a flood zone by more than 50 percent of its market value unless the whole building is brought into compliance with current flood rules. The Sarasota County Property Appraiser explains the threshold as the tax-roll improvement value times 1.2, halved, or a private appraisal. FEMA's guidance excludes outside improvements such as driveways, pools and landscaping from the count, so hardscape rarely triggers it.",
                p("The county's disaster-recovery page and the Town of Longboat Key's Chapter 154 govern the determination. Substantial damage after a storm is the same test applied to repair costs. Keep every hardscape invoice labeled as site work so the reviewer can exclude it, and don't bundle it into a building contract."))
    body += sec("How the 50% threshold is found", ol(["Look up the parcel on the Property Appraiser's search: it shows the flood zone and the improvement value.", "Multiply the improvement value by 1.2 (the appraiser's adjustment) and halve it: that's the tax-roll threshold.", "Or commission a private appraisal of the building's pre-work market value; the appraiser's page says that's often the better option.", "Count improvements to the structure: materials, labor, built-ins, overhead and profit. Exclude plans, permits, surveys and outside improvements to the land."]))
    body += sec("AE versus VE", table(["", "Zone AE", "Zone VE"], [["Meaning", "1% annual-chance flood with a base flood elevation", "Same, plus velocity wave action (coastal high hazard)"], ["Where", "Most of Siesta Key, Longboat Key, Lido, Casey Key, Manasota Key; bayfront and canals", "Gulf-facing rows on the islands"], ["Under an elevated home", "Enclosures limited; flood vents", "Only breakaway walls and open lattice; no obstruction to flow"], ["Driveways and decks", "Normal construction; drainage matters", "Designed to be sacrificial or rebuildable; pavers on a base favored"], ["Insurance", "Required with a federally backed mortgage", "Required; highest premiums"]], "FEMA zones as they affect hardscape"))
    body += sec("The Gulf Beach Setback Line", p("Sarasota County established the Gulf Beach Setback Line in 1979 to protect dunes and coastal habitat that shield landward structures from storms. Under Code Chapter 54, Article XXII, § 54-723, construction and excavation are prohibited seaward of the line (and waterward of the Barrier Island Pass Twenty-Year Hazard Line) except for maintenance of existing structures within their existing foundations that isn't a substantial improvement, and projects granted a coastal setback variance by the Board of County Commissioners under § 54-724 on a showing of unreasonable hardship. Swimming pools, spas and pool decks are ancillary structures that need a variance when seaward of the line. The Property Appraiser's map and the county's GIS show the line for any Gulf-front parcel."))
    body += sec("Conservation districts", p("North Casey Key (Laws of Florida ch. 70-937, county Code Chapter 54 Article XXVI) and Manasota Key (ch. 71-904, Article XXVII) carry additional construction rules enforced by the county. Hardscape on those keys is reviewed under them alongside the setback code."))
    body += sec("What this means for the estimate", ul(["Every island scope states the FEMA zone and base flood elevation.", "Hardscape is invoiced as site work, separately from any building work.", "In VE, the default is pavers on a rebuildable base with concrete curbs; poured decks only where an engineer specifies them.", "Gulf-front lots are checked against the setback line before design, and a variance timeline (months, with a public hearing) is stated if the deck would be seaward of it.", "Elevated homes get an engineered slab under any deck that sits below the house."]))
    body += sec("Official links", ul([ext("https://www.sarasotapropertyappraiser.gov/appraisal-info/damage-reporting/understanding-the-fema-50-rule/", "Sarasota County Property Appraiser: Understanding the FEMA 50% Rule"), ext("https://www.scgov.net/government/planning-and-development-services/building/disaster-recovery", "Sarasota County disaster recovery (substantial improvement)"), ext("https://www.fema.gov/sites/default/files/documents/fema_nfip_substantial-improvement-substantial-damage-desk-reference.pdf", "FEMA P-758 Substantial Improvement / Substantial Damage Desk Reference"), ext("http://sarasotacounty.elaws.us/code/coor_ch54_artxxii_sec54-723", "Sarasota County Code § 54-723 (Gulf Beach Setback Line)"), ext("https://msc.fema.gov/portal/home", "FEMA Flood Map Service Center")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/flood-zones-50-percent-rule/", "Flood Zones, the 50% Rule & the Setback Line for Pool Decks", "What FEMA AE and VE zones, the NFIP 50% substantial-improvement rule and Sarasota County's Gulf Beach Setback Line mean for pool decks, driveways and pavers on Siesta Key, Longboat Key, Casey Key and Manasota Key.",
              "Flood zones, the 50 percent rule and the Gulf Beach Setback Line, applied to hardscape", "Permits · flood and coastal", "Three rules that ride along with every barrier-island job: what counts toward 50 percent, what VE changes, and where a pool deck needs a variance.", body, faq, "Flood zones & 50% rule")


def turtle():
    faq = [
        ("What lighting can I put on a pool deck on Longboat Key between May 1 and October 31?", "Bulbs that are FWC Certified Wildlife Lighting or that produce only long-wavelength light of 560 nanometers or more without filters, gels or lenses, in fixtures that are FWC-certified or fully shielded, downward-directed, full cut-off with non-reflective opaque interiors, wherever the light is visible from the beach, under Town Ordinance 2021-01 (Chapter 100)."),
        ("What does 560-nanometer turtle-friendly lighting mean?", "Light at the amber-to-red end of the visible spectrum. Research cited by the Town shows hatchlings are far less likely to be disoriented by wavelengths of 560 nm and longer; modern amber and red LEDs produce it directly. A white LED behind an amber lens does not qualify."),
        ("Do path lights in a paver walkway need to be turtle compliant on Casey Key?", "Yes, if the beach can see them. Sarasota County's Marine Turtle Protection article (Chapter 54, Article XXIII) applies on Casey Key, Siesta Key and Manasota Key; the county's guidance is to extinguish white lights visible from the beach or replace them with amber or red LEDs in shielded fixtures."),
        ("Is the rule only for beachfront houses?", "It's for any light visible from the beach, which on a narrow key can include the second row and a lit pool cage. The county and the Town test with a survey from the beach at night."),
    ]
    body = facts([("Season", "May 1 to October 31"), ("Wavelength", "560 nm or longer (amber/red)"), ("Fixtures", "Fully shielded, downward-directed, full cut-off"), ("Codes", "Sarasota County Ch. 54 Art. XXIII; Longboat Key Ch. 100 (Ord. 2021-01); Venice; FDEP Rule 62B-55")])
    body += cap("What do the sea turtle lighting rules require of hardscape lighting?",
                "From May 1 to October 31, any artificial light visible from a nesting beach must be long-wavelength (560 nanometers or longer, amber or red) and mounted in fully shielded, downward-directed fixtures, or be turned off. Sarasota County enforces this under Chapter 54, Article XXIII; the Town of Longboat Key under Chapter 100 (Ordinance 2021-01, adopted July 2, 2021); the City of Venice under its own rules; all trace to the FDEP model ordinance in Rule 62B-55.",
                p("For pavers and concrete this means path lights, step lights, wall-cap lights, column lights and pool-cage perimeter lighting are specified as FWC Certified Wildlife Lighting from the start on Siesta Key, Longboat Key, Lido Key, Casey Key, Manasota Key and Venice Island, and it costs nothing extra to do it that way in a new install. Retrofitting later means lifting pavers."))
    body += sec("What the codes say", table(["Jurisdiction", "Rule", "Source"], [["Sarasota County (Siesta Key, Casey Key, Manasota Key, unincorporated beaches)", "Extinguish white lights visible from the beach or replace with amber/red LEDs in shielded fixtures; Sea Turtle Protection Program (941) 861-5000", "Code Ch. 54 Art. XXIII; county lighting guide"], ["Town of Longboat Key", "Turtle-friendly bulbs (FWC-certified or 560 nm+ without filters) and fixtures (fully shielded, downward, full cut-off, opaque interior) for all light visible from the beach; Code Enforcement tests bulbs, (941) 316-1966 ext. 2520", "Ch. 100, Ord. 2021-01"], ["City of Venice", "Red or amber LEDs in shielded, downward-directed fixtures on beach-visible properties", "City page; county Ch. 54 Art. XXV"], ["State model", "Definitions of certified wildlife lighting, sea turtle lighting district, pool-area and outdoor-area provisions", "FDEP Rule 62B-55.004 (effective 2020-12-17)"]], "Sea turtle lighting rules on the Sarasota coast"))
    body += sec("Fixtures that pass", ul(["Recessed paver lights with amber LEDs and a louver or hood.", "Step and riser lights with a hood, amber LED, mounted low.", "Hardscape lights under a seat-wall cap, amber, full cut-off.", "Column lights with a full cut-off shroud and an amber lamp.", "Any fixture on the FWC Certified Wildlife Lighting list, which the Town of Longboat Key links and which local suppliers stock; the Town also lists retail amber A19 and PAR38 LED bulbs."]) + p("What fails: white LEDs, white bulbs behind amber lenses, unshielded path lights, uplights on palms, cage lights visible from the sand."))
    body += sec("Design rules used on island projects", ol(["Put fixtures low and aim them down; a light you can't see from the beach standing on the sand is the goal.", "Wire in conduit under the pavers during the base work.", "Use brass or copper fixtures; salt air eats powder-coated aluminum.", "Put the transformer on a photocell and a timer; the season is May through October but the fixtures stay amber all year, because swapping bulbs twice a year is how people end up in violation.", "Keep a copy of the FWC certification for each fixture with the permit file."]))
    body += sec("Official links", ul([ext("https://myfwc.com/wildlifehabitats/wildlife/sea-turtle/lighting/", "FWC: Sea turtles and lights"), ext("https://myfwc.com/conservation/you-conserve/lighting/ordinances/", "FWC: Sea turtle protection ordinances by county"), ext("https://www.longboatkey.org/218/Turtle-friendly-Bulbs-Fixtures", "Longboat Key: Turtle-friendly bulbs and fixtures"), ext("https://www.scgov.net/Home/Components/News/News/3461/", "Sarasota County: Keep light out of sight during nesting season"), ext("https://www.venicegov.com/living/sea-turtle-lightning", "City of Venice: Sea turtle lighting"), ext("https://floridadep.gov/sites/default/files/62B-55_ModelLightingOrdinance_NPR_0.pdf", "FDEP Model Lighting Ordinance for Sea Turtle Protection")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("/permits/sea-turtle-lighting/", "Sea Turtle Lighting Rules for Pool Decks & Hardscape (2026)", "What Sarasota County, Longboat Key and Venice require for hardscape lighting from May 1 to October 31: 560 nm amber or red bulbs, fully shielded fixtures, FWC-certified products, the ordinances and how to design paver lighting that passes.",
              "Sea turtle lighting rules for pool decks, walkways and hardscape on the barrier islands", "Permits · sea turtle lighting", "May 1 to October 31, any light the beach can see must be long-wavelength and shielded. Here is the rule, the codes and the fixtures that pass.", body, faq, "Sea turtle lighting")


def get_pages():
    return [hub(), sarasota_county(), city_of_sarasota(), venice(), north_port(), longboat_key(), charlotte(), flood(), turtle()]
