# -*- coding: utf-8 -*-
"""Service-area hub, two county hubs, 12 Tier 1 and 3 Tier 2 locality pages. Every page is written from
the place's jurisdiction, flood zone, soil, housing stock and community rules; nothing is a city-name swap."""
from _data import CITIES, TIER1, TIER2, CITY_SERVICE, SERVICES, cs_route, BASE_URL
from _h import cap, sec, p, ul, ol, table, note, faq_block, cta, reviewed, svc_link, city_link, cs_link, link, ext, facts, cards
from templates import lead_form


def local_services(slug):
    xs = [cs_link(c, s, SERVICES[s]["name"]) for c, s in CITY_SERVICE if c == slug]
    return xs


def city_page(slug, title, meta, h1, lede, intro_html, sections, faq, changelog="First publication."):
    c = CITIES[slug]
    body = facts([("Jurisdiction", c["jurisdiction"]), ("Drive from Sarasota", c["drive"]), ("Population", c["population"]), ("Flood zones", c["flood"].split(";")[0])])
    body += intro_html
    for h, html_ in sections:
        body += sec(h, html_)
    body += sec("Local service pages", p(f"Written for {c['name']}, one service each:") + ul(local_services(slug)) +
                p(f'All other services: {link("/concrete/", "concrete")}, {link("/pavers/", "pavers")}.'))
    body += faq_block(faq, f"Questions from {c['name']} homeowners")
    body += sec("Request an estimate in " + c["name"], lead_form(city=c["name"]))
    body += reviewed("September 10, 2026", changelog)
    return {"route": f"/areas/{slug}/", "title": title, "meta_description": meta, "h1": h1, "kicker": f"Service area · {c['county']}", "lede": lede,
            "breadcrumbs": [("Home", "/"), ("Areas", "/areas/"), (c["name"], None)], "body_html": body, "faq": faq,
            "schema": [{"@context": "https://schema.org", "@type": "Place", "name": c["name"], "sameAs": c["wiki"], "geo": {"@type": "GeoCoordinates", "latitude": c["lat"], "longitude": c["lng"]}, "containedInPlace": {"@type": "AdministrativeArea", "name": c["county"]}}]}


# ------------------------------------------------------------------ AREAS HUB
def areas_hub():
    rows1 = [[city_link(c), CITIES[c]["jurisdiction"], f'{CITIES[c]["miles"]} mi · {CITIES[c]["drive"]}', CITIES[c]["population"]] for c in TIER1]
    rows2 = [[city_link(c), CITIES[c]["jurisdiction"], f'{CITIES[c]["miles"]} mi · {CITIES[c]["drive"]}', CITIES[c]["population"]] for c in TIER2]
    body = cap("Which places does Sarasota Concrete serve?",
               "All of Sarasota County, from Longboat Key and the city of Sarasota south through Siesta Key, Palmer Ranch, Osprey, Nokomis, Venice, South Venice, North Port and Englewood, plus the Charlotte County coast inside 40 miles: Port Charlotte, Rotonda West, Placida, Grove City and Cape Haze. Manatee County and south Hillsborough are inside the radius but served through their own local sites.",
               p("Distances are straight-line from downtown Sarasota (27.3364, -82.5307), calculated September 10, 2026; drive times reflect the bridges and the I-75 and US-41 corridors. Population figures are the Florida Office of Economic and Demographic Research estimates for April 1, 2025 for municipalities and the 2020 Census for census-designated places."))
    body += sec("Tier 1: Sarasota County, every service", table(["Locality", "Permit office", "Distance and drive", "Population"], rows1))
    body += sec("Tier 2: Charlotte County coast, four services", p("Pool decks, paver driveways, concrete driveways and concrete repair are scheduled in Charlotte County; other services are quoted case by case.") + table(["Locality", "Permit office", "Distance and drive", "Population"], rows2))
    body += sec("County hubs", cards([("/areas/sarasota-county/", "Sarasota County", "Permits, flood zones, the setback line, turtle lighting, soils, HOAs and seasonality for the whole county."), ("/areas/charlotte-county/", "Charlotte County coast", "What Charlotte permits differently, the canal neighborhoods, Rotonda's deed restrictions and Lemon Bay exposure.")]))
    body += cap("Are Lakewood Ranch and Bradenton covered from this site?",
                "No, and on purpose. Lakewood Ranch, University Park, Whitfield, Bayshore Gardens, Bradenton, Palmetto, Ellenton, Parrish, Myakka City, Cortez and Anna Maria Island are 5 to 20 miles away but sit in Manatee County, where the same provider works through Lakewood Ranch Concrete. Ruskin, Sun City Center, Wimauma, Apollo Beach, Gibsonton and Riverview in south Hillsborough are served the same way.",
                p("Keeping one site per county keeps the permit, flood and community information accurate; a page that tried to cover Manatee's building department and Sarasota's at once would get both half right. Punta Gorda, Arcadia, Tampa, Boca Grande and St. Petersburg are outside the radius or across a bay that turns 30 miles into 90 minutes and aren't covered."))
    body += sec("How the tiers were drawn", p("Tier 1 is every Sarasota County locality with its own permit story or ground story: twelve pages, all services. Tier 2 is the Charlotte County coast inside the radius, three pages, four services, because a 55-minute drive is fair for a pool deck and not for a shed pad. Manatee and Hillsborough localities inside 40 miles are listed but not paged, to keep one site per county and one canonical answer per question."))
    body += sec("Bridges and travel", ul(["Siesta Key: Siesta Drive bridge (north) or Stickney Point bridge (south); both are drawbridges and both back up in season.", "Longboat Key: the John Ringling Causeway and St. Armands Circle from Sarasota, or Cortez Road and the Longboat Pass bridge from Bradenton; a truck and trailer plan the day around the openings.", "Casey Key: the Blackburn Point swing bridge, one lane, weight-limited; deliveries are staged.", "Venice Island: the Venice Avenue, KMI and Circus bridges over the Intracoastal.", "Manasota Key: Manasota Beach Road from Englewood, or Beach Road from the south; the key spans both counties.", "North Port and the Charlotte coast: I-75 to Toledo Blade or River Road, or SR-776 through Englewood."]))
    body += reviewed("September 10, 2026")
    return {"route": "/areas/", "title": "Service Area: Sarasota County & the Charlotte Coast", "meta_description": "Where Sarasota Concrete works: every Sarasota County locality from Longboat Key to Englewood plus Port Charlotte, Rotonda West and Placida, with permit office, drive time, population and why Manatee is served separately.",
            "h1": "Service area: Sarasota County and the Charlotte County coast, 40 miles from Sarasota", "kicker": "Areas",
            "lede": "Fifteen locality pages and two county hubs, each with the permit office, flood zone, soil, housing stock and drive time, so an estimate starts with the right rules.",
            "breadcrumbs": [("Home", "/"), ("Areas", None)], "body_html": body}


# ------------------------------------------------------------------ COUNTY HUBS
def sarasota_county():
    body = facts([("Population", "487,640 (Florida EDR, April 2025); over 570,000 in winter"), ("Permit offices", "County, City of Sarasota, Venice, North Port, Town of Longboat Key"), ("Impervious cap", "50% of an RSF lot (Zoning App. A § 6.5)"), ("Turtle season", "May 1 to October 31")])
    body += cap("What rules apply across unincorporated Sarasota County for hardscape?",
                "Four county codes govern most of it: Chapter 98 and Chapter 74 (work in the right-of-way needs a culvert permit or right-of-way use permit), Chapter 22 Article V (contractors need a county Operating Certificate and Certificate of Competency for regulated trades), Appendix A Zoning § 6.5 (impervious cover capped at 50 percent of an RSF lot, pool decks and pavers included), and Chapter 54 (coastal setback in Article XXII, marine turtle protection in Article XXIII, trees in Article XVIII).",
                p(f'The cities inside the county (Sarasota, Venice, North Port, Longboat Key) run their own building departments; the county handles everything else, including Siesta Key, Casey Key, Osprey, Nokomis, Laurel, South Venice, Englewood north of the county line and the unincorporated neighborhoods east of the city. Each office has a page on the {link("/permits/", "permit hub")}.'))
    body += sec("Permits and portals", table(["Office", "Portal", "Phone", "Page"], [
        ["Sarasota County Building (1001 Sarasota Center Blvd; 4000 S. Tamiami Trail, Venice)", "Accela Citizen Access, building.scgov.net", "(941) 861-5000", link("/permits/sarasota-county/", "County")],
        ["City of Sarasota Development Services", "FTG portal, ftgportal.sarasotafl.gov", "(941) 263-6480 (verify)", link("/permits/city-of-sarasota/", "City")],
        ["City of Venice Building and Engineering", "eTRAKiT, trakit.venicegov.com", "(941) 882-7400 (verify)", link("/permits/venice/", "Venice")],
        ["City of North Port Building Division", "Click2Gov", "(941) 429-7044", link("/permits/north-port/", "North Port")],
        ["Town of Longboat Key Planning, Zoning & Building", "Town portal; 501 Bay Isles Rd", "(941) 316-1999", link("/permits/longboat-key/", "Longboat Key")]],
        "Checked September 10, 2026; phone numbers marked verify were not confirmed on an official page"))
    body += sec("Flood zones, the 50% rule and the setback line",
                p(f'The barrier islands (Longboat Key, Lido and St. Armands, Siesta Key, Casey Key, Manasota Key) and the bayfront are in FEMA Special Flood Hazard Areas: AE across most of the islands and VE on the Gulf-facing rows. The NFIP 50 percent rule limits improvements to a building to half its market value before full flood compliance is triggered; the Sarasota County Property Appraiser explains the calculation (improvement value from the tax roll times 1.2, halved, or a private appraisal) and FEMA guidance excludes site improvements such as driveways, pools and landscaping from the count. Sarasota County\'s Gulf Beach Setback Line (Code Chapter 54, Article XXII) prohibits construction seaward of the line without a coastal setback variance from the County Commission, and pools, spas and pool decks are treated as structures for that purpose. Full explanation on {link("/permits/flood-zones-50-percent-rule/", "flood zones and the 50% rule")}.'))
    body += sec("Sea turtle lighting", p(f'Chapter 54, Article XXIII of the county code and the Town of Longboat Key\'s Chapter 100 require, from May 1 to October 31, that artificial light visible from the beach use long-wavelength (560 nm or more) bulbs in fully shielded, downward-directed fixtures. Article XXV covers the Venice beach area. The county\'s Sea Turtle Protection Program answers questions at (941) 861-5000. Fixture guidance is on {link("/permits/sea-turtle-lighting/", "sea turtle lighting")}.'))
    body += sec("Soils and water table", p("The USDA Natural Resources Conservation Service maps most of the county's flatwoods as Myakka fine sand (Florida's state soil), EauGallie, Immokalee, Oldsmar and Wabasso: very deep, poorly to very poorly drained sands with a seasonal high water table within 10 inches of the surface for two to six months a year. The keys are beach sand and fill over shell. For hardscape this means compacted base in lifts, proof-rolled subgrade, geotextile where sand pumps, and drainage that actually leaves the lot. The Web Soil Survey (websoilsurvey.sc.egov.usda.gov) maps any parcel."))
    body += sec("Salt and storm exposure", p("Ian in September 2022 and Helene and Milton in September and October 2024 pushed surge across the islands; Helene measured 6.68 feet on Longboat Key. Salt reaches concrete and stone from Gulf spray, brackish canal and bay water, and salt-chlorinated pools. The coastal hub covers the mechanisms and the maintenance intervals."))
    body += sec("Communities with architectural review", p("Palmer Ranch and its sub-associations (Prestancia, Turtle Rock, Stoneybrook, Deer Creek, Huntington Pointe, Isles of Sarasota, Sandhill Preserve, Esplanade), Wellen Park and the West Villages (Islandwalk, Grand Palm, Gran Paradiso, Renaissance, Sarasota National), Venetian Golf & River Club, Boca Royale, Plantation, Heron Creek, Skye Ranch, Laurel Oak, The Meadows, Villagewalk, Bay Isles, Longboat Key Club, Country Club Shores and most Siesta Key condominiums require ARC or board approval for driveway, patio and pool deck changes. Guides on " + link("/hoa/", "HOA and ARC") + "."))
    body += sec("Seasonality", p("January through April is the peak for both population and demand; the county's population rises past 570,000 in winter. June through September brings 6 to 9 inches of rain a month and afternoon storms, and many owners are away. Hurricane season runs June 1 to November 30. Scheduling, cure protection and remote project management are all built around that calendar."))
    body += sec("Localities in Sarasota County", ul([f'{city_link(c)}: {CITIES[c]["housing"]}.' for c in TIER1]))
    body += reviewed("September 10, 2026")
    return {"route": "/areas/sarasota-county/", "title": "Sarasota County: Permits, Flood Zones, Soils & HOAs", "meta_description": "Sarasota County hub for concrete and pavers: the five permit offices and portals, the 50% impervious cap, flood zones and the Gulf Beach Setback Line, turtle lighting, Myakka sands, storm history and ARC communities.",
            "h1": "Sarasota County: the rules, the ground and the communities behind every hardscape estimate", "kicker": "County hub",
            "lede": "Five permit offices, one county code, a water table under 10 inches for months, and a coast that floods. This page is the reference the locality pages point back to.",
            "breadcrumbs": [("Home", "/"), ("Areas", "/areas/"), ("Sarasota County", None)], "body_html": body}


def charlotte_county():
    body = facts([("Population", "223,430 (Florida EDR, April 2025)"), ("Permit office", "Community Development, 18500 Murdock Circle, Port Charlotte"), ("Flatwork rule", "All slabs, pavers included, require a permit and inspections"), ("NOC threshold", "$5,000")])
    body += cap("What does Charlotte County require differently from Sarasota County?",
                "Charlotte County permits every piece of residential flatwork, structural or not, pavers included, with a site plan, an Affidavit for Accessory Structures where relevant, and a Notice of Commencement recorded before the first inspection when the contract exceeds $5,000. Fees published on the county's page include a $22 zoning review, a $310 line-and-grade fee (or $90 for right-of-way work) and a building fee of 0.004 times valuation over $50,000.",
                p(f'The county also requires termite treatment for flatwork within a foot of a structure and may require an occupation-of-easement approval from Real Estate Services when pavers cross an easement. A driveway located only in the right-of-way is permitted as a ROW permit instead. Licenses accepted for driveway and slab permits include Local Concrete Masonry. Details and links on {link("/permits/charlotte-county/", "the Charlotte County permit page")}.'))
    body += sec("Localities served in Charlotte County", ul([f'{city_link(c)}: {CITIES[c]["housing"]}.' for c in TIER2] + ["Englewood south of the county line and the Charlotte half of Manasota Key are covered on the " + city_link("englewood", "Englewood page") + ".", "Punta Gorda is 41 miles from Sarasota, outside the radius, and is served through Lakewood Ranch Concrete."]))
    body += sec("Ground and water", p("The Port Charlotte grid was platted by General Development Corporation from the 1950s to the 1980s on Myakka and Immokalee sands with roadside swales for drainage; many lots were never graded to modern standards, so a driveway crossing has to keep the swale flowing. Rotonda West sits inside a canal ring; Placida and Cape Haze are filled waterfront lots on Lemon Bay and Gasparilla Sound. Flood zones are AE along the canals and harbor and AE or VE on the Lemon Bay and Gulf-facing edges."))
    body += sec("Storm history", p("Ian made landfall in Lee County on September 28, 2022 with surge and wind that reached Charlotte Harbor and the Englewood coast; Helene and Milton in 2024 brought surge to Manasota Key and the Cape Haze peninsula. Salt in the base and lifted edge restraint are the common paver findings; slabs that sat under salt water are sounded for voids before anyone resurfaces them."))
    body += sec("Communities", p("Rotonda West Association enforces deed restrictions on driveway and exterior changes across the circle; Riverwood, Heritage Oak Park and the South Gulf Cove community associations review hardscape; Boca Royale and the Cape Haze golf communities have ARC review. Submit the county permit application and the association application in parallel; the association usually wants the permit number."))
    body += reviewed("September 10, 2026")
    return {"route": "/areas/charlotte-county/", "title": "Charlotte County Coast: Permits, Canals & Storm Rules", "meta_description": "Charlotte County hub for pool decks, driveways and repair in Port Charlotte, Rotonda West and Placida: the all-flatwork permit rule, fees, NOC threshold, GDC swales, canal flood zones and storm history.",
            "h1": "The Charlotte County coast: what changes south of the county line", "kicker": "County hub",
            "lede": "Port Charlotte, Rotonda West, Placida, Grove City and Cape Haze, where every slab is permitted, the swales drain the grid, and Lemon Bay sets the flood zone.",
            "breadcrumbs": [("Home", "/"), ("Areas", "/areas/"), ("Charlotte County", None)], "body_html": body}


# ------------------------------------------------------------------ TIER 1 LOCALITIES
def sarasota():
    faq = [("Which neighborhoods are inside Sarasota city limits versus the county?", "Downtown, the Rosemary District, Laurel Park, Gillespie Park, Indian Beach and Sapphire Shores, Arlington Park, Southside Village, Harbor Acres, Bird Key, Lido Key and St. Armands are city. Siesta Key, Gulf Gate Estates, Palmer Ranch, Fruitville, Bee Ridge and The Meadows are unincorporated county. The city's FTG permit portal or the Property Appraiser's map settles a specific address."),
           ("Does the city require a permit to replace a driveway?", "For the apron between the sidewalk and the street, yes: that strip is city right-of-way. For the private portion the city reviews it as flatwork through the FTG portal; confirm the current form with Development Services, because the site could not verify the exact category on the city's page."),
           ("How old are west-of-Trail driveways?", "Many date from the 1950s and 1960s, poured at 3 to 3.5 inches on raw sand with no joints. They've outlived their design and the fix is replacement on a compacted base, not another overlay."),
           ("Is Lido Key in a VE zone?", "The Gulf-facing rows are; most of the interior of Lido and St. Armands is AE. The Property Appraiser's property search shows the zone for any parcel."),
           ("What about the Ringling-era homes?", "Mediterranean Revival houses from the 1920s in Indian Beach, Sapphire Shores and Harbor Acres often have original terrazzo and coquina hardscape; the architectural concrete and stone pages are the right fit, and the city's historic preservation rules apply to designated properties.")]
    intro = cap("What does hardscape work look like inside the City of Sarasota?",
                "A city of 58,279 people (Florida EDR, April 2025) with three markets in one: 1920s to 1960s homes west of the Trail on sand and fill, mid-century ranches east of it, and the bayfront keys (Lido, St. Armands, Bird Key) in AE and VE zones. The City of Sarasota, not the county, issues permits inside the limits, and the apron at the street is city property.",
                p("The city's own permit portal (ftgportal.sarasotafl.gov) handles review; Development Services is the office. Grand oaks are protected by both the city (trunks 4 inches and up) and the county, which shapes where a driveway or walk can go in the older neighborhoods. Impervious cover and setbacks follow the city's zoning code rather than the county's 50 percent RSF rule."))
    sections = [
        ("Neighborhoods and what they need", table(["Area", "Housing", "Typical hardscape work"], [
            ["West of the Trail (Southside Village, Cherokee Park, Harbor Acres)", "1940s to 1960s, heavily renovated", "Driveway replacement, paver entries, honed or marble lanai floors"],
            ["Indian Beach, Sapphire Shores, Bayou Oaks", "1920s Mediterranean Revival to 1950s ranch", "Coquina and terrazzo-compatible walks, architectural concrete, bayfront pool decks in AE"],
            ["Downtown, Rosemary District, Laurel Park, Gillespie Park", "Bungalows, condos, new townhomes", "Small courtyard patios, alley driveways, permeable pavers on tight lots"],
            ["Arlington Park, Alta Vista, Paver Park", "1950s to 1970s block homes", "Driveway tear-outs, lanai slabs, pool deck resurfacing"],
            ["Lido Key, St. Armands, Bird Key", "1950s to 1970s waterfront, rebuilds", "Travertine and marble pool decks, elevated slabs, turtle-compliant lighting on Lido"],
            ["Gulf Gate (city portion) and Southgate", "1960s ranches", "Original driveways failing; see the Gulf Gate page"]], "Sarasota city areas, 2026")),
        ("Ground and water", p("East of US-41 the lots sit on Myakka and EauGallie fine sands with a wet-season water table under 10 inches; base compaction in lifts and positive drainage are the whole game. West of the Trail and on the keys the ground is fill and shell over sand, drains fast, and carries salt. Bird Key and Lido Key are in AE with VE on the Gulf face; Ringling Causeway access means truck timing around the bridge.")),
        ("Rules that bite in the city", ul(["Apron replacement needs a city permit because the strip between sidewalk and curb is city right-of-way.", "Retaining walls over 3.5 feet need a permit.", "Trees with trunks 4 inches and up need a permit to remove or root-prune; walks bend around them.", "Lido Key falls under sea turtle lighting rules from May 1 to October 31.", "Historic districts and designated properties have design review."])),
        ("A worked example", p("A 1958 block ranch in Arlington Park with a 3.5-inch, 480-square-foot driveway cracked into eight pieces and an apron heaved by a live oak root. The scope: remove the driveway and apron, protect the oak's critical root zone with a bridge slab over the root instead of cutting it, 4 inches of compacted base, 4-inch 4,000 PSI fiber concrete with #3 bar, joints at 8 feet, and the apron poured to the city detail under the apron permit. Planning band for that job in September 2026: $6,500 to $9,000.")),
    ]
    return city_page("sarasota", "Concrete & Pavers in Sarasota, FL – City Permits, Keys, Cost", "Concrete and paver work inside the City of Sarasota: which neighborhoods are city vs county, the apron permit rule, Lido and Bird Key flood zones, oak protection, mid-century driveways and a worked example with a 2026 price band.",
                     "Concrete and pavers in the City of Sarasota, from Indian Beach to Bird Key", "The city issues its own permits, owns the apron at the street and protects every oak over 4 inches; the keys add AE and VE zones and turtle lighting.", intro, sections, faq)


def fruitville():
    faq = [("Does The Meadows require approval for a patio extension?", "Yes. The Meadows Community Association reviews exterior changes, and the individual condominium and homeowner associations inside The Meadows have their own review. Submit to the sub-association first; it forwards or requires the master's approval."),
           ("Why do The Meadows and Fruitville behave differently from the keys for drainage?", "The keys are sand and fill that drain fast and carry salt. Fruitville and Bee Ridge sit on Myakka, EauGallie and Immokalee sands with a hardpan layer and a seasonal water table under 10 inches; water sits, the base pumps fines, and slabs settle. Base compaction and drainage matter more here than salt does."),
           ("Which permit office covers Fruitville?", "Sarasota County Building at 1001 Sarasota Center Boulevard, through the Accela portal. The area is unincorporated."),
           ("Are there flood zones inland?", "AE pockets along Phillippi Creek and near the Celery Fields; most lots are X. The Property Appraiser's map shows each parcel."),
           ("Is the Fruitville corridor growing?", "Yes, east toward I-75 and Lorraine Road with new subdivisions on filled land; new-construction driveways and lanai extensions on builder slabs are the common request.")]
    intro = cap("What is hardscape work like in Fruitville, Bee Ridge and The Meadows?",
                "This is unincorporated Sarasota County east of the city, permitted by the county through Accela, on flatwoods sands with a shallow seasonal water table and no salt to speak of. The housing runs from 1950s Sarasota Springs and 1960s Kensington Park to 1970s and 80s The Meadows and 2000s subdivisions along Fruitville Road, so the work is driveway and lanai replacement on settled slabs and extensions on builder-grade concrete.",
                p("The county's rules apply in full: culvert or right-of-way use permit for anything at the road, the 50 percent impervious cap on RSF lots, the county tree ordinance for grand oaks, and the $7,500 residential exemption process for small jobs with documentation."))
    sections = [
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Sarasota Springs, Kensington Park", "1950s to 1960s block homes", "Original driveways at 3.5 in., no joints; replacement on compacted base"], ["The Meadows", "1970s to 80s villas and homes, golf community", "Lanai extensions, paver entries, pool deck resurfacing; master and sub-association review"], ["Bee Ridge, Sarasota Springs east", "1970s to 90s ranches on larger lots", "Slabs and pads, driveway widening, boat and RV pads"], ["Fruitville corridor (Laurel Oak, Oak Ford, newer subdivisions)", "1990s to 2020s", "Builder-slab upgrades, paver driveways, outdoor kitchens; ARC review"]], "Fruitville and Bee Ridge areas")),
        ("Ground and water", p("The USDA maps this area as Myakka, EauGallie and Immokalee fine sands, poorly drained, with a spodic hardpan that keeps water near the surface in the wet season. Concrete poured on raw sand here settles at the garage and cracks across long panels; the fix is 4 to 6 inches of compacted base, proof-rolled subgrade and a slope that gets water to a swale or a drain. Well water is common east of I-75, so irrigation rust on driveways is a regular call.")),
        ("A worked example", p("A 1978 home in The Meadows with a 12-by-24 lanai slab that had settled 3/4 of an inch toward the sliders. The slab was sound but the pitch was wrong, so it came out: a 4-inch compacted limerock base, a new 4-inch slab pitched 1/8 inch per foot to a new floor drain at the cage edge, cage re-anchored. Master and sub-association approvals took three weeks; the county reviewed it as flatwork. Planning band in September 2026: $4,000 to $6,000.")),
    ]
    return city_page("fruitville-bee-ridge", "Concrete & Pavers in Fruitville & Bee Ridge, FL – County Rules", "Driveways, lanai slabs, pads and pavers in Fruitville, Bee Ridge, The Meadows, Kensington Park and Sarasota Springs: county permits via Accela, flatwoods sands with a shallow water table, HOA review and a 2026 worked example.",
                     "Concrete and pavers in Fruitville, Bee Ridge and The Meadows", "Unincorporated east Sarasota: county permits, a water table that sits, 1950s to 2020s housing, and associations that review every extension.", intro, sections, faq)


def gulf_gate():
    faq = [("Why are 1960s Gulf Gate driveways failing now?", "They were poured at 3 to 3.5 inches on raw sand with no control joints and no base, sixty years ago. The sand under them has been pumping fines every wet season since, the slabs have settled at the garage and cracked in the middle, and the overlays some owners added are delaminating. The fix is replacement on a compacted base."),
           ("Is Gulf Gate in the city or the county?", "Gulf Gate Estates and most of South Sarasota are unincorporated county; a strip along US-41 and Gulf Gate Drive is city. The Property Appraiser's map shows which."),
           ("Is Gulf Gate in a flood zone?", "Interior blocks are X; lots toward Little Sarasota Bay and along Phillippi Creek are AE."),
           ("What about the concrete-block homes' pool decks?", "Most are original 1960s to 70s slabs with cool-deck overlays applied in the 1990s. Sounding decides whether a new overlay works or the deck comes out; the resurfacing page has the tests."),
           ("How far is Gulf Gate from Siesta Key?", "A mile across the Stickney Point bridge; the same crew works both, but the rules differ: Gulf Gate is inland county, Siesta is barrier island.")]
    intro = cap("What is the hardscape story in Gulf Gate?",
                "Gulf Gate Estates (10,083 people in the 2020 Census) and South Sarasota are 1960s and 1970s block homes on quarter-acre lots, most still on their original driveway, walk and pool deck. The soil is Myakka fine sand with a shallow water table, the jurisdiction is Sarasota County for most streets, and the demand is driveway replacement, pool deck resurfacing or replacement, and repair.",
                p("The county permits through Accela; anything at the road needs a right-of-way use permit. Interior lots are Zone X; the blocks toward Little Sarasota Bay and Phillippi Creek are AE. There's no master HOA in Gulf Gate Estates, which makes it one of the few places in the area where an owner can change a driveway without an ARC packet."))
    sections = [
        ("What's under the driveways", p("Original Gulf Gate driveways were poured thin on sand that was never compacted. Sixty wet seasons of water moving fines out from under them have left voids at the garage and at the street. Sounding with a hammer finds them; a level shows the drop. Replacing the slab without compacting the base in lifts just restarts the clock.")),
        ("Typical projects", table(["Project", "What's usually found", "Approach"], [["Driveway replacement", "3.5-in. slab, no joints, settled at garage", "Remove, 4 to 6 in. compacted base, 4-in. 4,000 PSI, joints at 8 ft, ROW permit"], ["Pool deck", "1960s slab with a 1990s cool-deck overlay, hollow at the coping", "Sound it; overlay if solid, replace if not"], ["Front walk", "Cracked 3-ft walk, root heave from a 1960s oak", "Reroute or bridge the root; county tree rules"], ["Lanai", "Settled slab pitched toward sliders", "Replace with drain"]], "Gulf Gate patterns")),
        ("A worked example", p("A 1972 home two blocks from Little Sarasota Bay with a 780-square-foot pool deck on Myakka fine sand. The original slab was spalled at the coping and hollow across a third of the deck; an overlay would have failed. The deck came out, 4 inches of base went in, a new 4-inch textured deck was poured to two deck drains, and the cage was re-anchored. Eight working days. September 2026 planning band: $7,500 to $11,000.")),
    ]
    return city_page("gulf-gate", "Concrete & Pavers in Gulf Gate, FL – 1960s Driveways & Decks", "Concrete driveways, pool decks and repair in Gulf Gate Estates and South Sarasota: why 1960s slabs on sand are failing, county permits, no master HOA, Zone X vs AE, and a 2026 worked example.",
                     "Concrete and pavers in Gulf Gate, where the 1960s driveways are due", "Original slabs on uncompacted sand, sixty wet seasons later. County permits, no master HOA, and a mile from Siesta Key's bridge.", intro, sections, faq)


def siesta_key():
    faq = [("What flood zone is most of Siesta Key in?", "AE, with VE along the Gulf-facing rows. Both are Special Flood Hazard Areas; VE adds wave action and the strictest construction rules. The Property Appraiser's map shows the zone and the base flood elevation for any parcel."),
           ("Which office handles permits on Siesta Key: county or city?", "Sarasota County. Siesta Key is unincorporated; the county's Building division and Accela portal handle every permit, and the county's coastal setback and turtle lighting codes apply."),
           ("Does a new pool deck count toward the 50% rule?", "No. FEMA's substantial-improvement guidance and the county's practice exclude site improvements such as pool decks, driveways and landscaping from the calculation; only work on the building counts. The county decides case by case, so the permit application still documents it."),
           ("Can lighting be added to a paver deck on Siesta Key?", "Yes, with long-wavelength amber or red bulbs in fully shielded, downward-directed fixtures wherever the beach can see them, May 1 to October 31 under county code Chapter 54, Article XXIII."),
           ("What did Helene and Milton do to hardscape here?", "Surge pushed water and sand into first floors within 150 yards of the beach and left muddy waterlines 2.5 feet up walls. On hardscape it washed out joint sand, lifted spiked edge restraint, deposited salt in bases and, in places, undermined slabs. The post-storm page has the sequence.")]
    intro = cap("What makes Siesta Key hardscape different?",
                "Everything on the island is in a flood zone, most of it AE and the Gulf rows VE; the Gulf Beach Setback Line runs along the beach; turtle lighting rules apply from May 1 to October 31; and the 2024 surge from Helene and Milton reached most streets. Jurisdiction is Sarasota County. The island had 5,454 year-round residents in 2020 and many times that in season.",
                p("The work is pool decks first (travertine, shellstone, porcelain and concrete pavers over rebuilt bases), then post-storm paver restoration, sealing on an 18-month cycle, and elevated-home slabs and driveways under new construction. Every estimate starts with the FEMA zone and the base flood elevation written on the scope."))
    sections = [
        ("Rules on the island", table(["Rule", "What it means for hardscape", "Page"], [["FEMA AE/VE", "Site improvements outside the 50% calculation; VE limits what goes under an elevated home", link("/permits/flood-zones-50-percent-rule/", "Flood zones")], ["Gulf Beach Setback Line", "Pool decks seaward of the line need a coastal setback variance from the County Commission", link("/permits/flood-zones-50-percent-rule/", "Setback line")], ["Marine Turtle Protection (Ch. 54 Art. XXIII)", "Amber/red shielded fixtures visible from the beach, May 1 to Oct 31", link("/permits/sea-turtle-lighting/", "Turtle lighting")], ["Condominium boards", "Deck replacement phased, reserve-funded, board-approved", link("/hoa/barrier-island-condos/", "Condo guide")]], "Siesta Key hardscape rules")),
        ("Ground, salt and surge", p("The island is quartz sand and fill over shell. It drains fast and carries salt to every surface: Gulf spray on the beach side, bay water on the canals, and salt-chlorinated pools in between. Paver sealer lasts 18 to 24 months here, not 3 years; travertine coping on a salt pool is sealed annually. After a surge the base under a paver field holds salt and may hold voids, so the sequence is drain, sound, rebuild, rinse, reset, then sand and seal.")),
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Siesta Village, Beach Road, Midnight Pass north", "1950s cottages, condos, elevated rebuilds", "Condo pool decks, elevated-home slabs, turtle-compliant lighting"], ["Canal streets (Sabal Drive, Palm Island, Bayou Louise)", "1960s to 80s waterfront homes", "Travertine pool decks, paver driveways, post-storm resets"], ["Crescent Beach, Stickney Point, Turtle Beach", "Condos and 1970s homes", "Board-approved deck replacement, sealing"]], "Siesta Key areas")),
        ("A worked example", p("A 1968 canal home off Midnight Pass Road with a 640-square-foot paver pool deck lifted at the seawall side by the October 2024 surge. After three weeks of drying the field was lifted in sections, the base sounded (two voids), rebuilt in lifts and flushed, a concrete curb replaced the spiked restraint at the seawall, the original travertine was rinsed and reset, polymeric sand installed on a dry day, and sealing scheduled 30 days later. Documented with before-and-after photos for the insurer. Planning band, dated September 2026: $6,000 to $9,500.")),
    ]
    return city_page("siesta-key", "Concrete & Pavers on Siesta Key, FL – Flood Zone, Permits, Cost", "Pool decks, paver restoration and sealing on Siesta Key: AE and VE zones, the 50% rule, the Gulf Beach Setback Line, turtle lighting, county permits, 2024 surge lessons and a worked example with a 2026 price band.",
                     "Concrete and pavers on Siesta Key, where every lot is in a flood zone", "County jurisdiction, AE and VE zones, the setback line, turtle lighting and a coast that surged twice in 2024. Pool decks first, restoration second, sealing every 18 months.", intro, sections, faq)


def palmer_ranch():
    faq = [("What soil is under Palmer Ranch homes?", "Myakka and Oldsmar fine sands, graded and filled during development from the late 1980s on. Fill compacts better than native flatwoods sand, but the wet-season water table is still shallow, so base compaction and drainage decide whether a driveway settles."),
           ("Does Palmer Ranch require ARC approval for a paver driveway?", "Yes, twice in most cases: the sub-association (Prestancia, Turtle Rock, Stoneybrook, Deer Creek and the rest) and, for many changes, the Palmer Ranch Master Property Owners Association. The HOA guide covers the packet."),
           ("Which permit office covers Palmer Ranch?", "Sarasota County, through the Accela portal; Palmer Ranch is unincorporated."),
           ("Why is driveway replacement so common here?", "Homes built from 1990 to 2010 came with builder-grade broom driveways that are now 15 to 35 years old and were poured fast. Settlement at the garage, spalling from sprinklers and cracks across long panels are the usual findings."),
           ("Are pool decks the same story?", "Mostly. Original cool-deck overlays from the 1990s are at end of life; sounding decides overlay versus replacement, and travertine or paver replacement is the common choice.")]
    intro = cap("What is hardscape work like in Palmer Ranch?",
                "Palmer Ranch is a 10,000-acre master-planned community in unincorporated Sarasota County, developed since 1986 under the Palmer Ranch Master Property Owners Association with dozens of sub-associations, each with its own architectural review. Houses date from 1990 to 2010 and are now at driveway and pool deck replacement age.",
                p("The county issues permits; the associations approve materials and colors. Lots are graded fill over Myakka and Oldsmar sands, mostly Zone X with AE along the lakes and preserves. The requests are paver driveways in colors the ARC accepts, concrete driveway replacement, travertine pool decks and lanai extensions."))
    sections = [
        ("Communities and review", table(["Community", "Built", "Review"], [["Prestancia", "1990s", "Prestancia HOA plus master"], ["Turtle Rock", "1990s to 2000s", "Sub-association plus master"], ["Stoneybrook Golf & CC", "1990s", "Sub-association plus master"], ["Deer Creek, Huntington Pointe", "1990s", "Sub-association"], ["Isles of Sarasota, Sandhill Preserve, Esplanade", "2000s to 2010s", "Sub-association plus master; strict paver color lists"]], "Palmer Ranch sub-associations, partial list") + p(f'The {link("/hoa/palmer-ranch/", "Palmer Ranch ARC guide")} explains what goes in the packet and the typical sequence.')),
        ("Ground and water", p("Graded fill over flatwoods sand. Better bearing than native ground, still a shallow water table in the wet season and lakes that set the flood zone on the perimeter lots. Builder driveways were poured with little base; replacement is 4 to 6 inches of compacted base and a 4-inch 4,000 PSI slab with joints at 8 to 10 feet, or vehicular pavers on 6 inches of base.")),
        ("A worked example", p("A 1996 home in Turtle Rock with a 640-square-foot builder driveway cracked at the garage and stained by well-water irrigation. The owner chose pavers: demolition, 6 inches of compacted base in lifts, herringbone field in an ARC-approved tan blend with a charcoal border, concrete curb at the street, sprinkler heads redirected. Sub-association and master approvals took four weeks; county ROW use permit for the apron. Band as of September 2026: $10,000 to $14,000.")),
    ]
    return city_page("palmer-ranch", "Concrete & Pavers in Palmer Ranch, FL – ARC, Driveways, Decks", "Driveway and pool deck replacement in Palmer Ranch: 1990 to 2010 homes at replacement age, master and sub-association ARC review, county permits, graded fill over Myakka sand, and a 2026 worked example.",
                     "Concrete and pavers in Palmer Ranch, where 1990s driveways meet ARC review", "Dozens of sub-associations under one master association, county permits, graded fill over flatwoods sand, and a housing stock built from 1990 to 2010.", intro, sections, faq)


def longboat_key():
    faq = [("How high was the storm surge on Longboat Key during Helene and Milton?", "Helene's surge measured 6.68 feet on Longboat Key in September 2024, flooding ground-floor cottages on Gulf of Mexico Drive with about 3 feet of water; Milton followed two weeks later and pushed the Helene debris piles into other houses. Hardscape on the island was under salt water on both occasions."),
           ("What bridges and travel times connect Sarasota to Longboat Key?", "From Sarasota, the John Ringling Causeway to St. Armands Circle and up Gulf of Mexico Drive: 25 to 40 minutes. From the north, Cortez Road and the Longboat Pass bridge. Both routes have drawbridges; deliveries are timed."),
           ("Does Bay Isles or the Longboat Key Club require architectural review for pavers?", "Yes. Bay Isles Association, the Longboat Key Club communities, Country Club Shores and most condominiums review driveway and deck changes, and the Town requires its own permit on top."),
           ("Does the Town of Longboat Key require a permit for a paver driveway or pool deck?", "The Town's Planning & Zoning division reviews at-grade driveways, decks and patios as exceptions under its zoning criteria, and every permit on a property subject to substantial-improvement review goes through that check. The Town Hall at 501 Bay Isles Road, (941) 316-1999, is the office."),
           ("Which county does Longboat Key belong to?", "Both. The Town straddles the Sarasota-Manatee line (2,663 residents in the Sarasota part and 4,782 in the Manatee part, Florida EDR April 2025) but issues its own permits island-wide, so the county line doesn't change the process.")]
    intro = cap("What is hardscape work like on Longboat Key?",
                "A 10-mile barrier island with its own town government, 7,445 year-round residents split across Sarasota and Manatee counties, AE and VE flood zones end to end, turtle lighting rules under Town Ordinance 2021-01, and a 6.68-foot surge in September 2024. The Town of Longboat Key issues every permit, and community and club associations review most exterior changes.",
                p("Demand is travertine, marble and porcelain pool decks on estate lots, sealed paver driveways, post-storm restoration, and elevated-home slabs under new construction. Sealer life here is 18 to 24 months; coping on salt pools is sealed annually; every base is built to be rinsed and reset after the next surge."))
    sections = [
        ("Town rules", table(["Rule", "What it means", "Page"], [["Town permits island-wide", "One office for both county halves; at-grade driveways, decks and patios reviewed by Planning & Zoning", link("/permits/longboat-key/", "Longboat Key permits")], ["Substantial improvement / damage (Code Ch. 154)", "Every permit on a property in the review is checked against the 50% threshold; site work is excluded from the count but still documented", link("/permits/flood-zones-50-percent-rule/", "Flood zones")], ["Marine Turtle Protection (Ch. 100, Ord. 2021-01)", "Bulbs at 560 nm or longer, fully shielded fixtures, May 1 to Oct 31; Code Enforcement tests bulbs", link("/permits/sea-turtle-lighting/", "Turtle lighting")]], "Longboat Key rules")),
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Bay Isles, Longboat Key Club, Harbourside", "1980s to 2000s estates and villas", "Travertine and marble pool decks, sealed paver driveways, ARC review"], ["Country Club Shores, Sleepy Lagoon, Emerald Harbor", "1960s to 80s canal homes", "Deck replacement after surge, driveway pavers, coping"], ["Longbeach Village (north end)", "Cottages, elevated rebuilds", "Elevated-home slabs, small decks, turtle-compliant lighting"], ["Gulf of Mexico Drive condos", "1970s to 90s", "Board-approved phased deck replacement"]], "Longboat Key areas")),
        ("Ground and salt", p("Beach sand and dredged fill. Bases drain quickly and hold salt after a surge; edge restraint set in sand lifts. The standard here is a concrete curb at every exposed edge, geotextile under the base, a fresh-water flush after any flood, and porcelain or dense concrete pavers around salt pools unless the owner commits to annual travertine sealing.")),
        ("A worked example", p("A 1984 canal home in Country Club Shores with a 900-square-foot travertine pool deck that stood in 2 feet of salt water in October 2024. Insurer photos first, three weeks of drying, then the field was lifted, two voids at the seawall side were filled and compacted, the base was flushed, the travertine rinsed and reset, a concrete curb replaced the plastic restraint, and coping was resealed. Town permit documented the site work against the substantial-damage file. Planning band in September 2026: $8,500 to $13,000.")),
    ]
    return city_page("longboat-key", "Concrete & Pavers on Longboat Key, FL – Town Permits & Flood", "Pool decks, paver driveways, sealing and storm restoration on Longboat Key: Town permits island-wide, substantial-improvement review, Ordinance 2021-01 turtle lighting, the 6.68-foot 2024 surge, and a 2026 worked example.",
                     "Concrete and pavers on Longboat Key, under one town government and two counties", "Town permits for both halves of the island, AE and VE zones end to end, 560 nm lighting, and a coast that stood in salt water twice in 2024.", intro, sections, faq)


def osprey():
    faq = [("Is Osprey inside a city or unincorporated Sarasota County?", "Unincorporated county. Permits go through Sarasota County Building and the Accela portal; the county's coastal setback and turtle lighting codes apply on Casey Key."),
           ("What is the North Casey Key Conservation District?", "A special district created by Florida law (Laws of Fla. ch. 70-937) and enforced by the county under Code Chapter 54, Article XXVI, with additional construction rules on the north end of Casey Key. Hardscape near the beach is reviewed under it."),
           ("Do The Oaks and Southbay require architectural review?", "Yes. The Oaks Club communities and Southbay Yacht & Racquet Club review driveway, deck and lighting changes; Rivendell, Willowbend and Park Trace have HOA review too."),
           ("How do trucks reach Casey Key?", "By the Blackburn Point swing bridge, one lane and weight-limited, or from the south via Albee Road. Deliveries are staged and timed."),
           ("Is Osprey in a flood zone?", "Inland Osprey is mostly X with AE along Little Sarasota Bay and the creeks; Casey Key is AE and VE.")]
    intro = cap("What is hardscape work like in Osprey and on Casey Key?",
                "Osprey (6,729 people in the 2020 Census) is unincorporated county along US-41 between Sarasota and Venice, with The Oaks and Southbay estates on the bay side, 1980s to 2000s neighborhoods inland, and Casey Key, a narrow barrier island in AE and VE zones inside the North Casey Key Conservation District. Sarasota County permits everything.",
                p("Demand is high-end pool decks in travertine, marble and porcelain, paver driveways, and on Casey Key the full coastal set: setback line, turtle lighting, salt and surge restoration. Access to the key is by a one-lane swing bridge, which shapes how a job is staged."))
    sections = [
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["The Oaks (Bayside, Clubside), Southbay Yacht & Racquet Club", "1980s to 2000s estates, bayfront", "Travertine and marble pool decks, sealed paver driveways, ARC review"], ["Rivendell, Willowbend, Park Trace, Sorrento Woods", "1990s to 2000s", "Builder driveway upgrades to pavers, lanai extensions"], ["Casey Key", "Gulf-to-bay estates, cottages", "VE-zone decks, setback variances, turtle lighting, surge resets"], ["Bay Street, Osprey village", "1950s to 70s", "Driveway and walk replacement"]], "Osprey areas")),
        ("Ground and rules", p("Inland lots are Myakka fine sand; the key is beach sand and fill. County rules apply: right-of-way permits at the road, the 50 percent impervious cap on RSF lots, the coastal setback code and the turtle lighting article on Casey Key, and the conservation district's construction rules on the north end. Oscar Scherer State Park and the Legacy Trail border the area; nothing changes for hardscape, but access roads are shared with trail traffic.")),
        ("A worked example", p("A 2004 home in Rivendell with a 560-square-foot builder pool deck under a cage, spalled at the coping from a salt-chlorinated pool. Sounding found the slab solid, so the deck stayed: loose paste removed, coping replaced in travertine bullnose sealed with a penetrating product, and a light knockdown overlay across the field. HOA approval in two weeks; no county permit was needed for the overlay. September 2026 planning band: $5,500 to $8,000.")),
    ]
    return city_page("osprey", "Concrete & Pavers in Osprey & Casey Key, FL – Permits & Cost", "Pool decks, travertine, paver driveways and driveways in Osprey and on Casey Key: county permits, The Oaks and Southbay ARC review, the Casey Key conservation district, VE zones, swing-bridge staging and a 2026 worked example.",
                     "Concrete and pavers in Osprey and on Casey Key", "Bayfront estates, 1990s neighborhoods and a barrier island reached by a one-lane swing bridge, all permitted by Sarasota County.", intro, sections, faq)


def nokomis():
    faq = [("Which permit office serves Nokomis and Laurel?", "Sarasota County Building; both are unincorporated. The county's Venice office at 4000 South Tamiami Trail is the closer counter."),
           ("What makes pavers sink on a Nokomis lot?", "Water carrying fines out of the base: a downspout, a leaking irrigation line, or new-construction fill that was never compacted in lifts. East of I-75 the newer communities were built on imported fill, and settlement shows up in the first three years."),
           ("Do Toscana Isles, Bellacina and Talon Preserve require ARC approval?", "Yes; all the master-planned communities east of I-75 review exterior changes and keep paver color lists."),
           ("Is Nokomis on the coast?", "Nokomis Beach and Casey Key's south end are; most of Nokomis and all of Laurel are inland, with AE zones along Dona and Roberts bays and Shakett Creek."),
           ("What are the old neighborhoods like?", "Sorrento East, Sorrento South, Calusa Lakes and Mission Valley are 1970s to 90s homes on larger lots, often on well water, with original driveways and pool decks.")]
    intro = cap("What is hardscape work like in Nokomis and Laurel?",
                "Two markets in one unincorporated area: 1970s to 90s neighborhoods (Sorrento East, Calusa Lakes, Mission Valley) on Myakka sand and well water, and 2016 to 2024 production communities east of I-75 (Toscana Isles, Bellacina by Casey Key, Talon Preserve, Vicenza) built on imported fill with strict ARC review. Sarasota County permits both.",
                p("Nokomis had 3,808 residents and Laurel 9,184 in the 2020 Census, and the area east of the interstate has grown fast since. Demand is paver driveways and pool decks replacing builder concrete in the new communities, and driveway replacement, patio slabs and repair in the older ones."))
    sections = [
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Toscana Isles, Bellacina, Talon Preserve, Vicenza, Milano", "2016 to 2024 production homes", "Paver driveways and pool decks in ARC colors; lanai extensions"], ["Calusa Lakes, Sorrento East and South, Mission Valley", "1970s to 90s on larger lots", "Concrete driveway replacement, patio and lanai slabs, repair, rust from well water"], ["Nokomis Beach, Casey Key south end", "Waterfront", "Coastal decks, turtle lighting"], ["Laurel, Venice Hills", "1960s to 80s", "Driveway and walk replacement"]], "Nokomis and Laurel areas")),
        ("Ground and water", p("Native Myakka and Immokalee sands inland, imported fill in the new communities, and a wet-season water table that sits high in both. Fill placed in thick lifts by a developer settles for years; a paver driveway laid on it needs its own 6 inches of compacted base, not trust in the fill. Well water east of the interstate means iron staining on driveways and pool decks; the rust guide has the fix.")),
        ("A worked example", p("A 2019 home in Toscana Isles with a 520-square-foot builder broom driveway the owner wanted in pavers to match the neighbors. The ARC color list allowed three blends; the owner chose a light tan with a charcoal soldier course. Demolition, 6 inches of compacted base in three lifts over geotextile, herringbone field, poured curb where the field meets the street, irrigation heads redirected. Community approval took three weeks; county ROW permit for the apron. Planning band, dated September 2026: $8,500 to $12,000.")),
    ]
    return city_page("nokomis", "Concrete & Pavers in Nokomis & Laurel, FL – New Communities", "Paver driveways, pool decks, concrete driveways and patios in Nokomis and Laurel: county permits, ARC review in Toscana Isles and Bellacina, imported fill east of I-75, well-water rust, and a 2026 worked example.",
                     "Concrete and pavers in Nokomis and Laurel, old lots and new fill", "1970s neighborhoods on native sand and 2016-and-newer communities on imported fill, both permitted by Sarasota County and most reviewed by an ARC.", intro, sections, faq)


def venice():
    faq = [("What does the City of Venice require for pavers in the right-of-way?", "Approval of the city engineer, a right-of-way use authorization and a license agreement when the improvement doesn't match city standards, plus construction to the city detail. The private portion of a driveway is a building permit through eTRAKiT."),
           ("Is Venice Island in a flood zone?", "AE across the island and VE on the Gulf side; the mainland city is mostly X with AE along the Intracoastal and Curry Creek."),
           ("Does Venice have golf-cart rules?", "Golf carts are allowed on designated streets and paths in parts of the city and in communities like Venice Golf and Country Club and Wellen Park under their own rules; a second driveway or cart path needs ARC approval and, at the street, the city's right-of-way review."),
           ("What are the 1926 island homes like for hardscape?", "Nolen-plan Mediterranean Revival houses with original coquina and terrazzo details, narrow lots and mature trees. Walks and drives are designed around the trees and the historic district guidelines."),
           ("Does Wellen Park belong to Venice or North Port?", "Both. Wellen Park spans the city line; the Venice side is permitted by Venice and the North Port side by North Port, and the master association reviews all of it.")]
    intro = cap("What is hardscape work like in Venice?",
                "Venice (29,802 people, Florida EDR April 2025) issues its own permits through the Building department and eTRAKiT, and its Engineering department controls the right-of-way, where pavers need a license agreement. The island, laid out in 1926, is AE and VE; the mainland city is mostly X; and Wellen Park's villages inside the city line add ARC review.",
                p("Demand splits three ways: driveway tear-outs and lanai pavers on 1950s and 60s island homes, pool deck resurfacing and replacement in 1970s to 90s mainland neighborhoods, and builder-slab upgrades in Wellen Park. Turtle lighting rules apply on Venice's beaches under the county's Article XXV and the city's own lighting page."))
    sections = [
        ("City rules", table(["Rule", "What it means", "Page"], [["Building permits via eTRAKiT", "Flatwork inside the city reviewed by the Building department", link("/permits/venice/", "Venice permits")], ["Right-of-way (Code Ch. 62)", "Aprons and pavers at the street need engineering approval and often a license agreement", link("/permits/venice/", "Venice permits")], ["Historic district", "Venice Island's Nolen plan area has design guidelines", link("/areas/venice/", "this page")], ["Turtle lighting", "Red or amber LEDs in shielded fixtures on beach-visible properties, May 1 to Oct 31", link("/permits/sea-turtle-lighting/", "Turtle lighting")]], "Venice rules")),
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Venice Island, Historic Downtown, Gulf View", "1926 to 1960s", "Driveway replacement around trees, paver entries, historic-compatible walks"], ["Pinebrook, Jacaranda West, Capri Isles, Bird Bay", "1970s to 90s", "Pool deck resurfacing or replacement, driveway replacement"], ["Wellen Park (Venice side), Sawgrass, Stoneybrook at Venice", "1990s to 2020s", "Paver driveways and pool decks in ARC colors, lanai extensions"], ["Venice Gardens and South Venice", "County, not city", "See the South Venice page"]], "Venice areas")),
        ("Ground", p("Fill and shell over sand on the island; Myakka fine sand on the mainland; imported fill in Wellen Park. The island drains fast and carries salt; the mainland holds water in the wet season. Both need a compacted base and a slope that leaves the lot.")),
        ("A worked example", p("A 1962 island home on a 60-foot lot with a 440-square-foot driveway and apron cracked by a live oak. The city's engineering review required the apron in concrete to the city detail; the private portion went to pavers. The root was bridged rather than cut, the base was built in lifts, and the apron was poured under the right-of-way authorization. Building permit through eTRAKiT and the license agreement for the paver edge at the sidewalk took five weeks. Band as of September 2026: $7,500 to $10,500.")),
    ]
    return city_page("venice", "Concrete & Pavers in Venice, FL – City Permits & Wellen Park", "Driveways, pool decks and resurfacing in the City of Venice: eTRAKiT permits, right-of-way license agreements for pavers, Venice Island flood zones and historic guidelines, Wellen Park ARC review, and a 2026 worked example.",
                     "Concrete and pavers in Venice, from the 1926 island to Wellen Park", "A city that issues its own permits, controls its right-of-way with license agreements, and spans a barrier island, a mid-century mainland and a new master-planned edge.", intro, sections, faq)


def south_venice():
    faq = [("Where does South Venice end and the City of Venice begin for permits?", "The city line runs roughly along the Intracoastal and the northern edge of Venice Gardens; South Venice and Venice Gardens are unincorporated Sarasota County and permit through the county's Venice office at 4000 South Tamiami Trail. The Property Appraiser's map shows the jurisdiction for any parcel."),
           ("How old are Venice Gardens homes and what does that mean for driveways?", "Mostly 1950s to 1970s block homes with original driveways poured thin on sand. Replacement on a compacted base is the standard job; overlays on these slabs fail."),
           ("Are the lots on septic?", "Many South Venice lots are on septic and well. A drain field sets where a slab or pavers can go, and well water stains driveways with iron."),
           ("Is South Venice in a flood zone?", "AE along Lemon Bay, Alligator Creek and the Intracoastal; most interior lots are X."),
           ("Is there an HOA?", "South Venice Civic Association runs the beach ferry and boat ramp but isn't an architectural authority; Venice Gardens has voluntary associations. Most owners change a driveway with only the county permit.")]
    intro = cap("What is hardscape work like in South Venice and Venice Gardens?",
                "Unincorporated county south and east of the city: 15,283 people in South Venice and 7,328 in Venice Gardens (Census 2020), 1950s to 1980s block homes on small platted lots, many on septic and well, permitted by Sarasota County through the Venice office. The work is driveway replacement, repair, patio slabs and pads, with the drain field and the well as the constraints.",
                p("Little architectural review, straightforward county rules, and a lot of original concrete that has reached the end of its life. Salt exposure is limited to the lots on Lemon Bay and the Intracoastal."))
    sections = [
        ("What's on the lots", table(["Finding", "Cause", "Approach"], [["Driveway settled at the garage", "Uncompacted 1960s backfill", "Replace; compact the strip; dowel to apron"], ["Orange stains on the driveway", "Iron in well-water irrigation", "Redirect heads, oxalic cleaner, sealer"], ["Patio slab cracked in the middle", "No joints, 20-ft panel", "Replace with joints at 8 ft"], ["Shed pad sinking", "Precast blocks on sand", "Poured 4-in. pad on compacted base"], ["Drain field in the way", "Septic layout", "Site the slab or pavers clear of it; the county checks"]], "South Venice patterns")),
        ("Ground and water", p("Myakka fine sand with a shallow wet-season water table, Alligator Creek and Lemon Bay setting the AE zones, and septic systems that dictate where anything can be built. Concrete here wants a compacted base and a slope to a swale; pavers want the same base plus an edge that holds.")),
        ("The septic system decides where the slab goes", p("This is the constraint that catches people out here and in few other parts of the service area. A large share of South Venice lots run on a private well and an on-site septic system, and Florida's on-site sewage rules in Administrative Code Chapter 64E-6 keep both clear of new construction: a drain field has to stay a set distance from a potable well, from the property line, and from any structure placed over it. A slab poured across a drain field is less a permit problem than a plumbing problem you have bought, because the field needs air, water has to reach it, and a truck has to be able to pump the tank.") +
                                                            p("So the first thing worth finding on a South Venice job is the septic permit on file with the Florida Department of Health in Sarasota County, which shows where the tank and the field actually sit. Where that record is missing, and on 1950s and 1960s lots it often is, the layout gets probed before anything is formed. A patio that has to shift six feet to clear a field is a ten-minute conversation at the estimate and a demolition bill after the pour.")),
        ("A worked example", p("A 1971 Venice Gardens home with a 420-square-foot driveway in five pieces and a rust stripe from the sprinkler. Replacement on four compacted inches of crushed base, 4-inch 4,000 PSI fiber concrete with control joints every 8 feet, sprinkler heads moved, and a penetrating sealer at 28 days. County right-of-way use permit for the apron. Planning band in September 2026: $5,000 to $7,500.")),
    ]
    return city_page("south-venice", "Concrete & Pavers in South Venice & Venice Gardens, FL", "Driveway replacement, repair, patio slabs and pads in South Venice and Venice Gardens: county permits through the Venice office, 1950s to 80s block homes, septic and well constraints, and a 2026 worked example.",
                     "Concrete and pavers in South Venice and Venice Gardens", "Unincorporated county, small platted lots from the 1950s to 80s, septic and well water, and original driveways that have done their time.", intro, sections, faq)


def north_port():
    faq = [("What is different about pouring a driveway on a North Port GDC lot with a swale?", "The swale along the road is the lot's drainage, and the driveway crosses it on a culvert the city sizes. The crossing is permitted as a Right of Way Use Permit (Culvert/Driveway/Sidewalk/Concrete Slab), the swale is restored to grade, and Public Works inspects it before final. Pour it flat across the swale and you flood the neighbor."),
           ("Does North Port require engineered drawings?", "For permits that need them, construction documents must be sealed by a Florida-licensed engineer; a standard driveway on a standard culvert usually uses the city's detail. The Building Division at (941) 429-7044 confirms which applies."),
           ("Which portal does North Port use?", "Click2Gov for permits, with forms on northportfl.gov under Building-Planning."),
           ("Is North Port in a flood zone?", "Most of the GDC grid is X; AE runs along the Myakkahatchee Creek and the Myakka River, and Wellen Park's lakes set local zones."),
           ("What about Wellen Park?", "The North Port side of Wellen Park is permitted by the city and reviewed by the master association; builder driveways and pool decks are the common upgrade.")]
    intro = cap("What is hardscape work like in North Port?",
                "The largest city in Sarasota County (96,301 people, Florida EDR April 2025), built on tens of thousands of quarter-acre lots platted by General Development Corporation from the 1950s to the 1980s, with roadside swales for drainage and a city Building Division that permits driveway crossings, slabs and sidewalks under a Right of Way Use Permit. Wellen Park on the southwest edge adds new construction under ARC review.",
                p("Demand is driveway replacement and repair across the older grid (1970s to 2000s homes on deep sand), slabs and pads on large lots, and pool decks and paver upgrades in Wellen Park and the Woodlands communities."))
    sections = [
        ("City rules", table(["Rule", "What it means", "Page"], [["Right of Way Use Permit", "Culvert, driveway, sidewalk and concrete slab work at the road; swale restoration inspected by Public Works", link("/permits/north-port/", "North Port permits")], ["Sealed drawings", "Required where the city's standard detail doesn't cover the work", link("/permits/north-port/", "North Port permits")], ["Click2Gov", "Online permit portal", link("/permits/north-port/", "North Port permits")]], "North Port rules")),
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Price Boulevard and Toledo Blade corridors", "1970s to 2000s on GDC lots", "Driveway replacement with culvert crossing, repair, pads"], ["The Woodlands, Sabal Trace, Heron Creek, Bobcat Trail", "1990s to 2010s gated", "Pool decks, paver driveways, ARC review"], ["Wellen Park (North Port side), Islandwalk, Grand Palm, Renaissance", "2010s to 2020s", "Builder-slab upgrades, pavers in ARC colors"], ["Warm Mineral Springs", "1960s to 80s", "Driveway and walk replacement"]], "North Port areas")),
        ("Ground and drainage", p("Deep Myakka and Immokalee sands that drain fast on the surface and hold water at depth, with swales that were often too shallow or pitched wrong when the lots were platted. A driveway here is a drainage project first: the culvert is sized by the city, the swale is regraded, and the slab is pitched so water leaves the lot. Base compaction in lifts stops the settlement that shows up on so many 1980s driveways.")),
        ("A worked example", p("A 1986 home off Price Boulevard with a 500-square-foot driveway cracked in four places and a culvert crushed by a delivery truck. The scope: Right of Way Use Permit, new 15-inch culvert to the city's size, swale regraded, 4 inches of crushed base compacted in two lifts, a 4-inch slab of fiber-reinforced 4,000 PSI concrete on #3 rebar, joints sawn at 8 feet, Public Works inspection of the swale before final. September 2026 planning band: $7,500 to $11,500 including the culvert.")),
    ]
    return city_page("north-port", "Concrete & Pavers in North Port, FL – GDC Lots, Culverts, Permits", "Driveways, culvert crossings, repair, slabs and pool decks in North Port: the city's Right of Way Use Permit, swale drainage on GDC lots, Click2Gov, Wellen Park ARC review, and a 2026 worked example with the culvert included.",
                     "Concrete and pavers in North Port, where the driveway starts at the swale", "The county's largest city, platted on quarter-acre lots with roadside swales, permitted by its own Building Division, with Wellen Park growing on the edge.", intro, sections, faq)


def englewood():
    faq = [("Which county handles Englewood permits?", "Both. North of the county line (roughly Old Englewood Road and Dearborn Street), Sarasota County; south of it, Charlotte County, which permits all flatwork including pavers. Manasota Key is split the same way. The Property Appraiser sites for each county show the jurisdiction."),
           ("Does the Manasota Key Conservation District affect hardscape?", "Yes. The district, created by Laws of Florida chapter 71-904 and enforced by Sarasota County under Code Chapter 54, Article XXVII, adds construction rules on the key alongside the coastal setback and turtle lighting codes."),
           ("What did the 2024 storms do here?", "Helene and Milton pushed surge onto Manasota Key and along Lemon Bay; the Englewood beach access and the key's cottages took water. Paver fields were lifted and salted; the restoration sequence applies."),
           ("Is Englewood in a flood zone?", "AE along Lemon Bay and the creeks, AE and VE on Manasota Key, X across most of the inland grid."),
           ("Are there HOAs?", "Boca Royale, Plantation, Oyster Creek and Rotonda's neighbors have ARC review; most of old Englewood does not.")]
    intro = cap("What is hardscape work like in Englewood and on Manasota Key?",
                "A community of 20,150 people (Census 2020) that straddles the Sarasota-Charlotte line, so a driveway three streets apart can be permitted by two different counties with different rules. Inland it's 1960s to 1990s block homes on Myakka fine sand; Manasota Key is a barrier island in AE and VE zones, inside its own conservation district, that stood in surge in 2024.",
                p("Demand is paver pool decks, post-storm paver restoration, driveway replacement and repair. On the key, the coastal setback code, turtle lighting and the district's rules ride along with every job."))
    sections = [
        ("Two counties, one town", table(["Side", "Office", "Key differences", "Page"], [["Sarasota County (north)", "County Building, Venice office", "ROW permits at the road; $7,500 residential exemption with documentation", link("/permits/sarasota-county/", "Sarasota County")], ["Charlotte County (south)", "Community Development, Murdock Circle", "All flatwork permitted, pavers included; NOC over $5,000; published fees", link("/permits/charlotte-county/", "Charlotte County")]], "Englewood jurisdictions")),
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Old Englewood, Dearborn Street, Lemon Bay waterfront", "1950s to 70s cottages and canal homes", "Driveway and walk replacement, bayfront decks"], ["Englewood East, Overbrook, Grove City (Charlotte)", "1970s to 90s", "Driveway replacement, repair, pads"], ["Boca Royale, Plantation, Oyster Creek", "1980s to 2010s golf and gated", "Paver driveways and pool decks with ARC review"], ["Manasota Key", "Cottages, estates, rebuilds", "VE-zone decks, setback and district review, turtle lighting, surge resets"]], "Englewood areas")),
        ("Ground, salt and surge", p("Inland lots are Myakka fine sand; the key is beach sand and fill. Lemon Bay is brackish and the Gulf is a block away on the key, so sealer cycles are short and edge restraint is concrete. After the 2024 surge the standard sequence applies: document, drain, sound the base, rebuild, flush, reset.")),
        ("A worked example", p("A 1974 canal home on the Charlotte side of Englewood with a 600-square-foot concrete-paver pool deck that shifted along the seawall in October 2024. Charlotte County required a permit for the reset as slab work and a Notice of Commencement because the contract exceeded $5,000. The field was lifted, the base rebuilt and flushed, a concrete curb set at the seawall, pavers rinsed and reset, polymeric sand on a dry day. Planning band, dated September 2026: $6,000 to $9,000.")),
    ]
    return city_page("englewood", "Concrete & Pavers in Englewood & Manasota Key, FL – Two Counties", "Pool decks, paver restoration, driveways and repair in Englewood and on Manasota Key: which county permits your street, the conservation district, AE and VE zones, 2024 surge lessons and a 2026 worked example.",
                     "Concrete and pavers in Englewood and on Manasota Key, across two county lines", "Sarasota County to the north, Charlotte County to the south, a barrier island with its own conservation district, and a coast that took surge in 2024.", intro, sections, faq)


# ------------------------------------------------------------------ TIER 2
def port_charlotte():
    faq = [("Do Port Charlotte's older grid neighborhoods have drainage issues that affect driveways?", "Yes. The 1950s to 80s GDC plats rely on roadside swales that were often left shallow; driveways that cross them without a properly sized culvert dam the swale and flood the lot next door. Charlotte County permits the crossing and inspects it."),
           ("Does Charlotte County require a permit for a driveway or pavers?", "Yes, for all of it: the county's residential driveway and residential slab pages state that all concrete flatwork, structural or not, including pavers, requires a permit and inspections. Work only in the right-of-way is a ROW permit."),
           ("What are the fees?", "Published on the county's pages: $22 zoning review, $310 line and grade at issuance ($90 for ROW), slab review $22 non-structural or $90 structural, and a building fee of 0.004 times valuation over $50,000. A Notice of Commencement is required over $5,000."),
           ("Which services are scheduled in Port Charlotte?", "Pool decks (concrete and pavers), paver driveways, concrete driveways and concrete repair; other work is quoted case by case because of the drive."),
           ("Is Port Charlotte in a flood zone?", "AE along the canals, Charlotte Harbor and the Peace River; X on most of the interior grid.")]
    intro = cap("What is hardscape work like in Port Charlotte?",
                "A canal-laced retiree community of 61,964 people (Census 2020) on a GDC grid, 36.8 miles from Sarasota, permitted by Charlotte County, which permits every slab and paver field and publishes its fees. Demand is driveway and sidewalk repair across the 1970s and 80s blocks, salt-tolerant paver pool decks on the canals, and driveway replacement with culvert crossings.",
                p("Because of the distance, four services are scheduled here: pool decks, paver driveways, concrete driveways and concrete repair. Rules and fees are on the Charlotte County permit page."))
    sections = [
        ("Neighborhoods", table(["Area", "Housing", "Typical work"], [["Section 15, Murdock grid, Kings Highway corridor", "1970s to 80s block homes", "Driveway replacement, culvert crossings, repair"], ["Gulf Cove, South Gulf Cove, Grassy Point", "Canal-front, 1980s to 2010s", "Salt-tolerant paver pool decks, seawall-side resets"], ["Deep Creek, Harbour Heights", "1980s to 2000s", "Pool decks, driveways"], ["Riverwood, Heritage Oak Park", "Gated, 1990s to 2010s", "ARC-reviewed pavers"]], "Port Charlotte areas")),
        ("Ground and water", p("Myakka and Immokalee sands with a brackish water table on the canal lots. Swales drain the grid; culverts are sized by the county. Salt reaches the canal-front decks from the water and from salt pools; sealer cycles run 18 to 24 months there.")),
        ("A worked example", p("A 1979 home in Section 15 with a 480-square-foot driveway settled at the garage and a swale crossing with no culvert. Charlotte County permit and NOC, culvert sized by the county, swale regraded, a compacted 4-inch crushed-rock base, a 4-inch fiber-reinforced 4,000 PSI slab, control joints every 8 feet, line-and-grade inspection. Band as of September 2026: $7,000 to $10,500 including the culvert.")),
    ]
    return city_page("port-charlotte", "Concrete & Pavers in Port Charlotte, FL – County Permits & Fees", "Pool decks, paver and concrete driveways and repair in Port Charlotte: Charlotte County's all-flatwork permit rule and published fees, GDC swales and culverts, canal-front salt exposure, and a 2026 worked example.",
                     "Concrete and pavers in Port Charlotte, on the GDC grid", "Charlotte County permits every slab and paver field, swales drain the plats, and the canal lots see salt from two directions.", intro, sections, faq)


def rotonda_west():
    faq = [("How far is Rotonda West from Sarasota and is it served?", "34.6 miles straight-line, 50 to 60 minutes by SR-776, inside the 40-mile radius. Pool decks, paver driveways, concrete driveways and concrete repair are scheduled here."),
           ("Does the Rotonda West Association review driveway changes?", "Yes. The association enforces deed restrictions across the community's sections and reviews exterior changes; submit to the association alongside the Charlotte County permit."),
           ("What permit does Rotonda need?", "Charlotte County's: all flatwork including pavers requires a permit and inspections, with a Notice of Commencement over $5,000."),
           ("Is Rotonda in a flood zone?", "AE around the canal system and toward the Cape Haze peninsula; X in much of the interior of the circle."),
           ("What is the housing like?", "1970s to 2000s single-story homes, most with pool cages, on canal-ringed sections built on the county's Myakka soils.")]
    intro = cap("What is hardscape work like in Rotonda West?",
                "A 10,114-person (Census 2020) planned community laid out as a wheel of canal-ringed sections on the Cape Haze peninsula, governed by the Rotonda West Association's deed restrictions and permitted by Charlotte County, which permits every slab and paver field. Demand is pool deck replacement under cages, paver driveways in approved colors, and driveway repair on 1970s to 2000s homes.",
                p("Four services are scheduled here because of the 50-to-60-minute drive: pool decks, paver driveways, concrete driveways and concrete repair."))
    sections = [
        ("Rules", table(["Rule", "What it means", "Page"], [["Charlotte County permit for all flatwork", "Permit, inspections, NOC over $5,000, published fees", link("/permits/charlotte-county/", "Charlotte County permits")], ["Rotonda West Association", "Deed restrictions and review of exterior changes", link("/hoa/", "HOA guides")], ["Flood zones", "AE along canals; base flood elevation on the permit", link("/permits/flood-zones-50-percent-rule/", "Flood zones")]], "Rotonda West rules")),
        ("Ground and water", p("Myakka fine sand over a canal network that sets the water table near the surface on canal lots. Pool decks under cages need drains; driveways need compacted base in lifts and an edge that holds at the street.")),
        ("A worked example", p("A 1995 home in the Pinehurst section with a 620-square-foot cool-deck pool deck delaminating under the cage. Sounding found the slab hollow at the coping, so it came out; the owner chose light concrete pavers on 4 inches of compacted base with a deck drain and a concrete curb at the cage line. Charlotte County permit and NOC; association approval on the color. Planning band in September 2026: $9,000 to $12,500.")),
    ]
    return city_page("rotonda-west", "Concrete & Pavers in Rotonda West, FL – Pool Decks & Driveways", "Pool decks, paver driveways, concrete driveways and repair in Rotonda West: Charlotte County permits for all flatwork, Rotonda West Association review, canal-side flood zones, and a 2026 worked example.",
                     "Concrete and pavers in Rotonda West, inside the circle", "A canal-ringed planned community under deed restrictions, permitted by Charlotte County, 50 to 60 minutes from Sarasota.", intro, sections, faq)


def placida():
    faq = [("Are Placida and Grove City served?", "Yes, at the edge of the radius (31 to 39 miles): pool decks, paver driveways, concrete driveways and concrete repair are scheduled; other work is quoted case by case."),
           ("Which office permits Placida?", "Charlotte County, which permits every slab and paver field and publishes its fees."),
           ("Is the waterfront in a VE zone?", "Lots on Lemon Bay, Gasparilla Sound and the Cape Haze peninsula are AE, with VE on the most exposed shorelines. The county's flood maps show each parcel."),
           ("What about boat lifts and dock approaches?", "The upland pad for a lift motor or a dock approach is concrete work; anything over the water or on the seawall is marine construction with its own contractor and permit."),
           ("Are there HOAs?", "The Cape Haze golf communities and several waterfront associations review exterior changes; old Grove City mostly does not.")]
    intro = cap("What is hardscape work like in Placida, Grove City and Cape Haze?",
                "Waterfront and golf-community lots at the south end of the Cape Haze peninsula (Grove City had 2,402 people in the 2020 Census), 31 to 39 miles from Sarasota, permitted by Charlotte County. Filled waterfront lots on Lemon Bay and Gasparilla Sound with boat lifts, 1980s to 2010s golf-course homes, and salt everywhere.",
                p("Four services are scheduled: pool decks, paver driveways, concrete driveways and concrete repair. Dock and lift pads on the upland side are concrete work; marine construction is not."))
    sections = [
        ("Ground and salt", p("Sand and shell fill on the waterfront, Myakka fine sand inland. Bases drain fast and carry salt from the sound; paver sealer runs 18 to 24 months, coping on salt pools is sealed annually, and edge restraint is concrete on any edge a surge can reach.")),
        ("Rules", p(f'Charlotte County permits all flatwork with a Notice of Commencement over $5,000 (see {link("/permits/charlotte-county/", "Charlotte County permits")}); flood zones are AE and VE on the water; associations in Cape Haze review changes.')),
        ("A worked example", p("A 2006 waterfront home on the Cape Haze peninsula with a 720-square-foot travertine pool deck and a boat-lift motor pad. The deck was sound but the coping was flaking from the salt pool and the lift pad had tilted; the coping was replaced and sealed, the deck field re-sanded and sealed, and a new 6-inch reinforced lift pad poured on compacted base. County permit for the pad. September 2026 planning band: $4,500 to $7,000.")),
    ]
    return city_page("placida", "Concrete & Pavers in Placida & Grove City, FL – Waterfront", "Pool decks, paver driveways, concrete driveways and repair in Placida, Grove City and Cape Haze: Charlotte County permits, AE and VE waterfront zones, salt exposure, lift and dock pads, and a 2026 worked example.",
                     "Concrete and pavers in Placida, Grove City and Cape Haze", "Filled waterfront lots on Lemon Bay and Gasparilla Sound, golf communities, Charlotte County permits, and salt on every surface.", intro, sections, faq)


def get_pages():
    return [areas_hub(), sarasota_county(), charlotte_county(), sarasota(), fruitville(), gulf_gate(), siesta_key(), palmer_ranch(), longboat_key(), osprey(), nokomis(), venice(), south_venice(), north_port(), englewood(), port_charlotte(), rotonda_west(), placida()]
