# -*- coding: utf-8 -*-
"""City x service pages, part B: Osprey, Nokomis, Venice, South Venice, North Port, Englewood, Port Charlotte, Rotonda West, Placida."""
from content_city_service import page
from _h import p, link


def get_pages():
    P = []
    # ---------------------------------------------------------------- OSPREY & CASEY KEY
    P.append(page("osprey", "pavers-pool-decks", "Paver Pool Decks in Osprey & Casey Key, FL – Estates & Salt", "Paver pool decks in Osprey and on Casey Key: travertine $20 to $26, marble and porcelain higher, concrete pavers $13 to $16 per sq ft; The Oaks and Southbay ARC review, Casey Key VE zones and conservation district, and a worked example.",
        "Paver pool decks in Osprey and on Casey Key", "Travertine and marble decks for The Oaks and Southbay, and Casey Key decks built for a VE zone reached by a one-lane swing bridge.",
        "What does a paver pool deck cost in Osprey or on Casey Key?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, with marble and porcelain higher; Casey Key adds 5 to 15 percent for staging around the Blackburn Point swing bridge. An 800-square-foot deck behind an Oaks home runs roughly $16,000 to $21,000 in travertine before coping, demolition and drains.",
        p("Osprey's deck market is estate-scale: The Oaks Clubside and Bayside, Southbay Yacht & Racquet Club and the Rivendell and Park Trace homes upgrade builder decks to travertine, marble or porcelain under large cages, with coping in the same stone. Southbay and the Bay Street lots see Little Sarasota Bay spray and get the salt discipline. Casey Key is a different job: AE and VE, the North Casey Key Conservation District, the coastal setback line on the Gulf side, and a bridge that limits truck weight, so pavers are staged in trips and the base is built to be flushed.") + p("Chlorine pools dominate in The Oaks; salt pools on the key."),
        p(f'Sarasota County permit ({link("/permits/sarasota-county/", "rules")}); The Oaks, Southbay and Rivendell ARC review; on Casey Key the coastal setback code, the conservation district (Code Ch. 54 Art. XXVI) and {link("/permits/sea-turtle-lighting/", "turtle lighting")}.'),
        p("A 1997 Oaks Clubside home with a 940-square-foot broom deck under a two-story cage, sound, ponding at two corners. Scope: two linear drains cut in and tied to the lake-side yard drain, honed marble bullnose coping mortar-set, honed marble field sand-set over the slab on a re-screeded bed with a perimeter curb, cage anchors reset into the curb, polymeric sand, penetrating sealer at 30 days. ARC approval three weeks; no county permit for the overlay. Planning band: $26,000 to $34,000."),
        "How does the Casey Key bridge change a deck job?", "Weight limits and one lane mean pavers, base and equipment arrive in smaller loads timed around the swing schedule, which adds a day and 5 to 15 percent. It also means the crew stages on the lot, so the site plan shows where the pallets sit.",
        [("/pavers/marble-porcelain/", "Marble and porcelain", "Estate lanai floors."), ("/permits/flood-zones-50-percent-rule/", "Flood zones and setback", "Casey Key rules.")]))
    P.append(page("osprey", "pavers-driveways", "Paver Driveways in Osprey, FL – The Oaks, Rivendell, Bay Street", "Paver driveways in Osprey: $14 to $22 per sq ft planning band, ARC review in The Oaks, Rivendell, Willowbend and Park Trace, county apron permit on US-41 side streets, bayfront salt cycle and a worked example.",
        "Paver driveways in Osprey", "Circular drives in The Oaks and builder-driveway upgrades in Rivendell and Park Trace, with the county's apron permit and the community's color list.",
        "What does a paver driveway cost in Osprey?", "About $14 to $22 per square foot installed, so a 700-square-foot two-car driveway in Rivendell runs roughly $9,800 to $15,400 plus demolition and the apron under a county right-of-way use permit; an Oaks motor court of 1,500 square feet runs $21,000 to $33,000. Bayfront lots add the 18-month sealing cycle.",
        p("Osprey driveways range from 1980s and 90s builder slabs in Rivendell, Willowbend and Park Trace that get replaced with herringbone concrete pavers in ARC-approved blends, to motor courts and circular drives in The Oaks that use large-format or tumbled pavers with contrasting bands. The ground is Myakka fine sand with a shallow water table toward the bay: 6 inches of base in lifts, geotextile, a concrete curb at the street. Bay Street and Southbay lots see spray and seal every 18 to 24 months.") + p("Casey Key driveways are short, on fill, and built with the deck to the same salt rules."),
        p(f'County right-of-way use permit for the apron and flatwork review ({link("/permits/sarasota-county/", "rules")}); The Oaks, Rivendell, Willowbend, Park Trace and Southbay ARC review; 50 percent impervious cap on RSF lots.'),
        p("A 1992 Rivendell home with a 680-square-foot builder driveway settled at the garage. Scope: demolition, garage strip compacted, 6 inches of base in three lifts over geotextile, herringbone field in an approved gray-tan blend with a charcoal soldier course, poured curb where the field meets the street, apron in pavers under the county ROW permit, sprinkler heads redirected, polymeric sand, sealing at 30 days. ARC approval two weeks. Planning range: $10,500 to $14,500."),
        "Does The Oaks limit driveway materials?", "The community reviews material, color and layout for anything visible from the street, and motor courts are reviewed as site changes; approved blends are common, dark fields are not. Bring the current guideline to the estimate.",
        [("/concrete/driveways/osprey/", "Concrete driveways in Osprey", "The poured alternative."), ("/pavers/sealing/", "Sealing", "Bayfront cycle.")]))
    P.append(page("osprey", "pavers-travertine-shellstone", "Travertine & Shellstone in Osprey & Casey Key, FL", "Travertine and shellstone decks and patios in Osprey and on Casey Key: $20 to $26 per sq ft, finishes for wet grip, the salt-pool coping rule on the bay and the key, ARC review and a worked example.",
        "Travertine and shellstone in Osprey and on Casey Key", "Natural stone for estate lanais and Gulf-to-bay lots, sealed and rinsed so the waterline stays whole.",
        "What does travertine cost installed in Osprey or on Casey Key?", "About $20 to $26 per square foot installed, with coping at $30 to $60 per linear foot; Casey Key adds 5 to 15 percent for bridge logistics. A 600-square-foot Southbay lanai runs roughly $12,000 to $15,600 before coping and drains, and the care sheet carries an annual coping date if the pool is salt.",
        p("Travertine is the default finish for The Oaks and Southbay renovations, tumbled for pool decks and honed for lanais that continue an interior floor; shellstone shows up on Casey Key and the Bay Street waterfront where the owner wants the coastal fossil look. Both are calcium carbonate: on the bayfront and on the key, spray and salt pools flake the coping unless it's sealed annually and rinsed weekly, and acid cleaners are banned from the care sheet. Inland Rivendell and Park Trace lots on chlorine pools get the 2-to-3-year cycle.") + p("French pattern in 1-1/4-inch stone for decks; 2-inch pieces where a golf cart or a car crosses."),
        p(f'County permit as for any deck ({link("/permits/sarasota-county/", "rules")}); ARC review in the gated communities; on Casey Key the setback line, conservation district and {link("/permits/sea-turtle-lighting/", "turtle lighting")}.'),
        p("A Casey Key Gulf-to-bay home with a 560-square-foot bay-side pool deck in 1990s concrete pavers, coping cracked. Scope: demolition, base rebuilt in lifts over geotextile, shellstone bullnose coping mortar-set, shellstone field in a modular pattern, concrete curb at the seawall, amber wall-cap lighting toward the Gulf side, polymeric sand, penetrating sealer at 30 days with annual coping sealing (salt pool). Staged over the swing bridge in four trips. County permit; conservation-district review. Budget band: $16,000 to $21,000."),
        "Is shellstone too soft for a deck that sees surge?", "No softer than travertine; both are lifted, rinsed and reset after a surge like any paver. The base and the edge restraint are what fail, and both are built for it on the key.",
        [("/compare/travertine-vs-shellstone-vs-porcelain/", "Travertine vs shellstone vs porcelain", "Heat, slip, salt."), ("/coastal/salt-and-concrete/", "Salt", "The chemistry.")]))
    P.append(page("osprey", "concrete-driveways", "Concrete Driveways in Osprey, FL – Rivendell & Park Trace", "Concrete driveway replacement in Osprey: $7 to $12 per sq ft, 1980s to 2000s builder slabs, county right-of-way permit, ARC review, Myakka sand base and a worked example.",
        "Concrete driveways in Osprey", "Replacing 1980s and 90s builder slabs in Rivendell, Park Trace and Sorrento Woods, and 1950s slabs along Bay Street, on a compacted base.",
        "What does a concrete driveway cost in Osprey?", "About $7 to $12 per square foot installed, so a 660-square-foot two-car driveway runs roughly $4,600 to $7,900 plus $1,300 to $2,600 for demolition and $300 to $800 for the apron under a county right-of-way use permit. Bay Street and Southbay lots get the low water-cement mix and a penetrating sealer for spray.",
        p("Osprey's concrete driveways are the builder pours of Rivendell, Willowbend, Park Trace and Sorrento Woods from the 1980s to 2000s, at 4 inches with little base and long panels, settled at the garage and cracked mid-panel, plus the 1950s and 60s slabs along Bay Street and old Osprey. Replacement on Myakka fine sand means the backfill strip at the garage compacted, 4 to 6 inches of base depending on how wet the lot sits in August, a 4,000 PSI fiber slab with #3 bar, joints at 8 feet, and the apron to the county detail.") + p("ARC communities review color and width; most accept broom in natural gray."),
        p(f'County right-of-way use permit and flatwork review ({link("/permits/sarasota-county/", "rules")}); ARC in Rivendell, Willowbend, Park Trace, The Oaks; the 50 percent impervious cap on widenings.'),
        p("A 1988 Sorrento Woods home with a 620-square-foot driveway cracked across four panels and dropped at the garage. Scope: demolition, the soft strip at the garage dug out and compacted, 4 inches of base, 4-inch 4,000 PSI fiber concrete with #3 bar dowelled to the apron, control joints every 8 feet, apron under the county ROW permit, penetrating sealer at 28 days. Cost band: $6,300 to $9,200."),
        "Should an Osprey driveway be pavers instead?", "In The Oaks and Southbay, the market and the ARCs lean to pavers; in Rivendell, Park Trace and old Osprey, a well-built concrete driveway on a compacted base is the cheaper thirty-year answer. The comparison page has the twenty-year math.",
        [("/pavers/driveways/osprey/", "Paver driveways in Osprey", "The other answer."), ("/compare/concrete-vs-pavers-driveway/", "Concrete vs pavers", "Twenty-year cost.")]))

    # ---------------------------------------------------------------- NOKOMIS & LAUREL
    P.append(page("nokomis", "pavers-driveways", "Paver Driveways in Nokomis, FL – Toscana Isles & Bellacina", "Paver driveways in Nokomis and Laurel: $14 to $22 per sq ft, builder-slab upgrades in Toscana Isles, Bellacina and Talon Preserve on imported fill, ARC color lists, county apron permit and a worked example.",
        "Paver driveways in Nokomis and Laurel", "Herringbone driveways replacing builder concrete in the communities east of I-75, on fill that needs its own base.",
        "What does a paver driveway cost in Nokomis?", "About $14 to $22 per square foot installed, so a 520-square-foot driveway in Toscana Isles or Bellacina runs roughly $7,300 to $11,400 plus $1,000 to $2,100 for demolition of the builder slab and the apron under a county right-of-way use permit. The ARC color list decides the blend; the fill under the lot decides the base.",
        p("The new communities east of I-75 (Toscana Isles, Bellacina by Casey Key, Talon Preserve, Vicenza, Milano) came with broom driveways and strict color lists, and pavers are the upgrade neighbors already made. The lots are imported fill placed by the developer in thick lifts, which settles for years, so the driveway gets its own 6 inches of compacted base in three lifts over geotextile rather than trust in the fill. Well water east of the interstate means heads moved and a sealed field. Calusa Lakes and Sorrento East, older and on native sand, get the same base and fewer color rules.") + p("Nokomis Beach and the Casey Key south end add the salt cycle."),
        p(f'County right-of-way use permit for the apron and flatwork review ({link("/permits/sarasota-county/", "rules")}); ARC review in every master-planned community east of I-75; Calusa Lakes HOA.'),
        p("A 2019 Toscana Isles home with a 520-square-foot builder driveway. Scope: demolition, geotextile under 6 inches of base in three compacted lifts, 45-degree herringbone in the light tan blend on the ARC list with a charcoal soldier course, a concrete edge at the street line, apron in pavers under the county ROW permit, irrigation heads turned away from the surface, polymeric joint sand and a sealer 30 days later. ARC approval three weeks. Planning band: $8,500 to $12,000."),
        "Why not lay pavers on the developer's compacted fill?", "Because fill placed in thick lifts keeps settling for years, and a driveway laid on it follows. Six inches of base compacted in 3-inch lifts on top of the fill is what keeps the field flat through the first wet seasons.",
        [("/pavers/pool-decks/nokomis/", "Paver pool decks in Nokomis", "The other builder upgrade."), ("/guides/well-water-rust-stains/", "Rust stains", "Well irrigation east of I-75.")]))
    P.append(page("nokomis", "pavers-pool-decks", "Paver Pool Decks in Nokomis, FL – New Communities & Old Lots", "Paver pool decks in Nokomis and Laurel: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, builder-deck upgrades in Bellacina and Talon Preserve, 1970s decks in Sorrento East, ARC review and a worked example.",
        "Paver pool decks in Nokomis and Laurel", "Travertine over builder decks east of I-75 and full rebuilds on the 1970s lots west of it.",
        "What does a paver pool deck cost in Nokomis?", "For a 600-square-foot deck, count on roughly $7,800 to $9,600 if the field is concrete pavers ($13 to $16 a square foot) and $12,000 to $15,600 in travertine ($20 to $26), with coping and a drain added on top. East of I-75 the builder deck under the cage is usually sound enough to take pavers over it; in Sorrento East and Calusa Lakes the 1970s deck usually comes out first.",
        p("Two jobs with the same name. East of I-75, a 2016-to-2024 builder deck under a cage passes the five overlay tests and gets travertine or a light paver thin-set or sand-set over it with a perimeter curb and a drain cut in where the cage ponds; the ARC reviews the material. West of the interstate, a 1970s deck in Sorrento East, Sorrento South or Calusa Lakes was poured tight to the shell with no isolation joint and gets demolished, based, drained and re-laid. Chlorine pools dominate both; Nokomis Beach lots on salt pools get the annual coping rule.") + p("Cages here are big; anchors go into a concrete curb at the cage line."),
        p(f'County flatwork review for a new deck; overlays on the footprint usually below thresholds ({link("/permits/sarasota-county/", "rules")}); ARC in the communities east of I-75; Nokomis Beach lots under {link("/permits/sea-turtle-lighting/", "turtle lighting")}.'),
        p("A 2021 Bellacina home with a 640-square-foot builder deck under a cage, sound, no drain. Scope: linear drain cut into the low side and tied to the lake-side yard drain, travertine bullnose coping, tumbled travertine field sand-set over the slab with a perimeter curb, the cage re-anchored into the new curb, polymeric sand now and sealing after 30 days. ARC approval two weeks; no county permit for the overlay. Planning range: $13,500 to $17,500."),
        "Do the new communities require a permit for a deck overlay?", "The county usually doesn't for an overlay on the same footprint; the community's ARC always does. Submit the material sample, the drain detail and a photo of the cage line.",
        [("/pavers/patios-lanais/", "Paver patios and lanais", "The five overlay tests."), ("/compare/travertine-vs-concrete-pavers/", "Travertine vs pavers", "Cost and heat.")]))
    P.append(page("nokomis", "concrete-driveways", "Concrete Driveways in Nokomis & Laurel, FL – Sorrento East", "Concrete driveway replacement in Nokomis and Laurel: $7 to $12 per sq ft, 1970s to 90s slabs on native sand, county right-of-way permit through the Venice office, well-water rust and a worked example.",
        "Concrete driveways in Nokomis and Laurel", "Replacing 1970s to 90s driveways in Sorrento East, Calusa Lakes, Mission Valley and Laurel on Myakka sand, with the county's Venice office issuing the permit.",
        "What does a concrete driveway cost in Nokomis or Laurel?", "About $7 to $12 per square foot installed, so a 580-square-foot driveway runs roughly $4,100 to $7,000 plus $1,200 to $2,300 for demolition and $300 to $800 for the apron under a county right-of-way use permit. Larger Mission Valley lots often add a boat pad at 6 inches.",
        p("West of I-75 the driveways are 1970s to 90s pours on native Myakka and Immokalee sand: Sorrento East and South, Calusa Lakes, Mission Valley, Laurel and Venice Hills. Settled at the garage, cracked across long panels, orange from well-water sprinklers. Replacement is the standard: compaction of the backfill along the garage, 4 to 6 inches of base by how wet the lot sits, fiber 4,000 PSI slab on #3 rebar, joints sawn at 8 feet, apron to the county detail, heads moved. Calusa Lakes reviews color; most of the older neighborhoods don't.") + p("The county's Venice office at 4000 South Tamiami Trail is the closer permit counter."),
        p(f'County right-of-way use permit and flatwork review ({link("/permits/sarasota-county/", "rules")}); Calusa Lakes and the newer communities review; septic drain fields on some Laurel lots limit widening.'),
        p("A 1981 Sorrento East home with a 600-square-foot driveway in five pieces and a rust stripe. Scope: demolition, garage strip compacted, 4 inches of base, a 4-inch slab of fiber-reinforced 4,000 PSI concrete on #3 rebar, an 8-foot joint spacing, apron under the county ROW permit, sprinklers re-aimed off the hardscape, penetrating sealer at 28 days. Budget band: $5,800 to $8,600."),
        "Does Laurel have a different permit office from Nokomis?", "No; both are unincorporated Sarasota County, and the Venice office on South Tamiami Trail handles the counter. The Property Appraiser's map confirms any parcel that looks like it might be inside Venice's city line.",
        [("/concrete/patios-lanais/nokomis/", "Patios and lanais in Nokomis", "The slab that usually goes with it."), ("/concrete/slabs/", "Pads", "Boat and RV pads.")]))
    P.append(page("nokomis", "concrete-patios-lanais", "Concrete Patios & Lanai Slabs in Nokomis, FL – Extensions", "Concrete patios and lanai extensions in Nokomis and Laurel: $8 to $13 per sq ft broom, $11 to $17 exposed aggregate, cage extensions in the new communities, 1970s lanai replacement west of I-75, county review and a worked example.",
        "Concrete patios and lanai slabs in Nokomis and Laurel", "Lanai extensions beyond builder cages east of I-75 and replacement of settled 1970s lanais west of it.",
        "What does a lanai slab or patio cost in Nokomis?", "About $8 to $13 per square foot for a broom slab and $11 to $17 for exposed aggregate or color, so a 12-by-24 lanai extension runs roughly $2,300 to $3,700 before the cage extension and a floor drain. In Sorrento East a settled 1970s lanai replaced with a drain runs $3,500 to $5,500 for the same size.",
        p("The most common Nokomis patio job is extending a builder lanai in Toscana Isles, Talon Preserve or Vicenza: the new slab is poured beside the existing one on its own base with a dowelled joint, pitched to a new floor drain, and the cage is extended by the cage contractor. West of I-75 the 1970s lanais in Sorrento East and Calusa Lakes have settled toward the sliders and are replaced. Exposed aggregate with light stone is popular for heat and for hiding well-water stains.") + p("Extensions are checked against the 50 percent impervious cap on the smaller new-community lots."),
        p(f'County review for slabs that carry a cage; at-grade patios often below thresholds ({link("/permits/sarasota-county/", "rules")}); ARC review for extensions in every community east of I-75.'),
        p("A 2018 Talon Preserve home extending a 10-by-20 lanai to 10-by-32. Scope: 4 inches of compacted base on the fill, 4-inch 4,000 PSI fiber slab dowelled to the existing lanai with #3 bar at the new cage line, floor drain at the low corner tied to the yard drain, light exposed-aggregate finish matched across both by a decorative overlay on the old section, cage extended by the cage contractor under its own permit. ARC approval three weeks. Cost band: $4,500 to $6,800 for the concrete and overlay."),
        "Will the extension match the old lanai floor?", "The slab won't, exactly; a thin decorative overlay across both is how the finish is matched, and the joint between them is planned as a straight line the eye reads as design.",
        [("/concrete/patios-lanais/", "Patios and lanais", "Finishes and spec."), ("/pavers/patios-lanais/", "Paver lanais", "The other extension.")]))

    # ---------------------------------------------------------------- VENICE
    P.append(page("venice", "concrete-driveways", "Concrete Driveways in Venice, FL – Island, Mainland & Wellen Park", "Concrete driveway replacement in the City of Venice: $7 to $12 per sq ft, eTRAKiT permits, Engineering's right-of-way review and 6-inch aprons, Venice Island trees and historic guidelines, Wellen Park ARC and a worked example.",
        "Concrete driveways in the City of Venice", "Island tear-outs around live oaks, mainland replacements, and Wellen Park upgrades, each with the city's engineering review at the street.",
        "What does a concrete driveway cost in Venice?", "About $7 to $12 per square foot installed, so a 500-square-foot island driveway runs roughly $3,500 to $6,000 plus $1,000 to $2,000 for demolition and the apron poured to the city's detail, commonly 6 inches, under Engineering's right-of-way review. Permits through eTRAKiT and the review add two to five weeks.",
        p("Venice Island driveways are 1926-to-1960s ribbons on narrow lots between mature trees, and replacement means routing around the roots, keeping to the historic district's guidelines where they apply, and pouring the apron to the city detail. The mainland's 1970s to 90s neighborhoods (Pinebrook, Jacaranda West, Capri Isles) have the standard settled builder slabs. Wellen Park's Venice-side villages have new builder driveways the ARC lets you widen only inside the garage wall line.") + p("The island sits on fill and shell and drains fast; the mainland is Myakka sand and holds water in August."),
        p(f'Building permit through eTRAKiT; Engineering right-of-way review and city detail for the apron ({link("/permits/venice/", "Venice rules")}); historic district design review on the island; Wellen Park ARC.'),
        p("A 1962 island home on a 60-foot lot with a 440-square-foot ribbon driveway and an apron heaved by a live oak. Scope: root bridged with a thickened slab section over compacted stone, driveway widened to 11 feet on 4 inches of base, 4,000 PSI fiber-reinforced concrete at 4 inches with #3 rebar on chairs, joints cut on an 8-foot grid, apron poured at 6 inches to the city detail under the right-of-way authorization. eTRAKiT permit and engineering review five weeks. Planning band: $5,800 to $8,400."),
        "Does Venice require the apron in concrete?", "Where the city's detail calls for concrete at the curb, yes, at the detail's thickness; pavers over it need a license agreement. The engineering review answers it for your street before the estimate is final.",
        [("/concrete/pool-decks/venice/", "Pool decks in Venice", "The other island job."), ("/hoa/wellen-park/", "Wellen Park review", "Width rules.")]))
    P.append(page("venice", "concrete-pool-decks", "Concrete Pool Decks in Venice, FL – Island Salt & Mainland Slabs", "Concrete pool decks in the City of Venice: $9 to $14 per sq ft new, overlays $4 to $15, island decks in AE and VE with salt-resistant mix, mainland 1980s decks, eTRAKiT permits and a worked example.",
        "Concrete pool decks in the City of Venice", "Salt-mix decks on the island, replacements for 1980s mainland decks, and overlays where the slab still rings solid.",
        "What does a concrete pool deck cost in Venice?", "About $9 to $14 per square foot for a new textured deck, so a 600-square-foot deck runs roughly $5,400 to $8,400 before demolition and drains; an overlay on a sound slab is $4 to $8 per square foot. Island lots use the low water-cement mix and a penetrating sealer for spray and add a little for staging on small lots.",
        p("Venice Island pool decks sit in AE and VE on fill a few feet above the bay and the Gulf: salt spray, salt pools, and lighting rules on the Gulf side. New decks there are poured with a water-cement ratio at or below 0.45, 2 inches of cover over the cage-line steel, a 7-day cure and a penetrating sealer, and pitched to drains that reach the seawall side. Mainland decks in Pinebrook, Jacaranda West and Bird Bay are 1980s pours with cool-deck overlays that mostly fail sounding at the coping; Wellen Park decks are new and sound, and get overlays or pavers.") + p("The city's cages are aluminum and anchors go into new concrete at the cage line."),
        p(f'Building permit through eTRAKiT for replacement; overlays on the footprint usually below thresholds ({link("/permits/venice/", "Venice rules")}); AE and VE on the island ({link("/permits/flood-zones-50-percent-rule/", "flood page")}); {link("/permits/sea-turtle-lighting/", "turtle lighting")} on beach-visible lots; Wellen Park ARC.'),
        p("A 1986 Jacaranda West home with a 660-square-foot deck, cool-deck overlay peeling, hollow at the coping across 40 feet. Scope: demolition, a 4-inch compacted limerock base, isolation joint at the shell, two deck drains, 4-inch 4,000 PSI fiber deck with #3 bar at the cage line, light knockdown texture, matte sealer with grit, cage re-anchored. eTRAKiT permit. Planning range: $7,000 to $10,000."),
        "Is a poured deck the right call on Venice Island?", "In AE on the interior of the island, yes, with the salt mix; in VE on the Gulf side, pavers on a rebuildable base usually win, and under an elevated home the engineer designs whatever sits below the floor.",
        [("/pavers/pool-decks/venice/", "Paver pool decks in Venice", "The other answer."), ("/compare/resurface-vs-replace-pool-deck/", "Resurface or replace", "Six tests.")]))
    P.append(page("venice", "pavers-pool-decks", "Paver Pool Decks in Venice, FL – Island, Bird Bay, Wellen Park", "Paver pool decks in the City of Venice: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, island salt and lighting rules, overlays on Wellen Park builder decks, condo boards on the island and a worked example.",
        "Paver pool decks in the City of Venice", "Travertine on the island with the salt rule, overlays on Wellen Park's builder decks, and phased common decks for the island's condos.",
        "What does a paver pool deck cost in Venice?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 650-square-foot deck runs roughly $8,500 to $10,400 in pavers or $13,000 to $17,000 in natural stone, with coping and drains extra; island lots add a little for staging, and salt pools add the annual coping line on the care sheet.",
        p("Three markets. Venice Island's 1950s and 60s homes and Gulf-front condos: travertine or porcelain decks in AE and VE, concrete curbs at any edge the water can reach, amber lighting on the Gulf side, annual coping sealing on salt pools, phased common decks for the boards. The mainland's Bird Bay, Capri Isles and Pelican Pointe: 1980s to 2000s decks replaced with light pavers. Wellen Park: builder decks that pass the overlay tests and get travertine over them with a drain cut in.") + p("Island logistics are modest: three bridges, small lots, staging on the driveway."),
        p(f'eTRAKiT permit for a new deck; overlays on the footprint usually below thresholds ({link("/permits/venice/", "Venice rules")}); island flood zones and {link("/permits/sea-turtle-lighting/", "turtle lighting")}; Wellen Park ARC; condo boards ({link("/hoa/barrier-island-condos/", "condo guide")}).'),
        p("A 1959 island home on the bay side with a 700-square-foot concrete deck cracked along the coping. Scope: demolition, base rebuilt in lifts over geotextile, linear drain, travertine bullnose coping, tumbled travertine field, concrete curb at the seawall and the cage line, amber recessed lights, joints filled with polymeric sand, sealer applied at day 30 with annual coping sealing (salt pool). eTRAKiT permit. Budget band: $16,000 to $20,500."),
        "Which Venice decks are worth overlaying rather than rebuilding?", "Wellen Park's builder decks, almost always; mainland 1980s decks, sometimes; island decks that stood in surge, rarely. Sounding decides, and the estimate records the result.",
        [("/pavers/travertine-shellstone/", "Travertine and shellstone", "The salt rule."), ("/hoa/wellen-park/", "Wellen Park review", "What the ARC wants.")]))
    P.append(page("venice", "concrete-resurfacing", "Pool Deck Resurfacing in Venice, FL – Overlays That Last", "Pool deck resurfacing and overlays in the City of Venice: $4 to $8 basic, $10 to $15 decorative per sq ft, the six tests on 1980s mainland decks and Wellen Park builder decks, salt-side sealers and a worked example.",
        "Pool deck resurfacing in the City of Venice", "Light knockdown overlays on mainland and Wellen Park decks that pass the tests, and a plain no on decks that don't.",
        "What does pool deck resurfacing cost in Venice?", "About $4 to $8 per square foot for a basic textured overlay and $10 to $15 for a decorative one, so a 600-square-foot deck runs roughly $2,400 to $4,800 basic or $6,000 to $9,000 decorative, on a slab that rings solid, drains, has no offset cracks and leaves room under the threshold. Wellen Park decks nearly always qualify; 1980s mainland decks about half the time.",
        p("Venice has more overlay candidates than the keys because its mainland and Wellen Park slabs never stood in surge. The test set is the same: hammer, straightedge, level and hose, threshold, history. Pass, and the deck gets a light knockdown overlay with a matte grit sealer, or a stamped overlay for a stone look; fail, and the resurfacing page says replace. Island decks on the bay side get a penetrating sealer rather than a film, because the base stays damp and film blushes.") + p("Bird Bay and Capri Isles condos resurface common decks in summer, phased."),
        p(f'Overlays on the footprint usually below the city\'s thresholds; confirm through eTRAKiT ({link("/permits/venice/", "rules")}); condo boards; Wellen Park ARC reviews color.'),
        p("A 2016 Wellen Park (Venice side) home with a 560-square-foot builder deck, sound, ponding lightly at the cage screen. Scope: a slot drain sawn into the deck at the low side, pressure-wash and profile, two hairline cracks routed and filled, bond coat, light knockdown overlay in a sand tone, matte sealer with grit, two dry days between coats. ARC approved the color in one meeting; no permit. Cost band: $3,200 to $4,800 including the drain."),
        "How long does a Venice overlay last?", "Eight to fifteen years on a sound mainland or Wellen Park slab with resealing every 2 to 3 years; shorter on the island's bay side where the base stays damp and the sealer works harder.",
        [("/concrete/resurfacing/", "Resurfacing and overlays", "Finishes and process."), ("/compare/cool-deck-vs-pavers/", "Cool deck vs pavers", "The long-term math.")]))

    # ---------------------------------------------------------------- SOUTH VENICE & VENICE GARDENS
    P.append(page("south-venice", "concrete-driveways", "Concrete Driveways in South Venice & Venice Gardens, FL", "Concrete driveway replacement in South Venice and Venice Gardens: $7 to $12 per sq ft, 1950s to 80s block homes on small lots, county permits through the Venice office, septic and well constraints and a worked example.",
        "Concrete driveways in South Venice and Venice Gardens", "Replacing original 1950s to 80s driveways on small platted lots, with the drain field and the well as the two constraints.",
        "What does a concrete driveway cost in South Venice or Venice Gardens?", "About $7 to $12 per square foot installed, so a 420-square-foot driveway on a Venice Gardens lot runs roughly $2,900 to $5,000 plus $800 to $1,700 for demolition and $300 to $800 for the apron under a county right-of-way use permit. No association fee on most streets.",
        p("South Venice and Venice Gardens are unincorporated county on 1950s to 80s platted lots, most with the original 3.5-inch driveway on raw sand and many on septic and well. Replacement means the standard base and slab, sprinkler heads moved off the surface so the iron stays in the lawn, and a site plan that keeps the driveway clear of the drain field, which the county checks. Lots along Lemon Bay and Alligator Creek are AE and get a penetrating sealer; the interior grid is X and dry.") + p("Widening is common on the 80-foot lots but the septic layout decides the side."),
        p(f'County right-of-way use permit and flatwork review through the Venice office ({link("/permits/sarasota-county/", "rules")}); septic setbacks reviewed by the county; no master association.'),
        p("A 1971 Venice Gardens home with a 420-square-foot driveway in five pieces and a rust stripe from the well sprinkler. Scope: demolition, four compacted inches of crushed base, 4-inch 4,000 PSI fiber concrete with joints at 8 feet, widened 3 feet on the side away from the drain field, apron under the county ROW permit, heads moved, penetrating sealer at 28 days. Planning band: $5,000 to $7,500."),
        "Can the driveway go over the septic drain field?", "No. The county's septic rules keep vehicles and slabs off the drain field; the site plan shows the field from the septic permit on file and the driveway stays clear of it, which sometimes decides which side gets widened.",
        [("/concrete/repair/south-venice/", "Repair in South Venice", "When a panel is enough."), ("/guides/well-water-rust-stains/", "Rust stains", "The well.")]))
    P.append(page("south-venice", "concrete-repair", "Concrete Repair in South Venice & Venice Gardens, FL", "Concrete repair in South Venice and Venice Gardens: polyurethane lifting, crack sealing and panel replacement on 1950s to 80s slabs, well-water rust removal, septic-aware work and a worked example.",
        "Concrete repair in South Venice and Venice Gardens", "Lifting and patching original slabs where they're worth it, and an honest line where sixty years of sand have won.",
        "What does concrete repair cost in South Venice?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, panel replacement $400 to $900 per panel, rust removal and resealing $1 to $2 per square foot. On a 3.5-inch 1960s slab in many pieces, the estimate says replacement.",
        p("The repair pattern here is the pattern of every 1950s to 80s block-home neighborhood on Myakka fine sand: driveway panels dropped at the garage, front walks lifted by a pine root or dropped beside a downspout, lanai slabs pitched toward the sliders, all orange from the well. Lifting works on intact slabs once the water is fixed; walks get grinding under half an inch and panel replacement over it; rust gets oxalic cleaning on concrete and heads moved. Lots on septic get repairs planned around the drain field.") + p("Lemon Bay and Alligator Creek lots see enough spray to spall slab edges; a penetrating sealer after the repair slows it."),
        p(f'Repairs without a footprint change generally below county thresholds ({link("/permits/sarasota-county/", "rules")}); septic setbacks apply to any new slab work; public sidewalks are the county\'s.'),
        p("A 1968 South Venice home with a lanai slab dropped 1 inch toward the house and a walk panel lifted by a slash pine. Scope: irrigation leak under the lanai repaired, lanai lifted with polyurethane foam through five holes to restore the pitch, walk panel replaced with a bridge section over the root, joints sealed. One day plus a small pour. Planning range: $1,500 to $2,400."),
        "Why fix the sprinkler before lifting the slab?", "Because the leak is what emptied the sand from under the slab; foam fills the void today and the leak digs a new one by spring. The water comes first on every repair scope here.",
        [("/concrete/driveways/south-venice/", "Driveways in South Venice", "When the slab is past repair."), ("/guides/why-concrete-cracks-sarasota/", "Why concrete cracks", "Base movement.")]))
    P.append(page("south-venice", "pavers-patios-lanais", "Paver Patios & Lanais in South Venice & Venice Gardens, FL", "Paver patios and lanai floors in South Venice and Venice Gardens: $13 to $16 concrete pavers, $20 to $26 travertine per sq ft, small-lot patios on sand, 1970s lanai overlays, septic-aware layouts and a worked example.",
        "Paver patios and lanais in South Venice and Venice Gardens", "Small-lot patios on a real base and travertine over 1970s lanai slabs that still ring solid.",
        "What does a paver patio or lanai cost in South Venice?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 240-square-foot patio runs roughly $3,100 to $3,800 in pavers or $4,800 to $6,200 in stone; a lanai overlay on a sound 1970s slab sits at the low end because there's no excavation. Layouts steer clear of the septic drain field.",
        p("South Venice yards are small and the lots are platted tight, so patios are 200 to 300 square feet and often replace a cracked 1970s slab or a patch of dead grass under a live oak. Pavers on 4 inches of crushed base compacted in two lifts over the wet-season sand, a soldier-course border, a drain or a slope to the swale. Lanai slabs from the 1970s that pass the five tests get travertine or a light paver over them with a perimeter curb; the ones pitched toward the sliders come out. Septic lots keep the patio off the drain field.") + p("No association on most streets; the design is yours."),
        p(f'At-grade patios often below county thresholds; overlays on the footprint usually not permitted work; the 50 percent impervious cap and septic setbacks apply ({link("/permits/sarasota-county/", "rules")}).'),
        p("A 1976 Venice Gardens home with a 12-by-20 lanai slab, sound, sloped correctly, and a bare side yard. Scope: tumbled travertine sand-set over the lanai slab with a perimeter curb and a bullnose step at the slider, plus a 10-by-14 paver patio in the side yard on 4 inches of base with a border, both draining to the swale and clear of the drain field. No permit needed; the septic field was confirmed from the county's record. Budget band: $7,500 to $10,000 for both."),
        "Can a patio go beside the septic tank?", "Beside the tank with the lid accessible, yes; over the drain field, no. The county's septic record shows where both are, and the layout is drawn to it before the estimate.",
        [("/pavers/patios-lanais/", "Paver patios and lanais", "The overlay tests."), ("/concrete/slabs/south-venice/", "Pads in South Venice", "Shed and AC pads.")]))
    P.append(page("south-venice", "concrete-slabs", "Concrete Slabs & Pads in South Venice & Venice Gardens, FL", "Shed, AC, generator and hot-tub pads in South Venice and Venice Gardens: thickness by load, raised pads on wet sand, the county's 100-square-foot shed exemption, septic setbacks and a worked example.",
        "Concrete slabs and pads in South Venice and Venice Gardens", "Small pads on small lots, raised above the wet-season grade and kept off the drain field.",
        "What does a pad cost in South Venice?", "Small pads about $9 to $15 per square foot, so an AC pad runs $350 to $700, a generator pad $600 to $1,400 with anchor bolts to the template, a 10-by-12 shed pad $1,200 to $2,000, and an 8-by-8 hot-tub pad at 6 inches $1,200 to $2,000. Pads sit 2 to 4 inches above grade because these lots hold water in August.",
        p("Pads in South Venice are the honest small jobs: a condenser sinking on a precast block, a generator after the 2024 outages, a shed for the fishing gear, a spa. The ground is Myakka sand with a shallow water table, so every pad gets a compacted subgrade, 4 inches of base, a raised edge and a slope to the swale; hot-tub and boat pads get 6 inches with #4 bar. Sheds of 100 square feet or less follow the county's exemption; the septic drain field is off limits for all of it.") + p("Generator pads are poured to the manufacturer's template with conduit sleeved before the pour."),
        p(f'Sheds of 100 sq ft or less generally exempt; larger pads and any structure on them reviewed through Accela; AC and generator pads ride with the equipment permit; septic setbacks ({link("/permits/sarasota-county/", "rules")}).'),
        p("A 1974 South Venice home: a 22 kW standby generator pad and a 10-by-10 shed pad. Scope: generator pad at 5 inches to the manufacturer's template with anchor bolts and a sleeved conduit, raised 3 inches; shed pad at 4 inches with a thickened edge, raised 3 inches, both on compacted base and sloped to the swale, both clear of the drain field per the county record. Generator permitted with the electrical work; shed exempt at 100 square feet. Cost band: $2,200 to $3,400."),
        "Why raise a pad above the lawn?", "Because South Venice lawns stand in water after an August storm, and a condenser or a generator sitting in it corrodes. Two to four inches above grade with a slope away keeps the equipment dry.",
        [("/concrete/slabs/", "Slabs and pads", "Thickness by load."), ("/concrete/driveways/south-venice/", "Driveways in South Venice", "The larger pour.")]))

    # ---------------------------------------------------------------- NORTH PORT
    P.append(page("north-port", "concrete-driveways", "Concrete Driveways in North Port, FL – Culverts, Swales & Permits", "Concrete driveway replacement in North Port: $7 to $12 per sq ft plus the culvert, the city's Right of Way Use Permit and Public Works inspection, deep-sand base, Wellen Park ARC and a worked example with the culvert included.",
        "Concrete driveways in North Port", "Replacing 1980s to 2000s driveways on GDC lots with the culvert the city sizes and the swale it inspects.",
        "What does a concrete driveway cost in North Port?", "About $7 to $12 per square foot for the driveway plus $1,500 to $5,000 for the culvert crossing when the pipe is replaced, so a 500-square-foot driveway with a new culvert runs roughly $6,000 to $11,000 including demolition. Lots on curbed streets and in Wellen Park skip the culvert line.",
        p("A North Port driveway on the original grid is two projects: the crossing over the roadside swale, which the city permits under its Right of Way Use Permit, sizes the culvert for and inspects after the swale is regraded; and the slab on the lot, on deep Myakka and Immokalee sand that drains fast at the surface and holds water below, which needs 4 to 6 inches of compacted base, a 4,000 PSI fiber-reinforced slab with #3 steel and control joints every 8 feet. Wellen Park's North Port villages have curbed streets, builder driveways and an ARC width rule instead.") + p("Warm Mineral Springs and the Price Boulevard corridor are the oldest slabs."),
        p(f'City Right of Way Use Permit (Culvert/Driveway/Sidewalk/Concrete Slab) and building permit through Click2Gov; swale restoration inspected by Public Works; sealed drawings where the city detail doesn\'t cover the work ({link("/permits/north-port/", "North Port rules")}); Wellen Park ARC ({link("/hoa/wellen-park/", "guide")}).'),
        p("A 1986 home off Price Boulevard with a 500-square-foot driveway cracked in four places and a culvert crushed by a delivery truck. Scope: Right of Way Use Permit, new 15-inch culvert to the city's size, swale regraded both sides, a compacted 4-inch crushed-rock base, four inches of 4,000 PSI concrete, fiber plus #3 rebar, joints sawn at 8 feet, Public Works inspection of the swale before final. Planning band: $7,500 to $11,500 including the culvert."),
        "What if the existing culvert is fine?", "Then the permit covers the driveway crossing and the swale restoration without a new pipe, and the culvert line drops off the estimate. The city decides whether the pipe stays on the site visit.",
        [("/guides/north-port-gdc-lot-driveways/", "GDC lot driveways", "The swale explained."), ("/concrete/repair/north-port/", "Repair in North Port", "When a panel is enough.")]))
    P.append(page("north-port", "concrete-repair", "Concrete Repair in North Port, FL – Settled Driveways & Walks", "Concrete repair in North Port: polyurethane lifting on deep GDC sand, crack sealing, trip-hazard grinding and panel replacement with planning bands, swale-fed settlement and a worked example.",
        "Concrete repair in North Port", "Lifting driveways and walks that settled into deep sand, after the swale or the sprinkler that moved the sand is fixed.",
        "What does concrete repair cost in North Port?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, trip-hazard grinding $150 to $400 per joint, panel replacement $400 to $900 per panel. North Port's deep sand makes lifting a good fit for intact slabs, and a poor one for 1980s driveways cracked into pieces.",
        p("North Port's repair calls are settlement on deep sand: a driveway panel at the garage where the backfill was never compacted, a walk beside a downspout, a lanai corner where the swale behind the house backed up. Polyurethane foam lifts intact slabs in hours once the water is dealt with, and North Port's swales are often the water: a blocked or mis-pitched swale keeps the base wet all summer. Walks get grinding under half an inch; broken panels get replaced with dowels; rust from well water gets oxalic cleaning and heads moved.") + p("Wellen Park and the Woodlands communities are newer and settle less; their calls are builder cracks and drains."),
        p(f'Repairs without a footprint change generally below city thresholds; anything touching the swale or the right-of-way is a Right of Way Use Permit ({link("/permits/north-port/", "rules")}); ARC in the gated communities.'),
        p("A 1992 home off Toledo Blade with a two-car driveway settled 1.25 inches at the garage and a front walk dropped beside a downspout. Scope: downspout extended to the swale, driveway lifted with polyurethane foam through seven holes, walk lifted through two, joints sealed, rust cleaned and heads moved. One day. Planning range: $1,800 to $2,900."),
        "Can a driveway that settled into the swale side be lifted?", "If the slab is intact, yes, after the swale is regraded so it stops feeding water under the edge; if the crossing has broken over a crushed culvert, that's a Right of Way Use Permit and a new crossing, not a lift.",
        [("/concrete/driveways/north-port/", "Driveways in North Port", "The replacement with the culvert."), ("/guides/why-concrete-cracks-sarasota/", "Why concrete cracks", "Base movement.")]))
    P.append(page("north-port", "pavers-pool-decks", "Paver Pool Decks in North Port, FL – Wellen Park & The Woodlands", "Paver pool decks in North Port: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, overlays on Wellen Park and Woodlands builder decks, 1990s deck replacement on the grid, ARC review, city permits and a worked example.",
        "Paver pool decks in North Port", "Travertine over sound builder decks in Wellen Park and the Woodlands, and rebuilds on the 1990s grid.",
        "What does a paver pool deck cost in North Port?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 600-square-foot deck runs roughly $7,800 to $9,600 in pavers or $12,000 to $15,600 in travertine before you add coping or a drain. In Wellen Park the builder deck is usually sound and the pavers go over it; on the 1990s grid the deck usually comes out.",
        p("North Port pool decks split by age: Wellen Park's Islandwalk, Grand Palm and Renaissance and the Woodlands' Cedar Grove and Cypress Falls have builder decks from the 2000s to 2020s that pass the overlay tests and get travertine or light pavers thin-set or sand-set with a perimeter curb and a drain cut in; the Price Boulevard and Toledo Blade grid has 1990s decks poured tight to the shell that get demolished and re-laid on a base. Chlorine pools dominate; the coastal salt rules don't apply. ARC color lists do.") + p("Cages here are big and anchors go into a concrete curb at the cage line."),
        p(f'City building permit through Click2Gov for a new deck; overlays on the footprint usually below thresholds ({link("/permits/north-port/", "rules")}); Wellen Park and Woodlands ARC ({link("/hoa/wellen-park/", "guide")}).'),
        p("A 2015 Islandwalk home with a 620-square-foot builder deck under a cage, sound, ponding at the screen. Scope: linear deck drain installed and tied to the lake-side yard drain, travertine bullnose coping, a sand-set field of tumbled travertine over the slab, held by a perimeter curb, screen-cage anchors set into the curb, polymeric sand, sealing at 30 days. ARC approval three weeks; no city permit for the overlay. Budget band: $13,000 to $17,000."),
        "Does an overlay need a permit in North Port?", "Usually not for an overlay on the same footprint and height; a new deck does, through Click2Gov. The ARC needs the material and color either way.",
        [("/pavers/patios-lanais/", "Paver patios and lanais", "The five tests."), ("/pricing/pool-decks/", "Pool deck cost guide", "Every material.")]))
    P.append(page("north-port", "concrete-slabs", "Concrete Slabs & Pads in North Port, FL – Boat, RV & Shed", "Boat, RV, shed and generator pads on North Port's quarter-acre GDC lots: thickness by load, 6-inch base on deep sand, raised pads, the shed exemption, city permits and a worked example.",
        "Concrete slabs and pads in North Port", "Boat and RV pads on quarter-acre lots with deep sand, sized for the load and raised above the August puddles.",
        "What does a pad cost in North Port?", "Small pads about $9 to $15 per square foot and larger slabs $8 to $12, so an AC pad runs $350 to $700, a 12-by-16 shed pad $1,600 to $2,600, a 12-by-30 boat pad at 6 inches with #4 bar $3,200 to $4,800, and a 14-by-45 RV pad $5,500 to $8,000. The pad is set 2 to 4 inches above grade and sloped to the swale.",
        p("North Port's quarter-acre lots and boat-and-RV culture make pads a steady job: a trailer pad beside the driveway, a shed at the back, a generator after the storms. Deep Myakka and Immokalee sand drains fast at the surface and holds water below, so the subgrade is proof-rolled, the base is 6 inches under anything a vehicle sits on, the pad is raised, and the slope goes to the swale. Pads beside the driveway share the crossing; pads at the back need a path for the truck.") + p("The city's zoning sets accessory-structure setbacks on the lots; Wellen Park's ARCs mostly prohibit visible trailer pads."),
        p(f'City building permit through Click2Gov for slabs and any structure on them; small sheds may fall under an exemption (confirm with the Building Division); pads at the street under the Right of Way Use Permit ({link("/permits/north-port/", "rules")}).'),
        p("A 1998 home off Sumter Boulevard: a 12-by-32 boat pad beside the driveway and a generator pad. Scope: subgrade proof-rolled, 6 inches of base under the boat pad, 6-inch slab with #4 bar on 18-inch centers and a steel plate at the jack point, raised 3 inches and sloped to the swale; generator pad at 5 inches to the template with a sleeved conduit. City permit for the pads. Cost band: $4,500 to $6,500."),
        "Does a boat pad need a permit in North Port?", "Slab work in the city is permitted through the Building Division, and the zoning review checks setbacks and coverage; confirm the current threshold at (941) 429-7044 before pouring. Wellen Park's ARC decides whether a pad is allowed at all.",
        [("/concrete/slabs/", "Slabs and pads", "Thickness by load."), ("/compare/4-inch-vs-6-inch/", "4 or 6 inches", "Why pads get 6.")]))

    # ---------------------------------------------------------------- ENGLEWOOD & MANASOTA KEY
    P.append(page("englewood", "pavers-pool-decks", "Paver Pool Decks in Englewood & Manasota Key, FL – Two Counties", "Paver pool decks in Englewood and on Manasota Key: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, which county permits your street, the key's conservation district and VE zones, 2024 surge lessons and a worked example.",
        "Paver pool decks in Englewood and on Manasota Key", "Lemon Bay and Gulf-front decks built to be flushed and reset, permitted by whichever county your street is in.",
        "What does a paver pool deck cost in Englewood or on Manasota Key?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26; the key adds 5 to 15 percent for logistics and concrete curbs. A 650-square-foot deck runs roughly $8,500 to $10,400 in pavers or $13,000 to $17,000 in stone on the mainland, more on the key, before coping and drains. Charlotte County permits the reset as slab work with a Notice of Commencement over $5,000.",
        p("Englewood's paver deck market is Lemon Bay waterfront and Manasota Key: 1960s to 90s canal homes and cottages that stood in the 2024 surge and rebuilt decks on bases meant to be flushed, with concrete curbs at the seawall, geotextile, lifts and a field that resets. The key is AE and VE, inside its conservation district, with turtle lighting on the Gulf side and salt pools that need annual coping sealing on limestone. Inland Englewood East and Overbrook decks are 1970s to 90s slabs under cages that get pavers over them or a rebuild.") + p("North of the county line, Sarasota County; south of it, Charlotte County, which permits every paver field."),
        p(f'Sarasota County or Charlotte County permit by street ({link("/permits/sarasota-county/", "Sarasota rules")}, {link("/permits/charlotte-county/", "Charlotte rules")}); Manasota Key Conservation District (Sarasota County Code Ch. 54 Art. XXVII); AE and VE; {link("/permits/sea-turtle-lighting/", "turtle lighting")}.'),
        p("A 1974 canal home on the Charlotte side with a 600-square-foot concrete-paver deck that shifted along the seawall in October 2024. Charlotte County permit and NOC (contract over $5,000). Scope: insurer photos, three weeks of drying, field lifted, base rebuilt and flushed, concrete curb at the seawall, pavers rinsed and reset, polymeric sand on a dry day, sealing six weeks later. Planning band: $6,000 to $9,000."),
        "Which county permits a Manasota Key deck?", "The key is split like the town: north of the line, Sarasota County (and the conservation district's rules); south of it, Charlotte County. The Property Appraiser sites for each county show the jurisdiction for any parcel, and the estimate names it on the first line.",
        [("/coastal/post-storm-restoration/", "Post-storm restoration", "The sequence."), ("/areas/charlotte-county/", "Charlotte County", "What changes south of the line.")]))
    P.append(page("englewood", "pavers-repair-storm-restoration", "Paver Repair & Storm Restoration in Englewood & Manasota Key, FL", "Paver repair and post-surge restoration in Englewood and on Manasota Key after Ian, Helene and Milton: $8 to $15 per sq ft affected area, base flush and rebuild, concrete curbs, which county's file it goes in and a worked example.",
        "Paver repair and storm restoration in Englewood and on Manasota Key", "Three surges in two years. The sequence is the same each time: document, drain, rebuild, reset.",
        "What does storm restoration of pavers cost in Englewood?", "About $8 to $15 per square foot of the affected area plus base material and concrete curbs at $12 to $20 per linear foot, so a 350-square-foot seawall-side section runs roughly $2,800 to $5,300 plus the curb. Charlotte County permits larger resets as slab work with a Notice of Commencement over $5,000; Sarasota County generally doesn't for a reset without a footprint change.",
        p("Englewood and Manasota Key took Ian's surge in September 2022 and Helene's and Milton's in 2024. The findings repeat: plastic edge restraint floated at seawalls and on the Gulf side, joint sand gone, bases salted and undermined at the edges, sand and debris over drains, pavers intact. The restoration is the standard sequence with two county files to keep straight. Non-storm repairs are canal-side settling where a seawall weep hole washed the base, and ant-tunneled joints on unsealed decks.") + p("Cottages on the key that are rebuilding elevated get engineered slabs under the house and paver decks beside it."),
        p(f'Charlotte County: permit and NOC for larger resets ({link("/permits/charlotte-county/", "rules")}); Sarasota County: usually no permit for a reset without a footprint change ({link("/permits/sarasota-county/", "rules")}); document first ({link("/guides/hurricane-insurance-documentation/", "insurance guide")}).'),
        p("A 1968 Lemon Bay canal home on the Sarasota side whose 780-square-foot travertine deck dropped 2 inches along 35 feet of seawall in Milton. After documentation and three weeks of drying: 300 square feet lifted, base voids rebuilt in lifts, fresh-water flush, concrete curb along the seawall, travertine rinsed and reset with 12 new pieces, polymeric sand, coping resealed. No permit needed on the Sarasota side; site work documented for the insurer. Planning range: $5,000 to $7,800."),
        "Should the deck be rebuilt differently the third time?", "Only the edge and the base need to change: a concrete curb where the plastic restraint was, geotextile under the base, and a flush-and-reset plan on the care sheet. The pavers themselves have survived three surges already.",
        [("/coastal/storm-season-playbook/", "Storm playbook", "Before June 1."), ("/pavers/repair-storm-restoration/", "Paver repair", "The service.")]))
    P.append(page("englewood", "concrete-driveways", "Concrete Driveways in Englewood, FL – Which County Permits", "Concrete driveway replacement in Englewood: $7 to $12 per sq ft, 1960s to 90s slabs on the county's Myakka soils, which county permits your street (Charlotte permits all flatwork), Boca Royale and Plantation ARC and a worked example.",
        "Concrete driveways in Englewood", "Replacing 1960s to 90s driveways on both sides of the county line, with the permit office decided by the street.",
        "What does a concrete driveway cost in Englewood?", "About $7 to $12 per square foot installed, so a 540-square-foot driveway runs roughly $3,800 to $6,500 plus $1,100 to $2,200 for demolition and the apron: a county right-of-way use permit north of the line, a Charlotte County driveway permit with published fees ($22 zoning review, $310 line and grade) south of it.",
        p("Old Englewood and Englewood East are 1960s to 90s block homes on Myakka fine sand with the standard failed driveways; Boca Royale, Plantation and Oyster Creek are 1980s to 2010s golf and gated communities with builder slabs and ARC review. Replacement is the same slab everywhere: compacted garage strip, 4 to 6 inches of base, 4,000 PSI fiber concrete with #3 bar, an 8-foot joint spacing, apron to the jurisdiction's detail. Lemon Bay lots get the low water-cement mix and a penetrating sealer.") + p("The county line runs through the middle of town; the Property Appraiser sites settle any address."),
        p(f'North: Sarasota County right-of-way use permit and flatwork review ({link("/permits/sarasota-county/", "rules")}); south: Charlotte County driveway permit, NOC over $5,000, line-and-grade inspection ({link("/permits/charlotte-county/", "rules")}); ARC in Boca Royale, Plantation, Oyster Creek.'),
        p("A 1987 Englewood East home on the Charlotte side with a 540-square-foot driveway settled at the garage. Charlotte County driveway permit ($22 zoning review, $310 line and grade) and NOC. Scope: demolition, backfill strip at the garage compacted, 4 inches of base, a fiber 4,000 PSI mix poured 4 inches thick over #3 rebar, joints cut on an 8-foot grid, apron to the county detail, line-and-grade inspection. Budget band: $5,500 to $8,200 including fees."),
        "Why is the permit different three streets away?", "Because the Sarasota-Charlotte county line runs through Englewood, and Charlotte County permits every piece of flatwork with published fees while Sarasota County permits the right-of-way work and reviews the slab. The estimate names the office on its first line.",
        [("/areas/englewood/", "Englewood", "Two counties, one town."), ("/concrete/repair/englewood/", "Repair in Englewood", "When a panel is enough.")]))
    P.append(page("englewood", "concrete-repair", "Concrete Repair in Englewood & Manasota Key, FL", "Concrete repair in Englewood and on Manasota Key: lifting, crack sealing and panel replacement on 1960s to 90s slabs, post-surge void surveys on slabs that stood in salt water, and a worked example.",
        "Concrete repair in Englewood and on Manasota Key", "Settled slabs inland, salt-scaled slabs on the bay, and void surveys on every slab that stood in a surge.",
        "What does concrete repair cost in Englewood?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, spall patching $10 to $18 per square foot, panel replacement $400 to $900 per panel. Slabs that stood in the 2022 or 2024 surges get a void survey before any repair is quoted.",
        p("Inland Englewood repairs are the sand-and-water pattern: settled driveway panels, walks beside downspouts, lanais pitched to the house, lifted with foam after the water is fixed. Lemon Bay and Manasota Key repairs are salt: scaled slab edges and spalled deck coping patched with polymer-modified mortar and sealed, or replaced when rust bleeds through. Every slab on the bay or the key that stood in surge is sounded for voids first; foam fills the ones under intact slabs, and broken or lifted slabs are replaced.") + p("Charlotte County can treat larger repairs as permitted slab work; Sarasota County generally doesn't for repairs without a footprint change."),
        p(f'Sarasota side: repairs generally below thresholds ({link("/permits/sarasota-county/", "rules")}); Charlotte side: larger slab work permitted ({link("/permits/charlotte-county/", "rules")}); storm repairs documented for the insurer and, on the key, the county file.'),
        p("A 1972 Old Englewood home with a lanai slab dropped 3/4 inch toward the sliders and a driveway edge scaling from bay spray. Scope: irrigation leak under the lanai repaired, slab lifted with polyurethane foam through five holes, driveway edge scaling patched with polymer-modified mortar and the driveway sealed with a penetrating product. One day. Cost band: $1,600 to $2,600."),
        "Can a driveway that stood in surge just be resealed?", "After a void survey and a fresh-water rinse, if it's intact and rings solid, yes; if it sounds hollow at the edges, the voids are foamed first. Sealing over a void is the repair you pay for twice.",
        [("/coastal/post-storm-restoration/", "Post-storm restoration", "Slabs after surge."), ("/coastal/salt-and-concrete/", "Salt and concrete", "Why edges scale.")]))

    # ---------------------------------------------------------------- PORT CHARLOTTE
    P.append(page("port-charlotte", "pavers-pool-decks", "Paver Pool Decks in Port Charlotte, FL – Canal Lots & Permits", "Paver pool decks in Port Charlotte: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, Charlotte County's all-flatwork permit and fees, canal-front salt in Gulf Cove and South Gulf Cove, 1970s deck replacement and a worked example.",
        "Paver pool decks in Port Charlotte", "Salt-tolerant decks for the canal lots and rebuilds for the 1970s grid, permitted by Charlotte County with a Notice of Commencement.",
        "What does a paver pool deck cost in Port Charlotte?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 600-square-foot deck runs roughly $7,800 to $9,600 in pavers or $12,000 to $15,600 in stone; coping and drains are separate lines, plus Charlotte County's permit fees ($22 zoning review, $22 or $90 slab review, $310 line and grade) and a recorded Notice of Commencement.",
        p("Port Charlotte's canal neighborhoods (Gulf Cove, South Gulf Cove, Grassy Point, Harbour Heights) want decks that handle brackish spray and salt pools: dense concrete pavers or porcelain, or travertine with the annual coping rule, on a base with a concrete curb at the seawall. The 1970s and 80s grid (Section 15, Murdock, Deep Creek) has decks poured tight to the shell that get demolished and re-laid. Charlotte County permits every paver deck and inspects it; the NOC goes on record before the first inspection.") + p("Cages are original aluminum on the grid and anchors go into a new curb."),
        p(f'Charlotte County permit for all flatwork including pavers, NOC over $5,000, published fees, termite treatment within a foot of the house ({link("/permits/charlotte-county/", "rules")}); ARC in Riverwood, Heritage Oak Park and the South Gulf Cove associations.'),
        p("A 1985 South Gulf Cove canal home with a 640-square-foot concrete deck spalled at the coping from a salt pool. Charlotte County permit and NOC. Scope: demolition, base rebuilt in lifts over geotextile, linear drain, porcelain bullnose coping, light 2 cm porcelain field on a re-screeded bed, concrete curb at the seawall and cage line, polymeric sand. No sealing line on the care sheet. Planning band: $16,500 to $21,000 including fees."),
        "Why porcelain on a Port Charlotte canal?", "Because the pool is salt, the canal is brackish and the owner is seasonal: porcelain needs no sealing, doesn't etch and doesn't flake at the waterline. Travertine would need an annual coping seal the owner isn't here to schedule.",
        [("/compare/travertine-vs-shellstone-vs-porcelain/", "Travertine vs shellstone vs porcelain", "Salt and maintenance."), ("/areas/charlotte-county/", "Charlotte County", "Fees and rules.")]))
    P.append(page("port-charlotte", "pavers-driveways", "Paver Driveways in Port Charlotte, FL – Permit, Fees & Swales", "Paver driveways in Port Charlotte: $14 to $22 per sq ft, Charlotte County's driveway and ROW permits with published fees, GDC swale crossings, canal-front sealing and a worked example.",
        "Paver driveways in Port Charlotte", "Herringbone driveways on the GDC grid, with the swale crossing and Charlotte County's line-and-grade inspection.",
        "What does a paver driveway cost in Port Charlotte?", "About $14 to $22 per square foot installed, so a 520-square-foot driveway runs roughly $7,300 to $11,400 plus demolition, the swale crossing and Charlotte County's fees ($22 zoning review, $310 line and grade at issuance, $90 if the work is only in the right-of-way) and a recorded Notice of Commencement over $5,000.",
        p("Port Charlotte's grid was platted by GDC with roadside swales, so a paver driveway includes the crossing: a culvert the county sizes, ends set back from the frontage line, the swale regraded, and a line-and-grade inspection. On the lot, 6 inches of compacted base in lifts over Myakka and Immokalee sand, herringbone for the tires, a curb in concrete along the street edge. Canal lots in Gulf Cove and Grassy Point see brackish spray and seal every 18 to 24 months; the interior grid seals every 2 to 3 years.") + p("Riverwood and Heritage Oak Park keep color lists; the grid doesn't."),
        p(f'Charlotte County residential driveway permit (or ROW permit if only in the right-of-way), all flatwork including pavers permitted and inspected, NOC over $5,000, published fees ({link("/permits/charlotte-county/", "rules")}); ARC in the gated communities.'),
        p("A 1981 Section 15 home with a 520-square-foot cracked driveway and a swale crossing with no culvert. Charlotte County permit and NOC. Scope: demolition, culvert to the county's size, swale regraded, 6 inches of base in three lifts, herringbone field in a light gray blend with a charcoal border, concrete curb at the street, polymeric sand, line-and-grade inspection, sealing at 30 days. Planning range: $10,000 to $14,500 including the culvert and fees."),
        "Does Charlotte County inspect a paver driveway?", "Yes; the county states that all flatwork including pavers requires a permit and inspections, and the crossing gets a line-and-grade inspection. The job card lists what's inspected and when.",
        [("/concrete/driveways/port-charlotte/", "Concrete driveways in Port Charlotte", "The poured alternative."), ("/guides/north-port-gdc-lot-driveways/", "GDC lot driveways", "The swale explained; same platting.")]))
    P.append(page("port-charlotte", "concrete-driveways", "Concrete Driveways in Port Charlotte, FL – Culverts & County Fees", "Concrete driveway replacement in Port Charlotte: $7 to $12 per sq ft plus the culvert, Charlotte County's driveway permit and published fees, Notice of Commencement, the GDC swale and a worked example.",
        "Concrete driveways in Port Charlotte", "Replacing 1970s and 80s driveways on the GDC grid with the culvert crossing the county sizes and inspects.",
        "What does a concrete driveway cost in Port Charlotte?", "About $7 to $12 per square foot for the driveway plus $1,500 to $5,000 for a culvert crossing when the pipe is replaced, so a 480-square-foot driveway with a new culvert runs roughly $6,000 to $10,500 including demolition, plus Charlotte County's fees ($22 zoning review, $310 line and grade) and a recorded Notice of Commencement.",
        p("The 1970s and 80s block homes across Section 15, the Murdock grid, Deep Creek and Harbour Heights sit on their original driveways, cracked and settled, and cross swales that were shallow when GDC dug them. Replacement is the crossing (culvert sized by the county, swale regraded, line-and-grade inspection) plus the slab on Myakka and Immokalee sand: compacted garage strip, 4 to 6 inches of base, 4,000 PSI fiber concrete with #3 bar, joints at 8 feet. Canal lots get the low water-cement mix and a penetrating sealer.") + p("Termite treatment applies to flatwork within a foot of the house under the county's rules."),
        p(f'Charlotte County residential driveway permit, ROW permit for the crossing where applicable, NOC over $5,000, line-and-grade inspection, published fees ({link("/permits/charlotte-county/", "rules")}).'),
        p("A 1979 Section 15 home with a 480-square-foot driveway settled at the garage and a swale crossing with no culvert. Charlotte County permit and NOC. Scope: culvert to the county's size, swale regraded, demolition, the soft strip at the garage dug out and compacted, 4 inches of base, a 4-inch fiber-reinforced 4,000 PSI slab, control joints every 8 feet, line-and-grade inspection. Budget band: $7,000 to $10,500 including the culvert and fees."),
        "What is the $310 line-and-grade fee for?", "The county's survey and inspection of the crossing's line and grade so the swale keeps draining; it's charged at issuance for driveway permits, or $90 for right-of-way-only work. It's on the county's published fee page.",
        [("/pavers/driveways/port-charlotte/", "Paver driveways in Port Charlotte", "The other answer."), ("/concrete/repair/port-charlotte/", "Repair in Port Charlotte", "When a panel is enough.")]))
    P.append(page("port-charlotte", "concrete-repair", "Concrete Repair in Port Charlotte, FL – Settled Slabs & Salt", "Concrete repair in Port Charlotte: polyurethane lifting on GDC sand, crack sealing, trip-hazard grinding, canal-front spall patching, Charlotte County's approach to repair permits and a worked example.",
        "Concrete repair in Port Charlotte", "Lifting settled driveways and walks on the grid, and patching salt-scaled slabs on the canals.",
        "What does concrete repair cost in Port Charlotte?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, trip-hazard grinding $150 to $400 per joint, spall patching $10 to $18 per square foot, panel replacement $400 to $900 per panel. Charlotte County may treat larger slab repairs as permitted work; the estimate says when.",
        p("Port Charlotte's repair calls are settlement on the grid (driveway panels at the garage, walks beside downspouts, lanais that lost their pitch) and salt on the canals (scaled edges, spalled coping in Gulf Cove and Grassy Point). Foam lifting handles intact slabs once the swale or the sprinkler is fixed; grinding handles trip hazards under half an inch; polymer-modified patches and a penetrating sealer handle scaling until rust shows through. The 1970s slabs broken into pieces are replaced, and the estimate says so.") + p("Slabs that stood in Ian's surge on the harbor side are sounded before any repair."),
        p(f'Charlotte County can require a permit for larger slab repairs; confirm at (941) 743-1200 ({link("/permits/charlotte-county/", "rules")}); public sidewalks and swales are the county\'s.'),
        p("A 1983 Deep Creek home with a two-car driveway settled 1.25 inches at the garage and a lanai corner dropped where a pool overflow discharged. Scope: overflow line extended to the yard drain, driveway lifted with polyurethane foam through seven holes, lanai corner lifted through two, joints sealed. One day. Cost band: $1,700 to $2,800."),
        "Does Charlotte County require a permit to lift a slab?", "Foam lifting without a footprint change isn't usually treated as new flatwork, but the county permits slab work broadly; the estimate names the office's answer for your scope, and the number to confirm is (941) 743-1200.",
        [("/concrete/driveways/port-charlotte/", "Driveways in Port Charlotte", "When the slab is past repair."), ("/coastal/salt-and-concrete/", "Salt and concrete", "Canal-side scaling.")]))

    # ---------------------------------------------------------------- ROTONDA WEST
    P.append(page("rotonda-west", "pavers-pool-decks", "Paver Pool Decks in Rotonda West, FL – Under the Cage", "Paver pool decks in Rotonda West: concrete pavers $13 to $16 and travertine $20 to $26 per sq ft, 1990s deck replacement under cages, Charlotte County permits and fees, Rotonda West Association review and a worked example.",
        "Paver pool decks in Rotonda West", "Replacing 1990s cool-deck pool decks under Rotonda's cages, permitted by Charlotte County and reviewed by the association.",
        "What does a paver pool deck cost in Rotonda West?", "Concrete pavers about $13 to $16 per square foot and travertine $20 to $26, so a 620-square-foot deck runs roughly $8,000 to $9,900 in pavers or $12,400 to $16,100 in stone before coping and drains, plus Charlotte County's permit fees and a recorded Notice of Commencement over $5,000. The Rotonda West Association reviews the color.",
        p("Rotonda West is a wheel of 1970s to 2000s single-story homes with pool cages, most with cool-deck overlays from the 1990s now delaminating, over flatwoods sand ringed by canals that keep the water table near the surface. Decks that fail sounding come out and are re-laid on 4 inches of compacted base with a drain, light concrete pavers or travertine, a concrete curb at the cage line for the anchors; decks that pass get pavers over them. Chlorine pools dominate; the canal lots see enough spray for the 2-year sealing cycle.") + p("The association's deed restrictions cover exterior changes across every section."),
        p(f'Charlotte County permit for all flatwork including pavers, NOC over $5,000, published fees ({link("/permits/charlotte-county/", "rules")}); Rotonda West Association review ({link("/hoa/", "HOA guides")}).'),
        p("A 1995 home in the Pinehurst section with a 620-square-foot cool-deck deck delaminating under the cage, hollow at the coping. Charlotte County permit and NOC; association approval on the color. Scope: demolition, a 4-inch compacted limerock base, linear drain, concrete bullnose coping, light concrete pavers in a modular pattern, concrete curb at the cage line, cage anchors reset, polymeric joint sand and a sealer 30 days later. Planning band: $9,000 to $12,500 including fees."),
        "Does the association review a deck inside the cage?", "Rotonda West's deed restrictions cover exterior changes and most sections review material and color even inside a cage; submit the sample with the county permit number and it's usually a one-meeting approval.",
        [("/compare/cool-deck-vs-pavers/", "Cool deck vs pavers", "The 1990s overlay question."), ("/areas/rotonda-west/", "Rotonda West", "Rules and ground.")]))
    P.append(page("rotonda-west", "pavers-driveways", "Paver Driveways in Rotonda West, FL – Association & County", "Paver driveways in Rotonda West: $14 to $22 per sq ft, Charlotte County driveway permit and fees, Rotonda West Association color review, 6-inch base on canal-ringed sand and a worked example.",
        "Paver driveways in Rotonda West", "Herringbone driveways in association-approved colors on a base built for a canal-side water table.",
        "What does a paver driveway cost in Rotonda West?", "About $14 to $22 per square foot installed, so a 560-square-foot driveway runs roughly $7,800 to $12,300 plus demolition and Charlotte County's fees ($22 zoning review, $310 line and grade) with a recorded Notice of Commencement over $5,000. The association's approved colors decide the blend.",
        p("Rotonda's driveways are 1970s to 2000s builder slabs on Myakka sand with a canal-fed water table, mostly settled and cracked, on curbed streets without swales in most sections. Replacement in pavers means a 6-inch base compacted in lifts over geotextile, herringbone for the tires, a poured curb where the field meets the street, and a blend from the association's list, usually light tan or gray with a contrasting soldier course. Sealing runs every 2 to 3 years, closer to 2 on canal lots.") + p("Charlotte County permits and inspects every paver field."),
        p(f'Charlotte County residential driveway permit, inspections, NOC over $5,000, published fees ({link("/permits/charlotte-county/", "rules")}); Rotonda West Association review of exterior changes.'),
        p("A 1992 home in the Oakland Hills section with a 560-square-foot builder driveway cracked at the garage. Charlotte County permit and NOC; association approval on a light tan blend. Scope: demolition, compaction of the backfill along the garage, a 6-inch crushed base in three lifts on geotextile, 45-degree herringbone with a charcoal soldier course, a concrete edge at the street line, polymeric sand, line-and-grade inspection, sealing at 30 days. Planning range: $10,000 to $14,000 including fees."),
        "Which comes first in Rotonda, the county permit or the association?", "Submit both at once; the association usually wants the county permit number on its form, and the county doesn't ask about the association. Approvals overlap and the start date follows the later one.",
        [("/concrete/driveways/rotonda-west/", "Concrete driveways in Rotonda West", "The poured alternative."), ("/hoa/", "HOA guides", "The packet.")]))
    P.append(page("rotonda-west", "concrete-driveways", "Concrete Driveways in Rotonda West, FL – Permit, Fees & Review", "Concrete driveway replacement in Rotonda West: $7 to $12 per sq ft, Charlotte County driveway permit with published fees and inspections, Rotonda West Association review, canal-ringed sand base and a worked example.",
        "Concrete driveways in Rotonda West", "Replacing 1970s to 2000s builder slabs on a compacted base, permitted and inspected by Charlotte County, reviewed by the association.",
        "What does a concrete driveway cost in Rotonda West?", "About $7 to $12 per square foot installed, so a 560-square-foot driveway runs roughly $3,900 to $6,700 plus $1,100 to $2,200 for demolition and Charlotte County's fees ($22 zoning review, $310 line and grade) with a recorded Notice of Commencement over $5,000. Most Rotonda streets are curbed, so the culvert line rarely applies.",
        p("Rotonda's builder driveways were poured on Myakka fine sand next to canals that keep the base wet, with long panels and no compaction at the garage; they've settled and cracked. Replacement is the standard slab: garage strip compacted, 4 to 6 inches of base by how wet the section sits, 4,000 PSI fiber concrete with #3 bar, control joints every 8 feet, broom finish in natural gray, which the association accepts everywhere. Canal lots add a penetrating sealer. The county inspects line and grade at the street even without a swale.") + p("Cape Haze peninsula sections nearer the water get the low water-cement mix."),
        p(f'Charlotte County residential driveway permit, inspections, NOC over $5,000, published fees, termite treatment within a foot of the house ({link("/permits/charlotte-county/", "rules")}); Rotonda West Association review.'),
        p("A 1988 home in the Broadmoor section with a 560-square-foot driveway settled 1 inch at the garage and cracked across three panels. Charlotte County permit and NOC; association notified. Scope: demolition, backfill strip at the garage compacted, 4 inches of base, 4 inches of fiber-reinforced 4,000 PSI concrete with #3 steel, joints sawn at 8 feet, line-and-grade inspection, penetrating sealer at 28 days. Budget band: $5,500 to $8,500 including fees."),
        "Does a like-for-like concrete driveway need association approval?", "Rotonda West reviews exterior changes; a same-footprint, same-material replacement is usually a notification rather than a design review, but the association's current rule decides. Ask before demolition.",
        [("/pavers/driveways/rotonda-west/", "Paver driveways in Rotonda West", "The other answer."), ("/concrete/repair/rotonda-west/", "Repair in Rotonda West", "When a panel is enough.")]))
    P.append(page("rotonda-west", "concrete-repair", "Concrete Repair in Rotonda West, FL – Lifting & Cracks", "Concrete repair in Rotonda West: polyurethane lifting on canal-side sand, crack sealing, trip-hazard grinding and panel replacement with planning bands, the water-first rule and a worked example.",
        "Concrete repair in Rotonda West", "Lifting settled driveways and lanais on sand the canals keep wet, after the water that moved it is fixed.",
        "What does concrete repair cost in Rotonda West?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, trip-hazard grinding $150 to $400 per joint, panel replacement $400 to $900 per panel. Canal lots settle more than the interior of the circle because the base never fully dries.",
        p("Rotonda's repair pattern is settlement fed by water: canal-side lots with a base that stays saturated, downspouts onto driveway edges, pool overflows onto lanai corners, sprinkler lines leaking under walks. Foam lifting restores intact slabs in hours once the water is redirected; walks get grinding under half an inch; broken panels get replaced with dowels; the 1970s slabs in many pieces get replaced. Charlotte County may treat larger slab repairs as permitted work.") + p("Rust from well-water irrigation shows up in the sections still on wells."),
        p(f'Charlotte County can require a permit for larger slab repairs; confirm at (941) 743-1200 ({link("/permits/charlotte-county/", "rules")}); Rotonda West Association for visible changes.'),
        p("A 1996 home in the Long Meadow section with a lanai slab dropped 3/4 inch at the canal-side corner and a driveway panel dropped half an inch at the garage. Scope: pool overflow line extended to the yard drain, lanai corner lifted with polyurethane foam through three holes, driveway panel lifted through four, joints sealed. Half a day. Cost band: $1,400 to $2,300."),
        "Why do canal-side lanais settle more than the street side?", "Because the base on the canal side sits closer to the water table and never dries, so any added water (an overflow, a downspout) moves sand out from under the slab faster. Redirecting the water is the repair; the foam is the finish.",
        [("/concrete/driveways/rotonda-west/", "Driveways in Rotonda West", "When the slab is past repair."), ("/guides/why-concrete-cracks-sarasota/", "Why concrete cracks", "Base movement.")]))

    # ---------------------------------------------------------------- PLACIDA, GROVE CITY & CAPE HAZE
    P.append(page("placida", "pavers-pool-decks", "Paver Pool Decks in Placida & Cape Haze, FL – Waterfront Salt", "Paver pool decks in Placida, Grove City and Cape Haze: concrete pavers $13 to $16, travertine $20 to $26, porcelain higher per sq ft, Lemon Bay and Gasparilla Sound salt, AE and VE waterfront, Charlotte County permits and a worked example.",
        "Paver pool decks in Placida, Grove City and Cape Haze", "Waterfront decks on filled lots, built with concrete curbs and materials that don't mind salt.",
        "What does a paver pool deck cost in Placida or Cape Haze?", "Concrete pavers about $13 to $16 per square foot, travertine $20 to $26 and 2 cm porcelain $22 to $32, so a 700-square-foot waterfront deck runs roughly $9,000 to $11,000 in pavers, $14,000 to $18,000 in stone or $15,500 to $22,500 in porcelain before coping and drains, plus Charlotte County's fees and a Notice of Commencement. Salt pools push the choice toward porcelain or dense pavers.",
        p("Placida and Cape Haze decks sit on sand and shell fill on Lemon Bay, Gasparilla Sound and the canals, in AE and VE, with boat lifts at the seawall and salt on everything. The base is built to be flushed: geotextile, lifts, a concrete curb at the seawall and the cage line, a field that resets. Materials are chosen by the pool and the owner's presence: porcelain or dense concrete pavers for salt pools and seasonal owners, travertine for owners who'll seal the coping every year. The Cape Haze golf communities are inland and review color.") + p("Charlotte County permits every paver deck and inspects it."),
        p(f'Charlotte County permit for all flatwork including pavers, NOC over $5,000, published fees ({link("/permits/charlotte-county/", "rules")}); AE and VE on the water ({link("/permits/flood-zones-50-percent-rule/", "flood page")}); ARC in the Cape Haze communities.'),
        p("A 2006 waterfront home on the Cape Haze peninsula with a 720-square-foot travertine deck, coping flaking from a salt pool, field sound. Charlotte County permit (coping replacement as slab work). Scope: coping replaced in porcelain bullnose mortar-set on the beam, field cleaned and re-sanded, penetrating sealer, concrete curb added at the seawall where plastic restraint had lifted in 2024. Planning band: $4,500 to $7,000 including fees."),
        "Should a seasonal owner in Placida pick travertine?", "Only with a property manager who'll schedule the annual coping sealing on a salt pool; otherwise porcelain or dense concrete pavers, which need nothing between visits. The estimate asks the question before the sample is picked.",
        [("/compare/travertine-vs-shellstone-vs-porcelain/", "Travertine vs shellstone vs porcelain", "Salt and maintenance."), ("/guides/snowbird-project-guide/", "Snowbird guide", "Managing from away.")]))
    P.append(page("placida", "pavers-driveways", "Paver Driveways in Placida & Cape Haze, FL – Waterfront Lots", "Paver driveways in Placida, Grove City and Cape Haze: $14 to $22 per sq ft, Charlotte County driveway permit and fees, salt cycle on the sound, golf-community ARC review and a worked example.",
        "Paver driveways in Placida, Grove City and Cape Haze", "Herringbone driveways on filled waterfront lots and golf-community lots, sealed on the coastal cycle.",
        "What does a paver driveway cost in Placida?", "About $14 to $22 per square foot installed, so a 600-square-foot driveway runs roughly $8,400 to $13,200 plus demolition and Charlotte County's fees ($22 zoning review, $310 line and grade) with a recorded Notice of Commencement over $5,000. Waterfront lots seal every 18 to 24 months; inland Cape Haze every 2 to 3 years.",
        p("Placida's waterfront driveways sit on sand and shell fill that drains fast and carries salt from the sound; the Cape Haze golf communities are 1980s to 2010s homes on the county's Myakka soils with ARC color lists. Both get six inches of crushed base placed and compacted in lifts over geotextile, herringbone for the tires, a curb in concrete along the street edge, and a blend light enough to stay cool. Grove City's older streets have swale crossings the county sizes and inspects.") + p("Charlotte County permits and inspects every paver driveway."),
        p(f'Charlotte County residential driveway permit (or ROW permit if only in the right-of-way), inspections, NOC over $5,000, published fees ({link("/permits/charlotte-county/", "rules")}); ARC in the Cape Haze communities.'),
        p("A 1998 Cape Haze golf-community home with a 600-square-foot builder driveway cracked at the garage. Charlotte County permit and NOC; ARC approval on a light gray blend. Scope: demolition, the soft strip at the garage dug out and compacted, 6 inches of base in three lifts over geotextile, herringbone with a charcoal soldier course, concrete curb at the street, polymeric sand, line-and-grade inspection, sealing at 30 days. Planning range: $10,500 to $15,000 including fees."),
        "How far is Placida from the crew's base and does it change the price?", "About 35 miles and 55 to 65 minutes from Sarasota; the four scheduled services carry that drive in their normal pricing, and larger jobs are grouped so mobilization is shared. Other services here are quoted case by case.",
        [("/concrete/driveways/placida/", "Concrete driveways in Placida", "The poured alternative."), ("/pavers/sealing/", "Sealing", "The coastal cycle.")]))
    P.append(page("placida", "concrete-driveways", "Concrete Driveways in Placida, Grove City & Cape Haze, FL", "Concrete driveway replacement in Placida, Grove City and Cape Haze: $7 to $12 per sq ft, Charlotte County permit and fees, Grove City swale crossings, salt-mix on the sound, ARC review and a worked example.",
        "Concrete driveways in Placida, Grove City and Cape Haze", "Replacing older slabs in Grove City and builder slabs in Cape Haze, with the county's permit and the sound's salt in mind.",
        "What does a concrete driveway cost in Placida or Grove City?", "About $7 to $12 per square foot installed, so a 520-square-foot driveway runs roughly $3,600 to $6,200 plus $1,000 to $2,100 for demolition, $1,500 to $5,000 for a culvert crossing on Grove City's swale streets, and Charlotte County's fees ($22 zoning review, $310 line and grade) with a recorded Notice of Commencement.",
        p("Grove City's 1960s to 80s streets have the original slabs and swale crossings; Cape Haze's golf communities have 1980s to 2010s builder slabs; the Placida waterfront has short driveways on fill. All get the standard slab on a compacted base with an 8-foot joint spacing, and waterfront lots get the low water-cement mix and a penetrating sealer for spray off the sound. The county sizes any culvert and inspects line and grade at the street.") + p("ARC review in the Cape Haze communities is mostly a notification for like-for-like concrete."),
        p(f'Charlotte County residential driveway permit, ROW permit for crossings, inspections, NOC over $5,000, published fees, termite treatment within a foot of the house ({link("/permits/charlotte-county/", "rules")}).'),
        p("A 1976 Grove City home with a 520-square-foot driveway in pieces and a swale crossing with a collapsed pipe. Charlotte County permit and NOC. Scope: culvert to the county's size, swale regraded, demolition, 4 inches of base, 4-inch 4,000 PSI fiber concrete with #3 bar, joints cut on an 8-foot grid, line-and-grade inspection, penetrating sealer at 28 days (a block from Lemon Bay). Budget band: $6,500 to $10,000 including the culvert and fees."),
        "Does the sound's salt reach a driveway a block inland?", "On windy days, yes; scaling at the driveway's street edge is common a block from Lemon Bay and Gasparilla Sound. The low water-cement mix and a penetrating sealer are cheap insurance there.",
        [("/coastal/salt-and-concrete/", "Salt and concrete", "How spray scales a slab."), ("/concrete/repair/placida/", "Repair in Placida", "When a panel is enough.")]))
    P.append(page("placida", "concrete-repair", "Concrete Repair in Placida, Grove City & Cape Haze, FL", "Concrete repair in Placida, Grove City and Cape Haze: salt-scaled edges patched and sealed, settled slabs lifted, lift-pad and dock-approach repairs on the upland side, Charlotte County rules and a worked example.",
        "Concrete repair in Placida, Grove City and Cape Haze", "Salt scaling on the waterfront, settlement inland, and lift pads on the upland side of the seawall.",
        "What does concrete repair cost in Placida?", "Polyurethane lifting about $500 to $2,500 per settled area, crack routing and sealing $8 to $20 per linear foot, spall patching $10 to $18 per square foot, panel replacement $400 to $900 per panel, and a new 6-inch boat-lift motor pad $1,200 to $2,200. Anything over the water or on the seawall itself is marine work and isn't quoted here.",
        p("Placida's waterfront repairs are salt: scaled slab edges, spalled coping, tilted lift-motor pads on fill that settled. Patches are polymer-modified and sealed; pads are replaced at 6 inches on compacted base; slabs with rust bleeding through are replaced. Grove City and Cape Haze inland repairs are the settlement pattern, lifted after the water is fixed. Slabs on the sound that stood in the 2024 surge are sounded for voids first.") + p("Seawall caps, docks and anything waterward of the wall are marine construction with their own license and permit."),
        p(f'Charlotte County may treat larger slab repairs as permitted work; confirm at (941) 743-1200 ({link("/permits/charlotte-county/", "rules")}); marine work excluded from this site\'s scope.'),
        p("A 2001 waterfront home on the Cape Haze peninsula with a boat-lift motor pad tilted 2 inches on settled fill and a scaled driveway edge. Scope: old pad removed, subgrade compacted, new 6-inch pad with #4 bar on compacted base raised 3 inches, conduit sleeved; driveway edge patched with polymer-modified mortar and the driveway sealed with a penetrating product. Charlotte County permit for the pad. Cost band: $2,200 to $3,600 including fees."),
        "Can the seawall cap be repaired with the pad?", "No. The cap is marine construction under a different license and permit; the pad and the driveway on the upland side are the concrete work quoted here, and the estimate says where the line is.",
        [("/concrete/slabs/", "Slabs and pads", "Lift and dock-approach pads."), ("/coastal/post-storm-restoration/", "Post-storm restoration", "Slabs after surge.")]))
    return P
