# -*- coding: utf-8 -*-
"""Guides hub, fourteen guides and Ask the Estimator."""
from _h import cap, sec, p, ul, ol, table, note, faq_block, cta, reviewed, link, ext, facts, cards

GUIDES = [
    ("why-concrete-cracks-sarasota", "Why concrete cracks in Sarasota", "Shrinkage, base movement and late joints on Myakka sand."),
    ("cure-times-and-rain", "Cure times, rain and when you can drive on it", "What rain in the first two hours does, and the 24-hour, 7-day and 28-day marks."),
    ("snowbird-project-guide", "The snowbird project guide", "Running a driveway or deck job from out of state, with a November deadline."),
    ("deposits-and-warranties", "Deposits, contracts and warranties", "What Florida law says a deposit and a written contract should look like."),
    ("verify-contractor-license-sarasota", "How to verify a contractor in Sarasota County", "State license, county competency card, registration, bond and insurance."),
    ("well-water-rust-stains", "Rust stains from well-water irrigation", "Why driveways turn orange east of I-75 and how to remove and prevent it."),
    ("polymeric-sand-weeds-ants", "Polymeric sand, weeds and ants", "What joint sand does, when it's replaced, and why weeds mean the sand is gone."),
    ("efflorescence", "Efflorescence on new pavers", "The white haze, its timeline, and why sealing early traps it."),
    ("permeable-pavers-impervious-limit", "Permeable pavers and the 50% impervious limit", "Sarasota County's cap on RSF lots and the paver system that gets around it."),
    ("golf-cart-paths", "Golf-cart paths and second driveways", "What communities and cities say about a cart pad at the street."),
    ("north-port-gdc-lot-driveways", "Driveways on North Port GDC lots", "Swales, culverts, deep sand and the city's Right of Way Use Permit."),
    ("condo-pool-deck-boards", "A pool deck calendar for condo boards", "Twelve months from reserve study to reopening, with bids that compare."),
    ("hurricane-insurance-documentation", "Documenting hardscape damage for an insurance claim", "What to photograph, when, and how to separate site work from the building."),
    ("ask-the-estimator", "Ask the Estimator", "Real questions from local homeowners, answered weekly."),
]


def pg(slug, title, meta, h1, lede, body, faq=None, feed=False):
    return {"route": f"/guides/{slug}/" if slug else "/guides/", "title": title, "meta_description": meta, "h1": h1, "kicker": "Guide", "lede": lede,
            "breadcrumbs": [("Home", "/"), ("Guides", "/guides/"), (h1[:40], None)] if slug else [("Home", "/"), ("Guides", None)],
            "body_html": body, "faq": faq or [], "article": True, "feed_item": feed}


def hub():
    body = p("Guides answer the questions that don't fit a service, a permit or a comparison page. Each one is written for Sarasota County's ground and rules, cites its sources, and links the next commercial step.")
    body += cards([(f"/guides/{s}/", t, x) for s, t, x in GUIDES])
    body += reviewed("September 10, 2026")
    return pg("", "Guides: Concrete & Pavers on the Sarasota Coast", "Fourteen guides for Sarasota County homeowners: why concrete cracks here, cure and rain, snowbird projects, deposits and warranties, verifying contractors, rust stains, polymeric sand, efflorescence, permeable pavers, golf carts, GDC lots, condo boards and insurance claims.",
              "Guides for concrete and pavers on the Sarasota coast", "Fourteen answers to the questions between the service pages, plus a weekly log of real ones.", body)


def cracks():
    faq = [("Why does concrete crack in Sarasota?", "Three reasons, in order: shrinkage as the slab dries in heat without joints cut in time; base movement when water pumps fines out of Myakka sand under an uncompacted base; and loads a 3.5-inch 1960s slab was never built for. Salt and heat get blamed; joints and base are the usual culprits."),
           ("What does proper base prep look like on Myakka fine sand?", "Subgrade dug to firm material and proof-rolled, geotextile where it pumps, 4 to 6 inches of crushed limerock or recycled concrete placed in lifts of 3 inches or less and compacted with a plate compactor to refusal, pitched 1/8 inch per foot to where the water is supposed to go."),
           ("Are hairline cracks a defect?", "Hairline shrinkage cracks that don't offset are normal in concrete and are why joints exist; a crack with a step, or a pattern of cracks across a panel, is a base problem.")]
    body = facts([("Cause 1", "Shrinkage without timely joints"), ("Cause 2", "Base movement from water on sand"), ("Cause 3", "Loads beyond the slab's design"), ("Defense", "Same-day joints, compacted base, 4 in. and 4,000 PSI")])
    body += cap("Why does concrete crack in Sarasota?",
                "Because concrete shrinks as it dries and a 91-degree afternoon dries it fast; if control joints aren't cut the same day at 8 to 10 feet, the slab picks its own crack lines. Because Myakka and EauGallie sands lose fines to water and an uncompacted base drops, taking the slab with it. And because thousands of 1950s to 70s driveways were poured at 3 to 3.5 inches with no base and no joints and have carried SUVs for decades.",
                p("The USDA describes Myakka fine sand as poorly drained with a seasonal high water table within 10 inches for two to six months; NOAA's normals put July and August highs above 91 degrees. Those two facts explain most of the cracks in the county."))
    body += sec("Shrinkage", p("Concrete loses water as it cures and shrinks about 1/16 inch per 10 feet. It will crack; the only question is where. Control joints cut to a quarter of the slab depth at 8 to 10 feet, in panels close to square, give it a place. Cut the next morning in July and the slab has already chosen. Fiber reduces the first-hours plastic shrinkage cracks that appear while the surface is still soft; it doesn't replace joints."))
    body += sec("Base movement", p("Water is the enemy. A downspout onto the base, a sprinkler line leaking under the slab, a swale that stopped draining, a driveway poured on backfill that was never compacted against the garage footing: each one moves sand out from under a panel and the panel drops. The fix is compaction in lifts, a proof roll, geotextile where the sand pumps, and drainage that leaves the lot. On the islands, surge does the same thing in a night."))
    body += sec("Loads", p("A 4-inch slab on a compacted base carries cars for decades. Delivery trucks, boat trailers, dumpsters and skid steers on a 3.5-inch 1960s slab crack it across the middle. Pads and driveways built for those loads are 6 inches with #4 bar."))
    body += sec("What a crack means", table(["Crack", "Likely cause", "Action"], [["Hairline, random, no step", "Shrinkage; joints late or too far apart", "Seal and watch; cosmetic"], ["Straight, at a joint line", "Working as designed", "Nothing"], ["Step across the crack", "Base moved", "Find the water; lift or replace"], ["Corner breaks near the garage", "Uncompacted backfill", "Compact and replace the panel"], ["Map cracking, scaling surface", "Wet finish, salt, poor cure", "Resurface if sound; replace if not"], ["Cracks radiating from a point", "Point load", "Thicker pad for that load"]], "Reading cracks"))
    body += sec("Related", cards([("/compare/rebar-vs-fiber/", "Rebar vs fiber", "What holds cracks shut."), ("/concrete/repair/", "Concrete repair", "Sealing, lifting, replacing."), ("/concrete/driveways/", "Driveways", "The spec that prevents it.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("why-concrete-cracks-sarasota", "Why Concrete Cracks in Sarasota (and What Prevents It)", "The three causes of cracked concrete in Sarasota County (shrinkage without same-day joints, base movement on Myakka sand, loads beyond the slab), how to read a crack, and the base prep and joint spacing that prevent most of them.",
              "Why concrete cracks in Sarasota, and what a crack is telling you", "Heat, sand and old slabs, in that order, and the joints and base that answer them.", body, faq)


def cure():
    faq = [("What happens if it rains on my pour during a July afternoon storm?", "In the first two hours after placement, rain washes cement paste off the surface, weakens the top and leaves dusting and scaling later; the crew covers the slab with plastic and refinishes what it can. After the surface has set (four to eight hours), rain does no harm and helps the cure. That's why summer pours start at 7 a.m."),
           ("How long before I can drive on a new driveway in Sarasota heat?", "Seven days for cars and SUVs, 24 hours for foot traffic, 28 days for trucks, boat trailers and heavy loads. Heat speeds early strength but doesn't shorten the 28-day mark, and it makes the 7-day cure protection more important, not less."),
           ("Does the concrete need to be watered?", "If a curing compound was sprayed, no; if the crew wet-cures, the slab stays damp for 7 days. Letting it dry out in the first week is the fastest way to a weak, dusty surface.")]
    body = facts([("Rain risk", "First 2 hours after placement"), ("Foot traffic", "24 hours"), ("Cars", "7 days"), ("Heavy loads", "28 days")])
    body += cap("When can I walk, drive and park on new concrete, and what does rain do?",
                "Foot traffic after 24 hours, cars after 7 days, heavy vehicles and trailers after 28. Rain in the first two hours after placement washes paste off the surface and weakens it; after the surface sets, rain is harmless. In Sarasota's wet season, with 7 to 9 inches of monthly rain arriving mostly in afternoon storms, pours start at 7 a.m. and are finished and protected by early afternoon.",
                p("Curing is the week after the pour, not the day of it. A curing compound or a wet cure for 7 days is what turns a 4,000 PSI mix into a 4,000 PSI slab; a slab left to dry in the sun reaches a fraction of that at the surface."))
    body += sec("The timeline", table(["Time", "What's happening", "What you can do"], [["0 to 2 h", "Placing, screeding, floating; surface soft", "Nothing; rain is the risk"], ["2 to 8 h", "Setting; finishing and joint cutting", "Keep off it; joints cut in this window"], ["24 h", "Surface hard; about 30% strength", "Walk on it"], ["3 days", "About 50% strength", "Light furniture"], ["7 days", "About 70% strength; cure protection ends", "Cars, SUVs; screen cage anchors"], ["28 days", "Design strength", "Trucks, trailers, heavy pads; sealing"]], "Concrete cure timeline; percentages are typical for a 4,000 PSI mix in warm weather"))
    body += sec("Heat and wind", p("Heat speeds the set and increases evaporation from the surface, which is what causes plastic shrinkage cracks in the first hours. Winter cold fronts bring dry, windy days that evaporate water off a slab faster than July does. Evaporation reducers, shade and an early start are the answers in both seasons."))
    body += sec("Pavers", p("Polymeric sand needs 24 to 48 dry hours after activation or it washes out; you can walk on a paver deck as soon as it's compacted and drive on a paver driveway as soon as the sand cures. Sealing waits 30 days."))
    body += sec("Related", cards([("/tools/pour-calendar/", "Pour calendar", "Month by month."), ("/guides/why-concrete-cracks-sarasota/", "Why concrete cracks", "Shrinkage and joints."), ("/concrete/driveways/", "Driveways", "Spec.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("cure-times-and-rain", "Cure Times & Rain: When to Walk, Drive and Park on New Concrete", "How rain in the first two hours affects a Sarasota pour, when you can walk (24 h), drive (7 days) and park heavy loads (28 days) on new concrete, why a 7-day cure matters in heat and wind, and the paver-sand equivalent.",
              "Cure times, rain and when you can drive on it", "Two hours of rain risk, seven days of cure, twenty-eight days to full strength, and a 7 a.m. start in summer.", body, faq)


def snowbird():
    faq = [("How do you run a job when the owner is out of state for the summer?", "Video estimate, e-signed scope with photos of every decision point, a property manager or neighbor as the on-site contact, daily photo reports, permit and ARC handled by the provider, and a schedule that ends before you fly in. Payment milestones tie to photographed stages."),
           ("What is the lead time in season versus summer?", "January through April: four to eight weeks to a start date, sometimes more. June through September: two to four weeks, with weather shaping pour days. Book summer work in March if you want it done before November."),
           ("How do I get a quote without being home?", "A video walkthrough on your phone or a neighbor's, plus your survey or site plan from closing and a few photos of the surface. That's enough for a written scope; the site visit confirms measurements before the contract is signed.")]
    body = facts([("Season", "Owners present Jan to Apr; away Jun to Sep"), ("Best work window", "May to October"), ("Deadline", "Finished before November"), ("Tools", "Video estimate, e-sign, daily photos, manager hand-off")])
    body += cap("How does a seasonal owner get a driveway or pool deck done while away?",
                "Decide in March, sign in April, build in the summer, come back in November to a finished job. The provider quotes from a video walkthrough and your survey, sends a scope you sign electronically, pulls the permit and prepares the ARC packet, works with your property manager or a neighbor as the on-site contact, sends photos every working day, and ties payments to photographed milestones. Summer lead times are the shortest of the year.",
                p("Sarasota County's population rises past 570,000 in winter and drops in summer; the crews' calendars follow. The owner who books in March gets the calendar and the price; the owner who calls in December gets a waiting list."))
    body += sec("The twelve-month version", table(["Month", "Step"], [["January to February", "Walk the property while you're here; photograph the surfaces; note what you want"], ["March", "Request the estimate; site visit while you're still in town; ARC packet drafted"], ["April", "Sign the scope; ARC submitted; permit application filed; deposit"], ["May", "Approvals in; materials ordered; start date set"], ["June to September", "Work, with daily photos; polymeric sand and sealing scheduled around dry gaps"], ["October", "Final inspection; care sheet; warranty issued; photos on file"], ["November", "You arrive to a finished deck"]], "Snowbird project calendar"))
    body += sec("What the provider handles remotely", ul(["Permit application and inspections.", "ARC packet preparation (you sign and submit; most associations require the owner).", "Utility locates, irrigation shut-off and re-run.", "Neighbor notice for street parking and noise.", "Daily photo reports and a weekly summary.", "Hand-off to the property manager: care sheet, sealing date, warranty."]))
    body += sec("What you handle", ul(["The survey or site plan from your closing.", "The association's current guidelines and your signature on the ARC form.", "Access: gate code, cage door, water and power.", "Decisions on color and pattern before you leave, with samples in hand.", "Insurance notice if the work is on a barrier island in a flood zone."]))
    body += sec("Related", cards([("/contact/", "Request a video estimate", "Start here."), ("/guides/deposits-and-warranties/", "Deposits and warranties", "What to sign."), ("/hoa/", "HOA and ARC", "The packet.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("snowbird-project-guide", "Snowbird Guide: Sarasota Hardscape Jobs From Out of State", "How seasonal owners get a driveway, patio or pool deck built in Sarasota while away: decide in March, sign in April, build in summer, return in November; video estimates, e-signed scope, permits and ARC handled, daily photos, manager hand-off.",
              "The snowbird project guide: decide in March, come back to a finished deck in November", "Video estimate, e-signed scope, daily photos and a schedule built around the season you're not here.", body, faq)


def deposits():
    faq = [("How much deposit is normal for a concrete or paver job in Florida and what should the contract say?", "For residential work, a modest deposit (often 10 to 30 percent) with the balance in progress payments tied to stages is normal; Florida Statute 489.126 requires a contractor who takes more than 10 percent to apply for the permit within 30 days and start work within 90 days of permits issuing, and a contractor who takes a deposit and doesn't perform faces criminal exposure. The contract states the legal name, license or registration, scope, price, payment schedule, start and completion windows, warranty and the lien-law notice."),
           ("What should a written warranty cover for pavers and concrete?", "Workmanship: base failure, joints cut late, scaling from a bad finish, settled pavers, edge restraint failure, joint sand loss in the first season. Excluded, normally: hairline shrinkage cracks, color variation, damage from vehicles over the design load, tree roots, storm surge, efflorescence, stains from irrigation or salt. Manufacturer warranties on pavers and sealers are separate documents."),
           ("What is the lien-law notice?", "Florida's construction lien law requires a notice in contracts over $2,500 explaining that subcontractors and suppliers can lien your property if the contractor doesn't pay them; a Notice of Commencement recorded for jobs over $5,000 and releases of lien with each payment protect you.")]
    body = facts([("Deposit", "Modest; Florida Statute 489.126 rules apply over 10%"), ("Payments", "Tied to photographed stages"), ("Contract over $2,500", "Lien-law notice"), ("Job over $5,000", "Notice of Commencement; lien releases")])
    body += cap("What should a deposit and a contract look like for hardscape in Florida?",
                "A deposit that's a fraction of the price, a payment schedule tied to stages you can see (demolition done, base inspected, pour or laying complete, final), and a contract that names the legal entity, its license or county registration, the scope with quantities and spec, price, start and completion windows, warranty terms and the lien-law notice Florida requires over $2,500. Under Florida Statute 489.126, a contractor who takes more than 10 percent must apply for permits within 30 days and start within 90 days of issuance.",
                p("A contractor who wants half up front for flatwork, won't put the payment schedule in writing, or won't name the entity is telling you how the job will go."))
    body += sec("The contract checklist", ol(["Legal name of the contractor, its license or Sarasota County certificate number, and insurance certificate.", "Scope: square footage, thickness or paver system, base depth and material, reinforcement, joints, drainage, demolition, disposal.", "Materials by manufacturer, product and color.", "Permit and ARC responsibility and who pays fees.", "Price, deposit, progress payments tied to stages, final payment on completion.", "Start window and completion window, with the weather clause stated plainly.", "Warranty: what's covered, for how long, how to claim.", "Lien-law notice (over $2,500); Notice of Commencement and lien releases (over $5,000).", "Change-order process in writing."]))
    body += sec("Related", cards([("/warranty/", "Warranty", "What the provider's terms cover."), ("/guides/verify-contractor-license-sarasota/", "Verify a contractor", "Before you sign."), ("/financing/", "Financing", "Payment schedules.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("deposits-and-warranties", "Deposits, Contracts & Warranties for Florida Hardscape", "What a deposit, payment schedule and contract should look like for a concrete or paver job in Florida: Statute 489.126 deposit rules, the lien-law notice, Notice of Commencement, a contract checklist and what a workmanship warranty should cover and exclude.",
              "Deposits, contracts and warranties: what to sign and what to refuse", "A modest deposit, payments you can photograph, a legal name on the page and a warranty you can read.", body, faq)


def verify():
    faq = [("How do I verify a concrete contractor's license in Sarasota County?", "Check the state first at myfloridalicense.com (DBPR) for a certified or registered contractor license; then check Sarasota County's contractor registration and Certificate of Competency through the county's licensing office, because Code Chapter 22 requires an Operating Certificate and Certificate of Competency for regulated trades; then ask for the certificate of insurance and the surety bond the county requires for registration."),
           ("Does a paver installer need a state license in Florida?", "No. Installing driveways and pavers is on the DBPR's list of work that doesn't require a state construction license. Counties and cities can require local registration or a competency card, and Sarasota and Charlotte counties do for regulated trades; Charlotte's Local Concrete Masonry license is one example."),
           ("What insurance should a concrete contractor show me?", "A certificate of general liability insurance naming you or the county as certificate holder, workers' compensation or a valid exemption, and, for county registration, the surety bond the county requires by category. Ask for the certificate directly from the insurer's agent, not a photocopy.")]
    body = facts([("State", "DBPR license lookup (myfloridalicense.com)"), ("County", "Sarasota County Operating Certificate + Certificate of Competency (Code Ch. 22)"), ("Charlotte", "Local Concrete Masonry or state license"), ("Always", "Insurance certificate, bond, permit history")])
    body += cap("How do I check a contractor before signing?",
                "Four lookups. The DBPR license search for a state license (not required for flatwork and pavers, but common); Sarasota County's contractor licensing office for the Operating Certificate and Certificate of Competency that Code Chapter 22 requires for regulated trades; the permit portal for the contractor's permit history and any citations; and the insurer's agent for a current certificate of liability and workers' compensation. Charlotte County accepts a Local Concrete Masonry license for driveway and slab permits.",
                p("Florida Statute 489.119(5)(b) requires a licensed contractor to put its license number on every advertisement, proposal and contract; a company that advertises \"licensed\" without a number is either unlicensed or careless. This site says \"Insured\" and nothing more until the provider's number is documented, which is the same standard you should hold everyone to."))
    body += sec("The four lookups", table(["What", "Where", "What you're looking for"], [["State license", "myfloridalicense.com, DBPR license search", "Active status, no discipline; the name matches the contract"], ["County registration and competency", "Sarasota County Planning & Development contractor licensing; Charlotte County Contractor Licensing", "Active Operating Certificate and Certificate of Competency in a relevant category"], ["Permit history", "building.scgov.net; city portals; Charlotte County records", "Permits pulled in the contractor's name; no unresolved violations"], ["Insurance and bond", "Certificate from the agent", "General liability, workers' comp or exemption, surety bond"]], "Verifying a contractor in Sarasota and Charlotte counties"))
    body += sec("Red flags", ul(["No legal entity name on the estimate.", "\"Licensed\" with no number.", "Asks you to pull the permit as owner-builder for work they're doing.", "Wants most of the money before demolition.", "Won't put the base depth or the joint spacing in writing.", "Can't produce an insurance certificate from the agent."]))
    body += sec("Related", cards([("/guides/deposits-and-warranties/", "Deposits and contracts", "What to sign."), ("/permits/sarasota-county/", "Sarasota County permits", "Contractor registration rules."), ("/about/", "About this site", "What we don't claim.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("verify-contractor-license-sarasota", "How to Verify a Concrete or Paver Contractor in Sarasota County", "Four lookups before you sign with a concrete or paver contractor in Sarasota or Charlotte County: DBPR state license, county Operating Certificate and Certificate of Competency, permit history, insurance and bond, plus the statute on license numbers in advertising.",
              "How to verify a contractor in Sarasota County before you sign", "State license if any, county registration and competency, permit history, insurance and bond. Four lookups, twenty minutes.", body, faq)


def rust():
    faq = [("How do I remove rust stains from well-water irrigation on pavers?", "With an oxalic-acid cleaner diluted per the label, applied with a pump sprayer, allowed to dwell without drying, lightly agitated and rinsed; test a corner first, keep it off travertine and marble (acid etches limestone), and expect to reseal afterward because rust removers strip most sealers."),
           ("How do I stop it coming back?", "Redirect or replace sprinkler heads so the spray doesn't cross the hardscape; add an iron filter or a sequestering-agent injector to the well irrigation system; seal the surface so iron sits on top of the sealer instead of in the pore."),
           ("Is it a problem east of I-75 only?", "Mostly. Fruitville, Bee Ridge, Nokomis east of the interstate, South Venice, North Port and much of Charlotte County irrigate from wells with dissolved iron; city water lots rarely see it.")]
    body = facts([("Cause", "Dissolved iron in well water oxidizing on the surface"), ("Where", "Well-irrigated lots east of I-75 and in South Venice, North Port, Charlotte"), ("Removal", "Oxalic-acid cleaner; not on limestone"), ("Prevention", "Head redirection, iron filter, sealer")])
    body += cap("Why does my driveway turn orange, and how do I fix it?",
                "Well water in this county carries dissolved iron; sprayed through sprinklers it meets air, oxidizes and drops rust on whatever it lands on. Removal is an oxalic-acid cleaner on concrete and concrete pavers (never on travertine, shellstone or marble, which acid etches), tested on a corner, dwelled, agitated and rinsed, followed by resealing. Prevention is heads that don't cross the hardscape, an iron filter or sequestering injector on the well system, and a penetrating sealer.",
                p("The stain is cosmetic; it doesn't hurt the concrete. Sealer that was already on the surface takes the stain instead of the pore, which is why sealed driveways clean up and unsealed ones hold the orange. For scale: the EPA's secondary drinking-water standard for iron is 0.3 mg/L, and irrigation wells east of I-75 commonly test at 1 to 5 mg/L; oxalic-acid cleaners are typically diluted 8:1 to 10:1 with water and dwell 5 to 10 minutes; a 600-square-foot driveway takes about 2 hours to clean and a day to dry before resealing."))
    body += sec("Removal by surface", table(["Surface", "Cleaner", "Notes"], [["Broom or textured concrete", "Oxalic acid (diluted per label)", "Reseal after"], ["Concrete pavers", "Oxalic acid", "Reseal; re-sand if joints are disturbed"], ["Travertine, shellstone, marble", "Neutral-pH rust remover made for natural stone", "No acid; test first"], ["Porcelain", "Almost anything", "Immune"], ["Stamped or sealed decorative", "Strip, clean, reseal", "Rust remover takes the sealer with it"]], "Rust stain removal"))
    body += sec("Prevention", ol(["Walk the irrigation zones and note every head whose spray crosses a slab or paver field; redirect, replace with a shorter-throw nozzle, or move it.", "Test the well water for iron; above about 0.3 ppm, an iron filter or a sequestering agent injector on the irrigation line is the durable fix.", "Seal the hardscape with a penetrating sealer so stains stay on the surface.", "Rinse the surface after any irrigation change."]))
    body += sec("Related", cards([("/pavers/sealing/", "Cleaning and sealing", "The service."), ("/compare/sealer-types-coastal/", "Sealer types", "Which one."), ("/areas/fruitville-bee-ridge/", "Fruitville and Bee Ridge", "Where wells are common.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("well-water-rust-stains", "Rust Stains From Well-Water Irrigation on Pavers & Driveways", "Why well-irrigated lots in Sarasota County get orange rust stains on driveways and pavers, how to remove them by surface (oxalic acid on concrete, never on limestone), and how to stop them with head redirection, iron filtration and sealer.",
              "Rust stains from well-water irrigation: removal by surface and prevention at the sprinkler", "Iron in the well, oxygen in the spray, orange on the slab. The fix is the sprinkler head, then the cleaner, then the sealer.", body, faq)


def sand():
    faq = [("What is polymeric sand and when should it be replaced?", "Fine sand mixed with a polymer binder that hardens when wetted, locking pavers together and resisting wash-out, weeds and ants. A properly installed full-depth joint lasts 8 to 12 years or more; shallow or badly drained joints fail in 3 to 5. It's topped up when joints drop more than a quarter inch and replaced when the field is lifted."),
           ("Why do weeds and ants keep coming back between my pavers?", "Because the joint sand is gone or was plain sand. Weeds seed into open joints from above, not up from below; ants tunnel where sand is loose. Cleaning the joints out and installing polymeric sand to full depth, activated on a dry day, ends most of it; sealing on top helps."),
           ("Can polymeric sand be installed in the rainy season?", "On a two-day dry forecast. Rain in the first 24 hours after activation reactivates the polymer and washes it out, leaving a haze on the pavers and empty joints.")]
    body = facts([("What it is", "Sand plus a polymer binder that sets when wetted"), ("Life", "8 to 12 years full depth; 3 to 5 if shallow or wet"), ("Weeds", "Seed from above into empty joints"), ("Install", "Dry pavers, full depth, activate, 24 to 48 dry hours")])
    body += cap("What does polymeric sand do, and why do weeds mean it's gone?",
                "It fills the joints between pavers and, once activated with water, sets into a firm but flexible seal that locks the units, resists wash-out and blocks weeds and ants. Weeds seed into open joints from above, so a weedy paver field is a field whose joint sand is missing or was plain sand. Full-depth joints last 8 to 12 years when the base drains; they're topped up when they drop a quarter inch.",
                p("The most common failure is installation: sand swept into damp pavers, activated too heavily, or rained on within a day. Done right on a dry surface with a two-day dry forecast, it's the least expensive thing that keeps a paver field looking installed."))
    body += sec("Installation, step by step", ol(["Pavers dry and clean; joints emptied to at least two-thirds of the paver depth.", "Sand swept into the joints, then compacted with a plate compactor and a pad so the sand settles.", "Second sweep to fill; surface blown or swept clean so no sand dust is left on the face (it hazes).", "Activation with a fine mist in passes, never a stream; the polymer sets as it dries.", "24 to 48 dry hours before rain or irrigation; longer for thick joints."]))
    body += sec("Weeds, ants and the sand", table(["Symptom", "Meaning", "Fix"], [["Weeds in a line", "Joint sand gone along that line, often a drainage path", "Clean, re-sand, check the drain"], ["Ant hills at the joints", "Loose plain sand", "Polymeric re-sand"], ["Sand washed into the lawn after storms", "Shallow joints or no polymer", "Full-depth polymeric"], ["Haze on the pavers", "Sand dust left on the face at activation", "Efflorescence cleaner"], ["Hard crust that cracked", "Activated with too much water", "Remove and redo"]], "Joint sand problems"))
    body += sec("Related", cards([("/pavers/sealing/", "Cleaning, re-sanding and sealing", "The service."), ("/guides/efflorescence/", "Efflorescence", "The other white haze."), ("/pavers/repair-storm-restoration/", "Repair", "When the field has to be lifted.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("polymeric-sand-weeds-ants", "Polymeric Sand, Weeds & Ants: Paver Joints Explained", "What polymeric sand does for pavers in Sarasota County, how long full-depth joints last, why weeds and ants mean the sand is gone, how it's installed and activated, and the symptoms that point to a joint or drainage problem.",
              "Polymeric sand, weeds and ants: what the joints are telling you", "Weeds come from above into empty joints. Fill them right and they stop.", body, faq)


def efflor():
    faq = [("What is efflorescence on new pavers and will it go away?", "A white, powdery deposit of soluble salts carried to the surface by water evaporating from the paver body and the bedding. On new concrete pavers it's expected, peaks in the first weeks and mostly washes away over a few months of rain; where it persists, an efflorescence cleaner removes it. Sealing before it has worked out traps it under the sealer as a permanent haze."),
           ("Is it the same as sealer blush?", "No. Sealer blush is a film sealer turning white from moisture trapped underneath; it needs stripping. Efflorescence sits on the surface and brushes off dry."),
           ("Does travertine get it?", "Less, but calcium carbonate can show a similar haze from hard water and bedding minerals; the same neutral cleaner and patience apply, never acid.")]
    body = facts([("What", "Soluble salts brought to the surface by water"), ("When", "First weeks after install; after wet months"), ("Goes away?", "Mostly, with rain and time"), ("Don't", "Seal before it's gone; use acid on stone")])
    body += cap("Why do new pavers turn white, and what should I do?",
                "Water moving through concrete pavers and their bedding dissolves salts from the cement and carries them to the surface, where it evaporates and leaves a white haze called efflorescence. It's expected on new installs, peaks in the first weeks and mostly disappears over a few months of rain. Wait 30 days before sealing so it can work out; if it persists, an efflorescence cleaner made for pavers removes it. Acid on travertine or marble etches the stone.",
                p("Sealed too early, the salts are locked under the sealer as a permanent white cloud, and the fix is stripping the sealer. That's the reason every paver job here schedules sealing at 30 days, not on the last day of the install."))
    body += sec("Timeline", table(["When", "What you see", "What to do"], [["Week 1 to 4", "White haze after each rain", "Nothing; brush dry"], ["Month 2 to 3", "Fading", "Rinse; still no sealer"], ["Month 3+", "Gone or faint", "Clean with efflorescence cleaner if needed; seal"], ["Years later, after wet months", "Reappears in low spots", "Drainage check; clean"]], "Efflorescence timeline"))
    body += sec("Related", cards([("/pavers/sealing/", "Sealing", "Why it waits 30 days."), ("/guides/polymeric-sand-weeds-ants/", "Polymeric sand", "The other haze: sand dust."), ("/compare/sealer-types-coastal/", "Sealers", "Film blush explained.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("efflorescence", "Efflorescence on New Pavers: Why They Turn White & What to Do", "Why new concrete pavers in Sarasota show a white haze (salts carried up by water), the weeks-to-months timeline, why sealing before 30 days traps it, how to clean it without acid on stone, and how it differs from sealer blush.",
              "Efflorescence: the white haze on new pavers, and why sealing early makes it permanent", "Salts, water and evaporation. Wait, rinse, then seal.", body, faq)


def permeable():
    faq = [("Does the 50 percent impervious-coverage limit stop my driveway extension?", "It can. Sarasota County's zoning code (Appendix A, § 6.5) caps impervious coverage at 50 percent of the lot in RSF districts, and roofs, pool decks, concrete, asphalt and pavers count while grass, shell and pervious surfaces don't. A small lot with a large house and a pool cage can be at the cap before the driveway grows; the county's zoning review checks it."),
           ("Do permeable pavers count as impervious in Sarasota County?", "The code excludes surfaces that allow water to substantially penetrate into the ground, and permeable interlocking concrete pavement on an open-graded stone base is designed to do exactly that; the county's Low Impact Development guidance recognizes pervious pavement systems. Confirm the credit with zoning for your parcel before designing to it."),
           ("Are permeable pavers strong enough for a driveway?", "Yes. Permeable interlocking concrete pavement is designed for vehicle loads on an open-graded base per ICPI practice; the joints are wider and filled with small clean stone instead of sand, and the base is deeper.")]
    body = facts([("Cap", "50% of the lot, RSF districts (Sarasota County App. A § 6.5)"), ("Counts", "Roofs, pool decks, concrete, asphalt, pavers"), ("Doesn't", "Grass, shell, pervious surfaces"), ("Solution", "Permeable interlocking concrete pavement")])
    body += cap("What is Sarasota County's 50 percent impervious cap, and how do permeable pavers get around it?",
                "In unincorporated Sarasota County's RSF single-family districts, impervious coverage is capped at 50 percent of the lot, and the code counts roofs, swimming pools and pool decks, concrete, asphalt, pavers and any surface that substantially prevents water penetrating the ground, while excluding grass, shell and surfaces that let water through. Permeable interlocking concrete pavement on an open-graded stone base is designed to let water through and is the driveway or patio answer on a lot at the cap.",
                p("Cities inside the county (Sarasota, Venice, North Port) have their own coverage rules, and associations sometimes count turf and permeable pavers as impervious in their own guidelines even when the county doesn't."))
    body += sec("How a permeable driveway is built", ol(["Subgrade excavated deeper than a standard driveway and left uncompacted at the bottom where infiltration is wanted, or lined and underdrained where the water table is too high.", "Open-graded stone base: 8 to 12 inches of washed No. 2 or No. 57 stone with no fines, in lifts.", "Bedding of washed No. 8 stone, 2 inches.", "Permeable pavers with spacer bars, joints 3/8 inch or wider, filled with No. 8 or No. 9 stone.", "Edge restraint, compaction, and a maintenance note: joints are vacuumed, never sanded."]))
    body += sec("Cost and where it makes sense", p("Planning range $18 to $30 per square foot installed (September 10, 2026) versus $14 to $22 for standard pavers, for the deeper washed-stone base. It makes sense when the lot is at the cap, when the county's stormwater review needs the credit, and on flat lots where a standard driveway would send water at the neighbor. On lots with a wet-season water table within a foot, the design includes an underdrain."))
    body += sec("Related", cards([("/pavers/driveways/", "Paver driveways", "Standard and permeable."), ("/permits/sarasota-county/", "Sarasota County permits", "Zoning and right-of-way."), ("/areas/sarasota-county/", "Sarasota County hub", "The county code in context.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("permeable-pavers-impervious-limit", "Permeable Pavers & Sarasota County's 50% Impervious Limit", "Sarasota County caps impervious cover at 50% of an RSF lot and counts pool decks, concrete and pavers; permeable interlocking concrete pavement on an open-graded base lets water through, carries vehicles and costs $18 to $30 per sq ft. How it's built and when it's the answer.",
              "Permeable pavers and the 50 percent impervious limit", "When the lot is at the cap, the driveway that lets water through is the one the county allows.", body, faq)


def golf():
    faq = [("Does a golf-cart path or driveway widening need approval in Venice-area communities?", "Yes, from the association first: cart pads and second driveways are among the most common ARC denials because they change the streetscape. Then from the city or county for anything at the street, where Venice requires engineering review and North Port a Right of Way Use Permit."),
           ("Do golf-cart communities in Venice allow a second driveway for the cart?", "Some do, with rules on width, material and placement; many allow a cart pad beside the main driveway inside the garage wall line but not a second curb cut. The community's current guideline is the only source that counts."),
           ("What's the spec for a cart path?", "Four inches of broom concrete or concrete pavers on 4 inches of compacted base, 5 to 6 feet wide, sloped to drain; a cart weighs less than a car, so the driveway spec is more than enough.")]
    body = facts([("First question", "The association's rule on cart pads and second driveways"), ("Second", "The city or county at the street"), ("Spec", "4 in. concrete or pavers on 4 in. base, 5 to 6 ft wide"), ("Where", "Venice, Wellen Park, North Port, The Meadows, Palmer Ranch, Rotonda")])
    body += cap("Can I add a golf-cart path or pad at my Sarasota-area home?",
                "On the lot, usually, with ARC approval; at the street, only if the community allows a second access and the jurisdiction approves the apron. Venice, Wellen Park, Venice Golf & Country Club, Rotonda West and several Palmer Ranch and Meadows sections are cart-friendly on their own paths, but a cart pad that widens the driveway past the garage wall line or adds a curb cut is the change committees deny most. Build the pad inside the line, in the driveway's material, and submit the packet.",
                p("The construction is trivial: a cart weighs less than a car, so 4 inches of concrete or pavers on 4 inches of base at 5 to 6 feet wide carries it. The approvals are the project."))
    body += sec("Where carts are common", table(["Community", "Cart use", "Hardscape note"], [["Wellen Park (Venice and North Port sides)", "Community paths; street-legal LSVs on some streets", "Village ARC; two permit offices"], ["Venice Golf & Country Club, Pelican Pointe", "Cart living on course streets", "Club and HOA rules on pads"], ["The Meadows", "Course paths", "Master and sub-association"], ["Rotonda West", "Course communities", "Association deed restrictions"], ["Venice Island and Historic Downtown", "City-designated streets", "City right-of-way review"]], "Cart-friendly areas near Venice; rules are each community's own"))
    body += sec("Related", cards([("/hoa/wellen-park/", "Wellen Park review", "Width rules."), ("/concrete/driveways/", "Concrete driveways", "Spec and extensions."), ("/permits/venice/", "Venice permits", "Right-of-way.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("golf-cart-paths", "Golf-Cart Paths & Second Driveways in Venice-Area Communities", "Whether a golf-cart pad, path or second driveway is allowed at Sarasota-area homes: the association's width and curb-cut rules come first, the city or county at the street second, and the 4-inch spec that carries a cart last.",
              "Golf-cart paths and second driveways: the approvals are the project", "The pad is easy. The committee and the curb cut are not.", body, faq)


def gdc():
    faq = [("What is different about pouring a driveway on a North Port GDC lot with a swale?", "The swale is the lot's drainage and the driveway crosses it on a culvert the city sizes under a Right of Way Use Permit; the crossing is formed to the city detail, the swale is regraded on both sides, and Public Works inspects it before final. On the lot, deep sand needs a compacted base and a slope that reaches the swale."),
           ("Do all North Port driveways need a culvert?", "Most on the original grid do, because most lots front a swale; lots on curbed streets in newer subdivisions and Wellen Park don't."),
           ("What if my existing culvert is crushed?", "It's replaced with the size the city specifies, under the same permit; a crushed culvert is the usual reason a driveway is dammed and the yard floods.")]
    body = facts([("Platted by", "General Development Corp., 1950s to 1980s"), ("Drainage", "Roadside swales, often shallow"), ("Permit", "City Right of Way Use Permit (Culvert/Driveway/Sidewalk/Concrete Slab)"), ("Soil", "Deep Myakka and Immokalee sands")])
    body += cap("Why is a North Port driveway a drainage project first?",
                "Because General Development Corporation platted tens of thousands of quarter-acre lots from the 1950s to the 1980s and drained them with roadside swales that were often left shallow or pitched the wrong way. Every driveway crosses one on a culvert, the city sizes the pipe and permits the crossing under its Right of Way Use Permit, the swale is regraded both sides, and the Public Works Department inspects it. On the lot, deep sand wants a compacted base and a slope that reaches the swale.",
                p("Pour the crossing flat with no pipe and the swale dams; the yard next door floods and the city writes it up. The same applies across the county line in Port Charlotte's GDC grid, where Charlotte County permits the crossing."))
    body += sec("The crossing, step by step", ol(["Right of Way Use Permit application with the site plan showing the swale, the culvert location and the driveway.", "City sizes the culvert (typically 15 to 18 inches) and sets the invert elevations; ends set back from the frontage lines.", "Old culvert removed; new pipe set on bedding at the city's grade; mitered ends or headwalls per detail.", "Swale regraded on both sides to the original flow line.", "Driveway crossing formed to the detail; concrete 6 inches over the pipe where required.", "Public Works inspection of the swale and pipe; final."]))
    body += sec("On the lot", p("Deep sand drains fast at the surface and holds water at depth; a 1980s driveway poured on it with no base has settled at the garage and cracked in the middle. Replacement is 4 to 6 inches of compacted base, a 4-inch 4,000 PSI slab with fiber and #3 bar, joints at 8 feet, and a slope that carries water to the swale, not to the neighbor. Pavers get 6 inches of base and a concrete curb at the swale."))
    body += sec("Related", cards([("/permits/north-port/", "North Port permits", "The permit and the office."), ("/areas/north-port/", "North Port locality page", "Housing and a worked example."), ("/concrete/driveways/north-port/", "Concrete driveways in North Port", "Spec and price band.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("north-port-gdc-lot-driveways", "Driveways on North Port GDC Lots: Swales, Culverts & Permits", "Why a driveway on a North Port GDC lot starts with the swale: the city-sized culvert, the Right of Way Use Permit, Public Works inspection, the deep-sand base on the lot, and the crossing built step by step.",
              "Driveways on North Port GDC lots: the swale, the culvert and the permit", "Tens of thousands of quarter-acre lots, one drainage system, and a crossing the city sizes and inspects.", body, faq)


def condo():
    faq = [("How does a condo board phase a pool deck project with a reserve study?", "The reserve study's remaining-life estimate sets the year; the board budgets from reserves (pavement resurfacing and any item over $10,000 are statutory reserve components under Florida Statute 718.112), takes comparable bids on a written scope in the fall, votes in winter when owners are present, and builds in phases from May to September so half the deck stays open."),
           ("What if reserves are short?", "A special assessment, voted under the association's documents; the shortfall usually traces to a component list that never added the last resurfacing. Update the study before bidding."),
           ("How long does a phased deck take?", "Two to four weeks per phase for a typical 2,000 to 4,000 square foot common deck, with a week between phases to swap the temporary edge and reopen.")]
    body = facts([("Statute", "F.S. 718.112(2)(f) reserves"), ("Bid season", "Fall"), ("Vote", "Winter, owners present"), ("Build", "May to September, phased")])
    body += cap("What does a twelve-month pool deck calendar look like for a condo board?",
                "Reserve study reviewed in August and the deck component updated; scope written in September so every bidder prices the same base, drains, coping, edge and lighting; bids in October and November; board vote in January or February when owners are present; permit and, where relevant, setback and lighting checks in March; phase one in May, phase two in July, reopening in August, warranty and photos filed in September. Florida Statute 718.112(2)(f) makes pavement resurfacing a reserve item.",
                p("The board's job is the scope and the calendar; the contractor's is the base and the phasing. A scope that doesn't specify base depth, drains and edge restraint produces bids that can't be compared and a deck that can't be warranted."))
    body += sec("Twelve months", table(["Month", "Board", "Contractor"], [["August", "Review reserve study; confirm deck year and funding", ""], ["September", "Write the scope with a consultant or the leading bidder", "Site survey, sounding, drain check"], ["October to November", "Solicit comparable bids", "Bid with phasing plan and dates"], ["December", "Compare bids line by line", ""], ["January to February", "Vote; contract; deposit", "Order materials"], ["March", "Permit; ARC or setback and lighting checks; owner notice", "Permit application; NOC"], ["April", "Phase plan communicated; furniture plan", "Mobilization"], ["May to June", "Phase one; half the deck open", "Demolition, base, drains, coping, field"], ["July to August", "Phase two", "Same; sand; reopen"], ["September", "Warranty, photos, sealing date filed", "Sealing at 30 days"]], "Condo pool deck calendar"))
    body += sec("The comparable-bid scope", ul(["Square footage, coping linear feet, cage anchors.", "Base depth and material, geotextile, drains and their outlet.", "Material, manufacturer, color, pattern; coping profile.", "Edge restraint type at each edge.", "Phasing plan with dates and temporary edge details.", "ADA access, slip rating (wet DCOF 0.42), lighting compliance on beach-visible decks.", "Warranty terms, insurance, permit responsibility, legal name."]))
    body += sec("Related", cards([("/hoa/barrier-island-condos/", "Barrier-island condos", "Rules and reserves."), ("/pavers/pool-decks/", "Paver pool decks", "Spec."), ("/pricing/pool-decks/", "Pool deck costs", "Ranges to multiply.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("condo-pool-deck-boards", "Condo Pool Deck Replacement: A 12-Month Calendar for Boards", "A month-by-month calendar for Sarasota-area condominium boards replacing a pool deck: reserve study under F.S. 718.112, a comparable-bid scope, fall bids, a winter vote, a permit in March and a phased May-to-September build that keeps the pool open.",
              "A twelve-month pool deck calendar for condo boards", "Reserve study in August, bids in the fall, vote in winter, phased build in summer, reopen before the owners are back.", body, faq)


def insurance():
    faq = [("How do I document hardscape damage for a hurricane insurance claim?", "Date-stamped photographs before the storm (every May) and after it before anything is moved, close and wide, with a tape or a known object for scale; the waterline on walls; the direction pavers moved; drains and edges; the survey pins. Then a written assessment from the contractor separating site work (deck, driveway, pavers) from the building, with a repair scope and price, and the pre-storm invoices for what was there."),
           ("Is hardscape covered?", "Depends on the policy: many homeowner policies exclude or limit \"other structures\" and site improvements, and flood policies through the NFIP generally don't cover decks, driveways and pavers. Read the policy; document anyway, because wind and debris damage is treated differently from flood."),
           ("Why separate site work from the building?", "Because the building's repairs count toward the NFIP 50 percent substantial-damage threshold and site work doesn't; a bundled invoice can push a building into full flood compliance unnecessarily.")]
    body = facts([("Before", "Photos every May; invoices on file"), ("After", "Photos before anything moves"), ("Separate", "Site work from building repairs"), ("Then", "Contractor assessment with scope and price")])
    body += cap("What should I send the insurer after a storm damages my pool deck or driveway?",
                "Pre-storm photos (taken every May, date-stamped), post-storm photos before anything is touched, the waterline height and the direction things moved, a contractor's written assessment that lists the damage, separates site work from the building, and states the repair scope and price, and the invoices for the original work. Keep hardscape on its own invoice so the building's substantial-damage calculation under the NFIP 50 percent rule isn't inflated by a deck.",
                p("Coverage varies: homeowner policies often limit other structures, and NFIP flood policies generally exclude decks, driveways and pavers. Document regardless, because wind, debris and surge are adjusted differently and the assessment is also what the permit office wants."))
    body += sec("The file", ol(["May photo set: every surface, close and wide, drains, edges, coping, survey pins; saved to the cloud.", "Post-storm photo set before cleanup: same angles, plus waterlines and displaced items.", "A sketch of what moved where.", "Contractor assessment: damage list, cause (surge, wind, debris), site work vs building, scope, price, timeline.", "Original invoices and warranty for the hardscape.", "Permit records for the hardscape.", "Correspondence log with the adjuster."]))
    body += sec("Related", cards([("/coastal/storm-season-playbook/", "Storm season playbook", "The May checklist."), ("/coastal/post-storm-restoration/", "Post-storm restoration", "What happens after the photos."), ("/permits/flood-zones-50-percent-rule/", "The 50% rule", "Why site work is separated.")]))
    body += faq_block(faq)
    body += reviewed("September 10, 2026")
    return pg("hurricane-insurance-documentation", "Documenting Hardscape Storm Damage for an Insurance Claim", "What to photograph before and after a hurricane, how to separate pool deck, driveway and paver damage from the building for the NFIP 50% rule, what the contractor's assessment should contain, and what homeowner and flood policies usually cover.",
              "Documenting hardscape damage for an insurance claim", "Photos in May, photos before cleanup, an assessment that keeps site work off the building's ledger.", body, faq)


def ask():
    body = cap("What is Ask the Estimator?",
               "A public, weekly log of real questions received by phone and through the estimate form, anonymized, with a short answer and a link to the page that answers it in full. Entries begin the week the phone number and form go live; nothing here is invented to fill space. The log feeds the FAQ pages and, when a question earns it, a new guide. An RSS feed is at /feed.xml.",
               p("Each entry carries the week, the locality (never the address), the service, the question as asked, the short answer and the canonical link. Questions that reveal a gap in the site get a page."))
    body += note("No entries yet. The first entries are posted the week the Sarasota Concrete phone number and form go live (see OWNER-INPUTS in the project for what's pending).", "warn")
    body += sec("Format of an entry", table(["Field", "Example"], [["Week", "Week of November 2, 2026"], ["Locality", "Siesta Key"], ["Service", "Paver pool deck"], ["Question as asked", "Our travertine is flaking along the pool. Is it the salt system?"], ["Short answer", "Probably. Unsealed travertine at a salt pool's waterline flakes as salt crystallizes in the stone. Seal the coping annually with a penetrating product, rinse weekly, and replace the worst pieces."], ["Canonical page", "/pavers/travertine-shellstone/"]], "Entry template (example only; not a real entry)"))
    body += sec("Subscribe", p(link("/feed.xml", "RSS feed")))
    body += reviewed("September 10, 2026")
    return pg("ask-the-estimator", "Ask the Estimator: Real Sarasota Hardscape Questions, Weekly", "A weekly log of real questions from Sarasota-area homeowners about concrete, pavers, pool decks, permits and storms, anonymized and answered with a link to the full page. Entries begin when the line goes live; RSS at /feed.xml.",
              "Ask the Estimator", "Real questions, answered weekly, with the page that answers them in full.", body)


def get_pages():
    return [hub(), cracks(), cure(), snowbird(), deposits(), verify(), rust(), sand(), efflor(), permeable(), golf(), gdc(), condo(), insurance(), ask()]
